export default {
  vi: {
    girl: { base: [], crush: [], named: [] },
    boy: {
      base: [
        "Thưa quý vị khán giả, xin một tràng pháo tay cho {goi} của tui!",
        "Tui nhìn {goi} chơi mà tim tui đập nhanh hơn cả tốc độ chuột luôn.",
        "Xin giới thiệu, nhân vật chính của đêm nay, chính là {goi}! Pháo tay đâu!",
        "{Goi} ơi, tui ở đây cổ vũ {goi} nè, {goi} cứ yên tâm mà gánh team.",
        "Ha ha ha, {goi} chơi hay quá, tui cười luôn một mình luôn nè!",
        "Tui xin phép khóc một chút, vì {goi} chơi hay quá chịu không nổi.",
        "Quý vị thấy chưa, đó là {goi} của tui đó, giỏi chưa!",
        "Có {goi} trong team thì tui ngủ ngon luôn, thật đó.",
        "{Goi} thắng thì tui vui, {goi} thua thì tui vẫn vui, vì tui là fan mà!",
        "Chương trình hôm nay do {goi} trình diễn, tui chỉ làm MC thôi nha!",
        "Pha vừa rồi, tui xin phép quay chậm lại ba lần để ngắm cho kỹ.",
        "{Goi} cho tui ngồi cạnh xem chơi nha, tui hứa im lặng. Chắc vậy.",
        "Tui nói trước, ai chê {goi} là tui giận thiệt đó nha!",
        "Bản tin nóng: {goi} vừa chơi hay đến mức màn hình xin nghỉ phép.",
        "Xin một tràng pháo tay thật to, to hơn tiếng bàn phím của {goi} nữa!",
        "{Goi} ơi, đừng bỏ tui nha, tui còn muốn xem {goi} chơi thêm nhiều ván nữa.",
        "Tui hồi hộp quá, tay tui run còn hơn tay {goi} luôn á!",
        "Ê, {goi} chơi gì mà mượt như bơ vậy, cho tui xin công thức!",
        "Khán giả bên dưới đang đứng hết dậy rồi nha {goi}, ngồi xuống không nổi!",
        "Tui đi khoe với cả server là {goi} của tui chơi đỉnh nhất rồi nè.",
        "Tui chưa từng thấy ai bình tĩnh như {goi}, tui lo hơn cả {goi} luôn.",
        "{Goi} ơi, ván này mà win là tui mời {goi} một ly trà đá ảo nha!",
        "Và người chiến thắng của đêm nay, không ai khác, chính là {goi}!",
        "Tui ngồi xem mà quên luôn chuyện ăn cơm, {goi} chịu trách nhiệm đi!",
        "Hôm nay tui thấy {goi} chơi, tui tin vào nhân phẩm luôn.",
        "{Goi} thở một cái thôi là tui đã thấy ngầu rồi, nói chi đến pha vừa rồi.",
        "Cứu tui, {goi} chơi hay quá, tui phải ngồi xuống uống miếng nước đã.",
        "Quý vị khán giả ơi, tiếng vỗ tay đâu rồi, {goi} vừa làm xong một phép màu!",
        "Tui xin tuyên bố, {goi} là niềm tự hào của cái server này!",
        "Nếu {goi} thua thì tui khóc, mà khóc to lắm nha, nên cố lên đi!",
        "{Goi} chơi hay vậy mà còn khiêm tốn nữa, tui thương {goi} ghê.",
        "Tui nói thiệt, xem {goi} chơi còn vui hơn xem phim nữa đó.",
        "Có ai thấy pha đó không? Tui thấy rồi, tui còn muốn xem lại nữa nè!",
        "Chuột của {goi} có phép thuật hả, sao đi đâu trúng đó vậy trời!",
        "Tui cổ vũ {goi} tới khi nào hết hơi thì thôi, mà tui nhiều hơi lắm nha.",
        "Hỡi những người đang xem, hãy nhớ tên {goi}, vì sau này {goi} sẽ nổi tiếng!",
        "Tui kể cho {goi} nghe nè, tui xem {goi} chơi mà cười như được mùa vậy đó.",
        "Một pha xử lý như vậy, tui xin phép đứng dậy cúi chào {goi}.",
        "{Goi} cứ chơi đi, tui lo phần vỗ tay, phần này tui làm giỏi lắm!",
        "Ván này {goi} mà thắng, tui hứa sẽ kể chuyện này cho cả xóm nghe.",
        "Alo alo, đài phát thanh xin thông báo, {goi} đang chơi cực kỳ đỉnh!",
        "Ôi {goiLong} ơi, chơi gì mà hay dữ vậy, tui mê luôn rồi nè!",
        "Tui mà là đối thủ của {goi}, tui đầu hàng ngay từ giây đầu tiên.",
        "Xin phép tặng {goi} một cái huy chương bằng giấy, tui tự làm đó nha!",
        "Kính thưa quý vị, {goi} của chúng ta lại tiếp tục làm nên lịch sử!",
        "Tui có chút cảm động, vì {goi} chơi tiến bộ quá chừng luôn.",
        "{Goi} ơi, cho tui mượn bí quyết đi, tui trả bằng một tràng pháo tay.",
        "Tui nói nhỏ nghe nè, {goi} là người chơi tui nể nhất cái server này.",
        "Đừng lo lag, đừng lo ping, có tui ngồi đây cầu nguyện cho {goi} rồi.",
        "Tui xem {goi} chơi mà cười đau cả bụng, vì hay quá nên cười đó nha!",
        "Cái pha vừa rồi nên được đưa vào sách giáo khoa luôn, {goi} ơi.",
        "Chương trình xin được tạm dừng một phút để vỗ tay cho {goi}.",
        "{Goi} chơi một ván là tui hạnh phúc cả ngày, không xạo đâu.",
        "Tui là MC chuyên nghiệp mà còn nói không nên lời, {goi} giỏi thiệt.",
        "Nhìn {goi} bình tĩnh clutch mà tui muốn ôm màn hình luôn á!",
        "Có {goi} ở đây thì tui không sợ gì hết, kể cả ván khó nhất.",
        "Thưa quý vị, đây không phải là phim, đây là {goi} đang chơi thật đó!",
        "Ê {goi}, nghỉ tay một chút đi, để tui vỗ tay cho kịp với pha trước nè.",
        "Tui tin {goi} nhiều hơn tin dự báo thời tiết luôn đó.",
        "{Goi} chơi hay quá, tui đang nghĩ cách quảng cáo cho {goi} nè.",
        "Tui vừa gọi cho mẹ khoe là có người chơi hay vậy đó, {goi} ơi.",
        "Xin quý vị giữ trật tự, {goi} của tui đang làm việc lớn!",
        "{Goi} cứ yên tâm, đồng đội mà quay lưng thì tui vẫn đứng sau cổ vũ.",
        "Ơ kìa, {goi} lại làm được nữa rồi, tui sắp hết từ để khen luôn nè.",
        "Trời ơi {goi} ơi, tui nổi hết da gà, da vịt, da ngỗng luôn rồi!",
        "Tui xin hứa sẽ ngồi xem {goi} chơi đến ván cuối, dù trời có sập.",
        "Giỏi quá giỏi quá, tui khen hoài mà vẫn chưa thấy đủ nè {goi}!",
        "Hôm nay tui cười nhiều nhất nhờ {goi}, cảm ơn {goi} nha.",
        "Bản tin thể thao: {goi} dẫn đầu về độ ngầu, các đối thủ xin chào thua.",
        "Tui cá một ly trà sữa là {goi} sẽ win ván này, ai chơi không?",
        "Nếu có giải Oscar cho game thủ, tui sẽ đi vận động cho {goi} liền.",
        "{Goi} ơi, nhớ uống nước nha, vì tui muốn xem {goi} chơi lâu thiệt lâu.",
        "Tui đứng trên khán đài, vẫy cờ hết cỡ cho {goi} nè!",
        "Mỗi lần {goi} ghi điểm, tui lại muốn nhảy tưng tưng ngoài sân luôn.",
        "Cho tui xin chữ ký của {goi} đi, sau này tui còn đem khoe.",
        "Thưa quý vị, hãy tưởng tượng một người chơi hay đến thế, và đó chính là {goi}!",
        "Đồng đội của {goi} chắc đang hạnh phúc lắm, tui đoán vậy đó.",
        "Tui ngồi đây hồi hộp như chờ kết quả thi, mà {goi} thì toàn điểm mười.",
        "{Goi} giỏi tới mức tui phải kể cho cả nhà hàng xóm nghe luôn.",
        "Tui không biết khen sao nữa, thôi tui vỗ tay cho {goi} hoài hoài nha.",
        "Chương trình có quà đặc biệt, quà đó là một lời khen thiệt lòng cho {goi}!",
        "Chơi hay vậy là phải có fan club, và tui xin làm hội trưởng cho {goi}.",
        "Ván này {goi} mà gánh nổi thì tui kể cho con cháu nghe luôn.",
        "{Goi} ơi, tui nói thiệt, tui nhớ {goi} mỗi lúc {goi} đi lấy nước đó.",
        "Xin quý vị ghi nhận, ngày hôm nay, {goi} đã chơi hay hơn ngày hôm qua!",
        "Tui chỉ muốn nói một câu thôi: {goi} đỉnh quá trời quá đất luôn!",
        "Tui là người đầu tiên bấm like cho pha này, và cũng là người cuối cùng.",
        "{Goi} chơi mà tui ngồi im re, vì sợ làm {goi} mất tập trung đó.",
        "Tui thấy {goi} căng thẳng thì tui cũng căng, mà {goi} vẫn ngầu hơn tui.",
        "Quý vị khán giả, xin hãy dành tặng {goi} một nụ cười thật tươi!",
        "Tui phát hiện ra bí mật rồi, bí mật của {goi} là chăm chỉ và hay.",
        "Lỡ có thua thì {goi} vẫn là nhà vô địch trong lòng tui nha.",
        "Cho tui ngồi ghế đầu xem {goi} chơi đi, tui trả tiền vé bằng tiếng cười.",
        "Hôm nay tui mệt mà xem {goi} chơi là tỉnh liền, hay hơn cà phê nữa.",
        "Phát thanh viên xin thông báo, {goi} vừa phá kỷ lục độ đỉnh của server!",
        "Tui xin đại diện cho cả đám, gửi tới {goi} lời khen nồng nhiệt nhất!",
        "{Goi} chơi hay vậy mà tui còn chưa kịp chuẩn bị bài phát biểu nữa.",
        "Thôi xong, tui mê {goi} chơi game mất rồi, biết làm sao đây ta.",
        "Tui nói với {goi} nè, có {goi} thì ván nào cũng như ván chung kết.",
        "Khoan đã, để tui thở cái đã, vì {goi} vừa chơi một pha quá hay.",
        "Tui kể chuyện cười nè: {goi} thua. Hết chuyện cười, vì chuyện đó không có thật.",
        "Mấy đứa đối thủ chắc đang run lắm, vì có {goi} ở đây rồi!",
        "{Goi} nhớ nghỉ ngơi nha, nhưng trước đó cho tui xin thêm một ván nữa.",
        "Tui chấm {goi} mười điểm, thêm mười điểm nữa vì dễ thương luôn.",
        "Tui nghe nói {goi} sắp được mời đi thi quốc tế, tin này tui bịa nhưng tui tin.",
        "Cho tui xin một tràng pháo tay, à thôi, hai tràng, vì {goi} xứng đáng.",
        "Nhìn {goi} chơi, tui hiểu thế nào là nghệ thuật rồi, thiệt luôn.",
        "{Goi} ơi, tui mang bắp rang tới xem {goi} chơi nè, mời {goi} ăn nha.",
        "Quý vị thân mến, tui xin phép rớt nước mắt vì pha này quá đẹp.",
        "Tui mà có cái cúp là tui trao liền cho {goi}, không cần suy nghĩ.",
        "Tui không giỏi game đâu, nhưng tui giỏi cổ vũ {goi}, cứ tin tui.",
        "Bình tĩnh nha {goi}, tui còn bình tĩnh hơn {goi} nữa, vì tui đang ngồi xem mà.",
        "Chúc mừng {goi}, hôm nay tui lại có thêm lý do để kể chuyện cho cả xóm nghe.",
        "Tui sẽ ở đây đến cuối ván, cuối đêm, cuối tuần luôn, {goi} cứ chơi đi!",
        "Hết hồn, {goi} vừa chơi gì vậy, tui phải xem lại phát nữa mới tin.",
        "Dưới ánh đèn sân khấu, {goi} tỏa sáng như một ngôi sao thực thụ!",
        "Cả khán phòng đang nín thở chờ {goiLong}, mà {goi} vẫn cười tươi rói!",
        "Tui là MC mà bữa nay chỉ muốn làm khán giả của {goi} thôi.",
      ],
      named: [
        "Thưa quý vị, xin một tràng pháo tay cho {ten}, người chơi hay nhất đêm nay!",
        "{ten} ơi, tui ở đây cổ vũ {ten} nè, cứ yên tâm mà chơi!",
        "Ha ha, {ten} chơi hay quá, tui cười một mình luôn nè!",
        "Xin giới thiệu, nhân vật chính của chương trình, {ten}! Pháo tay đâu!",
        "{ten} thắng thì tui vui, {ten} thua thì tui vẫn vui, vì tui là fan mà!",
        "Bản tin nóng: {ten} vừa chơi hay đến mức server phải nghỉ phép.",
        "Tui xin tuyên bố, {ten} là niềm tự hào của cái server này!",
        "Ai chê {ten} là tui giận thiệt đó nha, nói trước rồi!",
        "{ten} ơi, đừng bỏ tui nha, tui còn muốn xem {ten} chơi thêm nhiều ván nữa.",
        "Tui nể {ten} thiệt sự, nể tới mức muốn viết thư cảm ơn luôn.",
        "Quý vị khán giả thấy chưa, {ten} đó, giỏi chưa!",
        "Tui xin làm hội trưởng fan club của {ten}, ai muốn vào thì đăng ký nha!",
        "{ten} chơi một pha là tui vui cả ngày, không xạo đâu.",
        "Tui chấm {ten} mười điểm, thêm mười điểm nữa vì dễ thương luôn.",
        "Chương trình xin tạm dừng một phút, để cả server vỗ tay cho {ten}.",
        "Nếu có giải Oscar cho game thủ, tui sẽ đi vận động cho {ten} liền.",
        "Cứu tui, {ten} chơi hay quá, tui phải ngồi xuống uống miếng nước đã.",
        "Tui mà có cái cúp là tui trao liền cho {ten}, không cần suy nghĩ.",
        "Đồng đội của {ten} chắc đang hạnh phúc lắm, tui đoán vậy đó.",
        "Và người chiến thắng của đêm nay, không ai khác, chính là {ten}!",
        "{ten} cứ chơi đi, tui lo phần vỗ tay, phần này tui làm giỏi lắm!",
      ],
    },
  },
  en: { girl: { base: [], named: [] } },
};
