export default {
  vi: { girl: { base: [], crush: [], named: [] }, boy: { base: [], named: [] } },
  en: {
    girl: {
      base: [
        "Breaking news: a new world record for being awesome, and you just broke it twice.",
        "Scientists confirm your aim is not natural. They are asking for a sample.",
        "Bulletin: the lobby has declared today a national holiday in your honor.",
        "Experts are baffled. You just did the impossible and looked bored doing it.",
        "Guinness called. They are running out of categories for you.",
        "Local gamer ruins everyone's day by being too good. More at eleven.",
        "Weather update: a storm of headshots is moving in, and it is you.",
        "Reporter on the scene says the enemy team is still processing what happened.",
        "Police report: someone stole the show and it was you, no charges, only applause.",
        "Fun fact: your reaction time makes lightning look like it is buffering.",
        "You play like the tutorial was written about you.",
        "That was so smooth the game forgot to lag.",
        "Your mouse hand should be insured. Seriously, call a broker.",
        "If skill were a currency, you would be buying the whole server.",
        "You are the final boss and the enemy team did not get the memo.",
        "Somewhere a pro player just felt a cold chill and does not know why.",
        "The game devs are watching this and quietly adding a nerf for you.",
        "Rank says one thing, but your gameplay says it is lying.",
        "That play belongs in a museum, next to the paintings and the dinosaurs.",
        "You make hard things look like a warm-up round.",
        "My jaw is on the floor and the floor is applauding.",
        "Even the loading screen is rooting for you now.",
        "Bigger than a mountain, faster than a rumor, that is your gameplay.",
        "You just played at a level the leaderboard has no number for.",
        "Alert: the skill meter has exploded, please evacuate calmly.",
        "A tiny audience of bots is crying happy tears in the corner.",
        "Your calm under pressure is scarier than any boss fight.",
        "That clutch will be told to the grandchildren of this server.",
        "Hold on, I need a moment, that was too good to process.",
        "Rumor has it your keyboard purrs every time you touch it.",
        "The enemy team has formed a support group and your name is the topic.",
        "Fresh from the lab: scientists measured your skill and broke the ruler.",
        "You are the reason the other team has trust issues with corners.",
        "Newsflash: the underdog is you, and the underdog is winning loudly.",
        "That was not a play, that was a documentary.",
        "Is it a bird, is it a plane? No, just you carrying the entire lobby.",
        "Respect level just hit a number my calculator cannot display.",
        "The prophecy said a hero would come. It did not mention the great aim.",
        "Your hands move like they have a secret contract with the game.",
        "If good plays were pizza, you would have sold out the whole city.",
        "Special report: gravity gave up trying to stop your comeback.",
        "Zero panic, full style, that is the official motto of you.",
        "Honestly, the speed of that decision should be studied in schools.",
        "People will say this was luck. People are wrong and I have receipts.",
        "The crowd is so loud the neighbors are asking what is going on.",
        "That was the kind of play that makes chat forget how to type.",
        "You are not just good, you are good with background music.",
        "You turned a bad situation into a victory lap. Who does that?",
        "Hot take: you are the most reliable thing in this entire game.",
        "A moment of silence for everyone you just outplayed, and now applause.",
        "Breaking: local legend refuses to miss a single shot today.",
        "Your game sense is so sharp it could open a letter.",
        "The team chat just went quiet from pure respect.",
        "Studies show watching you play improves mood a lot, no side effects.",
        "You have the focus of a cat watching a laser pointer, but with better results.",
        "That comeback had more twists than a soap opera finale.",
        "I would like to formally request an encore of that last move.",
        "Weather forecast: sunny with a ninety percent chance of you winning.",
        "Even the enemy team stopped to watch that one, no joke.",
        "You are a walking highlight reel and the cameras are lucky to be here.",
        "Please sign my screen, I am keeping this moment forever.",
        "The scoreboard is blushing and so am I.",
        "That reaction speed belongs in the history books, volume one.",
        "Plot twist: the one they underestimated is writing the whole story.",
        "Today's forecast calls for flawless plays with scattered applause.",
        "Honestly, the game should pay you for how good it looks right now.",
        "You make teamwork look like a solo performance with extra steps.",
        "That was so clean I wanted to check for fingerprints.",
        "Alert to all units: the legend is warmed up and ready.",
        "I would trade my whole snack stash to see that again.",
        "The tension was huge and you handled it like a casual stroll.",
        "Pretty sure the game just whispered, wow, to itself.",
        "Old gamers will tell tales of this match around campfires.",
        "Your timing is so perfect the clock asked for lessons.",
        "Somebody check the servers, they are overheating from your skill.",
        "A hundred percent hype, zero percent doubt, that is how I feel right now.",
        "You make every second of this stream worth the popcorn.",
        "Rare footage of someone who actually reads the map and wins.",
        "That play gave me goosebumps and I do not even have skin.",
        "The trophy room is getting a new wing just for this match.",
        "Scouts from far away lands are definitely taking notes on you.",
        "Your skill tree has branches the game never planned for.",
        "Do not tell the others, but you are my favorite part of the whole server.",
        "That was a cinematic. Somebody cue the orchestra, please.",
        "The way you stay calm is basically a superpower and I am taking notes.",
        "If you lose I will cry, but if you win I will cry louder, so win please.",
        "Tiny request: keep being this great, it is great for my health.",
        "You make my heart do the victory dance, and it has two left feet.",
        "I would carry your bags to the finals, that is how proud I am.",
        "Whoever taught you to play like that deserves a medal and a hug.",
        "You are the plot armor everyone else is jealous of.",
        "Quick bulletin: your fans are many, loud, and slightly emotional.",
        "The lobby is a nicer place with you in it, and a harder place too.",
        "Whatever happens next, that last round was a classic.",
        "You are proof that practice, talent and snacks make a champion.",
        "Short on words, long on respect, that is my whole review.",
        "Today is a good day to be your fan, and every day, really.",
        "Newsflash: your biggest fan is still screaming, send help and snacks.",
        "That was a plot twist even the writers did not see coming.",
        "Every time you do that, a tiny firework goes off in my head.",
        "Historians will mark this match as the moment everything changed.",
        "You could win with a potato controller and I would still cheer.",
        "Legends are made in rounds like this one, and you are mid-legend.",
        "Alert: charm levels critical, tactics levels critical, humility levels fine.",
        "Not a single wasted move, my heart cannot take this much elegance.",
        "The only thing faster than your reflexes is my fan mail count.",
        "Honest report from the front row: absolutely top tier, would watch again.",
        "You carry hope in one hand and a perfect crosshair in the other.",
        "Breaking: the word impossible has filed a complaint against you.",
        "Official ruling: that was the best thing I have seen all week."
      ],
      named: [
        "Breaking news: {ten} just set a world record and did not even blink.",
        "Scientists confirm {ten} is operating at a level the charts do not cover.",
        "Bulletin: {ten} has been declared a national treasure by this lobby.",
        "Guinness is on the phone for {ten}, and they sound nervous.",
        "Experts say {ten} is the reason the other team has trust issues.",
        "{ten} walked in, broke three records, and asked what is for lunch.",
        "Local legend {ten} is on a roll and the whole server is taking pictures.",
        "If skill were a language, {ten} would be writing the dictionary.",
        "Weather report: heavy clutch showers all day thanks to {ten}.",
        "Somewhere a pro just felt a chill and it is all because of {ten}.",
        "Fun fact: {ten} has more highlights than most games have levels.",
        "Special report: {ten} refuses to lose and the scoreboard agrees.",
        "{ten} versus the whole lobby, and the lobby is losing politely.",
        "Hold the presses, {ten} just pulled off a move that needs its own movie.",
        "Your biggest fan here says {ten} is the main event and the encore."
      ]
    }
  }
};
