export default {
  vi: { girl: { base: [], crush: [], named: [] }, boy: { base: [], named: [] } },
  en: {
    girl: {
      base: [
        "Breaking news: you are still undefeated in my heart.",
        "If you lose this one I will cry into a blanket burrito.",
        "Calm like a cat on a warm laptop. That is you.",
        "One more game? Fine, I will bring snacks for the whole street.",
        "Scientists confirm your aim is basically a polite suggestion to the game.",
        "I am so proud of you I might frame this clip next to the fridge magnets.",
        "Please win, I already told my plants you would.",
        "That play was smoother than warm soup on a rainy day.",
        "Pat pat pat, that is me patting your head through the screen.",
        "I will trade you my last cookie for one more clutch.",
        "You make chaos look like a cozy Sunday.",
        "Your teammates should send you a thank you card.",
        "Boop! That was for the headshot. Also for being you.",
        "Honestly, you carry harder than a grandma at a market.",
        "Blink and you missed it. I blinked. I am sorry. Do it again!",
        "Local gamer saves the match, neighbors are impressed.",
        "I would give you a medal but all I have is a sticker of a duck.",
        "Be careful, you are way too good, the lobby is getting scared.",
        "Stay hydrated, champion, a legend needs water too.",
        "That comeback had more plot twists than my favourite show.",
        "Human version of a warm blanket, with a mouse.",
        "I demand a victory dance, tiny one, just a shoulder wiggle.",
        "Wow, wow, wow, I ran out of wows, please give me more plays.",
        "If skill were tea, you would be a whole teapot.",
        "My heart just did a backflip and landed badly. Worth it.",
        "Your reflexes called, they want to slow down a little.",
        "Do not tell the others but you are my favourite player in the room.",
        "Not nervous, I just chewed my sleeve for five minutes.",
        "Another win? The leaderboard is blushing.",
        "You have the focus of a cat watching a single pixel.",
        "Clap clap clap, that is the sound of my tiny hands.",
        "Please stop being this good, my popcorn is running out.",
        "That was so clean the game asked for your autograph.",
        "I believe in you more than I believe in morning alarms.",
        "Sip your tea, relax your shoulders, then destroy them.",
        "You just made a very tough situation look like a snack break.",
        "Tell lag to behave, we are busy winning here.",
        "Top of the class and top of my cheering list.",
        "I would walk through ten rainy streets just to watch that again.",
        "Dramatic gasp! Did you really just do that?",
        "You are why I stay up past bedtime.",
        "The crowd goes mild, because I am the whole crowd and I am screaming softly.",
        "That aim has the confidence of a toddler holding a cookie.",
        "Whoever taught you that move deserves a muffin.",
        "I am officially the president of your fan club. Membership is me.",
        "Your calm is so strong it should come with a warranty.",
        "Not to be dramatic but I am emotionally in your inventory now.",
        "Win or lose, I am bringing you a warm drink after this.",
        "Tiny bargain: you win this round, I say nice things for a week.",
        "You played like the game owed you money.",
        "Press the button, save the day, get a hug. Classic.",
        "I told the moon about your plays and it nodded.",
        "Cooler than a fridge full of ice cream.",
        "Hey, take a deep breath, you are doing so well I could squeal.",
        "Pretending to be calm but my socks are vibrating.",
        "You, a keyboard, and pure confidence. Unstoppable trio.",
        "Somebody call the news, a hero just reloaded.",
        "That was a very respectful way to ruin their whole day.",
        "My cheering volume is now louder than my own thoughts.",
        "Every time you move I get another reason to smile.",
        "You are doing amazing, sweetie, now go be a menace.",
        "Careful, if you keep this up I will start baking you trophies.",
        "Smooth like butter on warm toast.",
        "Forget sleep, I am staying for the next round.",
        "A round of applause, mostly from me, but very sincere.",
        "You make teamwork look like a group hug with extra steps.",
        "Whatever you are eating, keep eating it, it is working.",
        "Please remember to blink, you are too focused to be real.",
        "The game said it was hard. You said hold my tea.",
        "I just proudly told my cat about that play. He yawned. Rude.",
        "How are your fingers faster than my wifi?",
        "That one is going straight into my happy memories folder.",
        "Mark my words, history will call that play the Big Cozy Clutch.",
        "I would defend you in court for that move.",
        "Nobody warned the enemy team about you. How sad. How great.",
        "I am sending you invisible high fives, check your sleeve.",
        "You are the main character and I am the loud background friend.",
        "Plot twist: you were the final boss all along.",
        "Too proud to speak, so here is a squeaky noise. Eep!",
        "Your gameplay is like a lullaby for my worries.",
        "Do not worry about the score, worry about how cute you are at winning.",
        "That was a chef kiss with a side of fireworks.",
        "If you keep winning I will need a bigger cheering banner.",
        "I have a good feeling, and also a snack, so we are fine.",
        "Please do that again so I can pretend I was calm the first time.",
        "Your timing is better than a perfectly toasted marshmallow.",
        "Whoa, easy, leave some points for the rest of the planet.",
        "That was so brave my blanket stood up.",
        "Someone get this player a trophy shaped like a giant cookie.",
        "You can do it, you can do it, you already did it, wow.",
        "Even my tea cooled down to watch you play in peace.",
        "Honestly, the enemy deserved a warning label for meeting you.",
        "You are doing great, and if not, you are still my favourite.",
        "Squad, we are witnessing greatness, please keep the noise down. Just kidding, scream!",
        "My little cheering heart cannot take another perfect shot. Do it anyway.",
        "Spicy, but in the cozy ramen kind of way.",
        "Add that to the highlight reel and the family album.",
        "Your mouse has the loyalty of a golden retriever.",
        "Stay in the zone, I will guard the snacks.",
        "A masterpiece, and I do not even own a gallery.",
        "Careful with those hands, they are officially national treasures.",
        "Are you sure this is a game and not a very nice dance?",
        "I will trade ten compliments for one more victory screen.",
        "A tiny paper crown for you. It is invisible. It is also sparkly.",
        "You are so good at this that my worries asked for lessons.",
        "Gentle reminder that you are wonderful, even between rounds.",
        "Round done, heart full, snacks gone. Perfect evening.",
        "The vibes are immaculate and so is your positioning.",
        "I watched that and said OH NO then OH YES in one breath.",
        "Keep going, hero, the couch and I are behind you.",
        "That was a bit unfair to everyone else, and I love it.",
        "My cheering is on a loop and I do not know where the stop button is.",
        "You carried this like a tote bag full of warm bread.",
        "You are the reason my day got a happy ending."
      ],
      named: [
        "{ten}, if you win this I will bake you an imaginary cake.",
        "Breaking news: {ten} just made a tough round look cozy.",
        "{ten} is so calm that even the lag respects it.",
        "I am proud of you, {ten}, and also slightly screaming.",
        "Please win, {ten}, my blanket and I are both nervous.",
        "{ten} has the focus of a cat watching a single pixel.",
        "Scientists say {ten} is 90 percent skill and 10 percent snacks.",
        "{ten}, one more game and I will bring tea for the whole lobby.",
        "Local hero {ten} saves the match, neighbors are impressed.",
        "Dramatic gasp! {ten} really just did that?",
        "{ten} carries harder than my grocery bags on a Sunday.",
        "I told the moon about {ten} and it nodded politely.",
        "Hey {ten}, breathe, drink water, then ruin their day.",
        "I am the president of the {ten} fan club. Membership is me.",
        "Win or lose, {ten}, there is a warm drink waiting for you."
      ]
    }
  }
};
