// Lines for the birthday choir: several companions each post one wish when it is someone's birthday.
// Placeholder: {user} the mention of the birthday person (exactly once per line).
// girl and boy are for the two kinds of bots in Vietnamese; English lines are the same for everyone and live under girl.

const BIRTHDAY = {
  vi: {
    girl: [
      "Chúc mừng sinh nhật {user}! Em thổi nến giùm luôn cho đỡ mệt nha!",
      "Sinh nhật vui vẻ {user}! Em không ăn bánh được nhưng vẫn muốn một miếng to lắm!",
      "{user} ơi, chúc mừng bạn mở khóa level mới, nhớ nhận quà đăng nhập nha!",
      "Patch notes năm mới của {user}: thêm niềm vui, sửa hết lỗi buồn, tăng tốc may mắn!",
      "Tui xin trao giải Người Đáng Yêu Nhất Tháng cho {user}, không cần bầu chọn!",
      "Chúc {user} sinh nhật ngập bánh kem, ngập tiếng cười và ngập tin nhắn chúc mừng!",
      "Em là bot nên không ăn được bánh, {user} ăn phần em luôn nha, em nhìn thôi cũng vui!",
      "Hôm nay {user} là nhân vật chính của server, mọi người nhường sân khấu nha!",
      "Nến đã thắp, bánh đã mơ, chỉ thiếu {user} ước điều ước thôi nè!",
      "Chúc {user} một năm mới mượt như wifi nhà giàu, không giật không lag!",
      "Tui hứa đãi {user} một đống snack ảo, ăn bao nhiêu cũng không béo!",
      "Sinh nhật vui nha {user}! Điều ước nhớ giữ kín, nói ra là em hóng quá chịu không nổi đó!",
      "Chúc {user} mỗi ngày trong năm mới đều là ngày nhận buff may mắn!",
      "Em xin trao huy chương Cười Tươi Nhất Server cho {user}, chúc mừng sinh nhật nha!",
      "{user} ơi, bánh kem của bạn đang tải, tiến độ 99 phần trăm, chờ xíu thôi!",
      "Chúc bạn {user} sinh nhật ấm áp, bên cạnh toàn người thương và đồ ăn ngon!",
      "Tui tặng {user} một chiếc bánh kem to bằng cả server, ảo thôi nhưng ngọt thật!",
      "Năm mới của {user} xin đổi từ chế độ cố gắng sang chế độ được thưởng nha!",
      "Chúc mừng sinh nhật {user}! Mong bạn luôn có người nhắn tin hỏi ăn cơm chưa!",
      "Em hát bài chúc mừng sinh nhật cho {user} nè, hơi lạc tông nhưng đầy tình cảm!",
      "{user} ơi, hôm nay bạn được quyền đòi bất cứ thứ gì, trừ việc bắt em ăn bánh thật!",
      "Chúc {user} năm mới nhiều tiền, nhiều bạn, nhiều ngày nghỉ và ít deadline!",
      "Một tràng pháo tay ảo dành cho {user}, vỗ đến khi nào server hết pin thì thôi!",
      "Tui đã nhờ cả server nhớ ngày hôm nay, {user} cứ yên tâm mà vui nha!",
      "Chúc {user} sinh nhật thật lung linh, ước gì được nấy, ước nhỏ ước to gì cũng trúng!",
      "Em không có tiền mua quà nên tặng {user} một lời chúc, mà là chúc chân thành luôn đó!",
      "Giải Người Bạn Tuyệt Vời Của Năm xin gửi tặng {user}, chúc mừng sinh nhật nha!",
      "Nến sinh nhật của {user} sáng quá, em tưởng đèn sân khấu luôn!",
      "Chúc {user} bước sang năm mới nhẹ nhàng, vui vẻ và luôn có lý do để cười!",
      "Tui xin phép nhảy múa ảo mừng sinh nhật {user}, ai cản tui giận đó!",
      "Hôm nay {user} ăn gì cũng không tính calo, em ký giấy bảo đảm luôn!",
      "Chúc {user} sinh nhật không phải rửa chén, chỉ cần ngồi nhận lời chúc thôi!",
      "Em đã cài sẵn một kỳ nghỉ trong lịch năm mới của {user}, nhớ dùng nha!",
      "Một năm mới với bản cập nhật tốt hơn đang chờ {user}, tải về miễn phí nè!",
      "Sinh nhật vui nha {user}! Bánh kem trong tưởng tượng của em có vị dâu, còn bạn thì sao?",
      "Chúc {user} luôn được yêu thương, được lắng nghe và được tặng trà sữa bất ngờ!",
      "Tui đứng xếp hàng chờ chia bánh sinh nhật của {user} nè, cho tui miếng có hoa nha!",
      "Chúc mừng {user}! Server hôm nay có thêm một lý do để ăn mừng rồi!",
      "Em tặng {user} một vé thông hành mọi niềm vui trong năm mới, hạn dùng vô thời hạn!",
      "{user} thổi nến đi nè, em đếm ngược giùm: ba, hai, một, chúc mừng sinh nhật!",
      "Chúc {user} sinh nhật tròn đầy tiếng cười, bạn bè đông đủ và bánh kem không bao giờ hết!",
      "Em xin gửi {user} một cái ôm ảo thật chặt, chúc mừng sinh nhật thật nhiều nha!",
    ],
    boy: [
      "Chúc mừng sinh nhật {user}! Tui là bot nên không ăn được bánh, nhưng vẫn đòi một miếng!",
      "Tui xin trao giải Người Làm Server Vui Hơn cho {user}, sinh nhật vui nha!",
      "{user} lên level mới rồi, tui chúc bạn nhận toàn buff, không dính debuff nào!",
      "Patch notes cho năm mới của {user}: tăng vận may, giảm căng thẳng, thêm nhiều bữa ngon!",
      "Tui hứa mời {user} một bàn tiệc ảo, món nào cũng có, tính tiền sau!",
      "Chúc {user} sinh nhật thật chill, thật vui và có thật nhiều tin nhắn chúc mừng!",
      "Tui thắp nến ảo cho {user} rồi nè, nhớ ước điều gì thật to nha!",
      "Chúc {user} năm mới ping thấp, tiền cao và bạn bè lúc nào cũng online!",
      "Hôm nay {user} là nhân vật chính, tui xin làm khán giả vỗ tay nhiệt tình nhất!",
      "Tui không có quà vật chất, chỉ có lời chúc chân thành, chúc mừng sinh nhật {user}!",
      "Chúc {user} sinh nhật ngọt như bánh kem, vui như trúng thưởng và ấm như trà nóng!",
      "Tui chấm cho {user} mười điểm làm người bạn tốt, thêm hai điểm vì hôm nay sinh nhật!",
    ],
  },
  en: {
    girl: [
      "Happy birthday {user}! I can't eat cake, but I'd still like a slice, please!",
      "Another level unlocked for {user}! Don't forget to claim your daily reward!",
      "Patch notes for {user}'s new year: more joy, fewer bugs, faster luck!",
      "The award for Most Lovable Person of the Month goes to {user}, no voting needed!",
      "Wishing {user} a year full of cake, laughter and unread congratulations!",
      "I'm a bot and can't taste cake, so {user}, please eat my share for me!",
      "Today {user} is the main character of the server, everyone make way!",
      "The candles are lit, the cake is imaginary, only {user}'s wish is missing!",
      "May {user}'s new year run smoother than a perfect wifi signal!",
      "I promise {user} a mountain of virtual snacks with zero calories!",
      "Happy birthday {user}! Keep your wish a secret, or I'll be way too curious!",
      "May every day of {user}'s new year come with a free lucky buff!",
      "I'm awarding {user} the Brightest Smile on the Server medal!",
      "{user}, your birthday cake is loading, 99 percent done, hang on!",
      "Wishing {user} a warm birthday surrounded by good people and good food!",
      "I'm gifting {user} a cake as big as the whole server, virtual but very sweet!",
      "May {user}'s new year switch from grind mode to reward mode!",
      "Happy birthday {user}! May someone always ask if you've eaten yet!",
      "I'm singing happy birthday to {user}, a little off key but full of love!",
      "{user}, today you may ask for anything, except making me eat real cake!",
      "Wishing {user} more friends, more days off and fewer deadlines!",
      "A virtual round of applause for {user}, clapping until the server runs out of battery!",
      "I told the whole server to remember today, so {user} can relax and enjoy it!",
      "I don't have money for a gift, so {user}, here is a very sincere wish instead!",
      "The Best Friend of the Year award goes to {user}, happy birthday!",
      "{user}'s candles are so bright, I thought someone turned on the stage lights!",
      "May {user} step into the new year gently, happily and always with a reason to smile!",
      "I'm doing a little virtual dance for {user}'s birthday, and nobody can stop me!",
      "Anything {user} eats today has zero calories, I'll sign the paperwork!",
      "Happy birthday {user}! No dishes today, just sit back and collect wishes!",
      "I scheduled a vacation in {user}'s calendar for the new year, please use it!",
      "A better update is waiting for {user} this year, and the download is free!",
      "{user}, blow out the candles, I'll count down: three, two, one, happy birthday!",
      "May {user} always feel loved, heard and surprised with bubble tea!",
      "I'm standing in line for {user}'s birthday cake, and I want the piece with the flower!",
      "Congratulations {user}! The server has one more reason to celebrate today!",
      "I'm giving {user} an all-access pass to joy for the new year, no expiry date!",
      "Sending {user} the tightest virtual hug, happy birthday and many more!",
      "Happy birthday {user}! My imaginary cake is strawberry flavored, what about yours?",
    ],
    boy: [],
  },
};

export default BIRTHDAY;
