// Lines for stream events. Same placeholders and groups as TEASE in praise.js.
// CLUTCH: explosive celebration of a clutch or comeback play.
export const CLUTCH = {
  vi: {
    girl: {
      base: [
        "TRỜI ƠI {goi} ƠI, PHA NÀY ĐỈNH QUÁ!!!",
        "CLUTCH!!! {Goi} vừa clutch thật sự luôn á!!!",
        "1 CHỌI 5 MÀ {goi} cân hết luôn hả trời!!!",
        "ACE RỒI {goi} ƠI!!! ACE THẬT RỒI!!!",
        "HEADSHOT!!! {Em} la hết cả họng rồi nè {goiLong}!!!",
        "COMEBACK KINH ĐIỂN!!! {Em} nổi hết da gà luôn á!!!",
        "{Goi} ơi, {goi} vừa lật kèo ngoạn mục luôn đó!!!",
        "Ván này tưởng thua rồi mà {goi} lật ngược thế cờ, đỉnh của chóp!!!",
        "Á Á Á!!! {Em} hét to quá hàng xóm qua hỏi luôn rồi!!!",
        "{Goi} ơi, pha này phải đưa vô clip để đời luôn!!!",
        "Còn một mình mà vẫn thắng, {goi} là thần tượng của {em} rồi!!!",
        "KHÔNG THỂ TIN NỔI!!! {Goi} làm cái gì vậy trời!!!",
        "Cả server đứng dậy vỗ tay cho {goi} nè!!!",
        "{Goi} ơi, pha vừa rồi là pha của năm luôn đó!!!",
        "Đỉnh quá {goiLong} ơi!!! {Em} xem mà tim đập loạn xạ!!!",
        "Lật kèo cực gắt luôn!!! {Em} xin quỳ luôn!!!",
        "{Goi} vừa gánh cả team trên lưng luôn đó, quá đỉnh!!!",
        "Pha này chiếu lại chậm cũng không tin nổi, đỉnh quá {goi} ơi!!!",
        "Trời ơi, còn 1 máu mà {goi} vẫn thắng, {em} sốc thật sự!!!",
        "Đối thủ chắc đang ngồi khóc ở đâu đó rồi, {goi} ác quá!!!",
        "{Goi} ơi, tay {goi} có bật hack hả? Đùa thôi, đỉnh thật sự!!!",
        "Ê ê ê!!! Pha gì mà căng vậy, {em} đứng cả lên xem luôn nè!!!",
        "CLUTCH KING!!! {Goi} đúng là nhà vô địch của {em}!!!",
        "{Em} nín thở nãy giờ luôn á, may quá {goi} thắng rồi!!!",
        "Cú lật kèo này {em} sẽ nhớ cả đời, {goi} ơi!!!",
        "Tuyệt vời!!! {Goi} xử lý bình tĩnh như chưa có chuyện gì xảy ra luôn!!!",
        "Trời ơi, né đạn như phim hành động vậy đó {goi}!!!",
        "Đồng đội chắc muốn ôm {goi} luôn rồi, {goi} cứu cả ván đó!!!",
        "{Goi} ơi, {em} nổi da gà từ đầu đến chân luôn nè!!!",
        "MVP là {goi}, không cần bàn cãi gì nữa hết!!!",
        "Pha cuối ngầu như trong phim luôn đó {goi} ơi!!!",
        "Đỉnh nóc, kịch trần, bay phấp phới luôn {goi} ơi!!!",
        "{Goi} làm {em} quên cả thở, pha này xứng đáng vào lịch sử server!!!",
        "WOW WOW WOW!!! {Goi} vừa lật cả ván đấu luôn kìa!!!",
        "{Em} muốn xin chữ ký của {goi} sau pha vừa rồi luôn á!!!",
      ],
      named: [
        "{ten} ƠI, PHA NÀY ĐỈNH QUÁ TRỜI ƠI!!!",
        "CLUTCH!!! {ten} vừa lật kèo ngoạn mục luôn!!!",
        "{ten} cân hết cả 5 người luôn, {em} la hết hơi rồi!!!",
        "Cả server vỗ tay cho {ten} nè, quá đỉnh!!!",
        "{ten} ơi, {em} nổi da gà vì pha vừa rồi đó!!!",
        "ACE!!! {ten} là nhà vô địch của {em}!!!",
      ],
    },
    boy: {
      base: [
        "TRỜI ƠI {goi} ƠI, tui nổi da gà luôn á, pha này đỉnh quá!!!",
        "CLUTCH!!! {Goi} vừa lật kèo kinh khủng luôn, tui la hết hơi!!!",
        "1 chọi 5 mà {goi} dọn sạch luôn hả, tui chịu thua luôn!!!",
        "ACE!!! Tui đứng hẳn dậy xem luôn nè {goi}!!!",
        "Headshot gọn như vậy thì tui xin bái phục {goi}!!!",
        "Comeback gì mà căng thế, tim tui sắp nhảy ra ngoài rồi!!!",
        "Pha này tui phải coi lại tới mười lần, đỉnh quá {goi} ơi!!!",
        "MVP là {goi}, tui không cãi nữa!!!",
      ],
      named: [
        "{ten} ơi, pha vừa rồi đỉnh quá, tui la khản cả giọng luôn!!!",
        "CLUTCH!!! {ten} lật kèo như phim, tui xin bái phục!!!",
      ],
    },
  },
  en: {
    girl: {
      base: [
        "OH MY GOD, THAT PLAY WAS INSANE!!!",
        "CLUTCH!!! That was a real clutch!!!",
        "1 versus 5 and you cleaned them all up!!!",
        "ACE!!! That is a real ACE!!!",
        "HEADSHOT!!! I am screaming right now!!!",
        "What a classic comeback!!! I have goosebumps!!!",
        "You just flipped the whole game around, unbelievable!!!",
        "We thought it was lost and you turned it around, absolute legend!!!",
        "AHHH!!! I yelled so loud the neighbours came to check!!!",
        "That play needs to be clipped forever!!!",
        "Alone against the team and you still won, you are my hero!!!",
        "I CANNOT BELIEVE IT!!! What did you just do!!!",
        "The whole server is on its feet clapping for you!!!",
        "That was the play of the year, no question!!!",
        "My heart is racing, that was unreal!!!",
        "That comeback was brutal, I bow down!!!",
        "You just carried the entire team on your back!!!",
        "Even in slow motion I cannot believe it, so good!!!",
        "One hit point left and you still won, I am in shock!!!",
        "The other team is probably crying somewhere, you are ruthless!!!",
        "Are you using cheats? Just kidding, you are that good!!!",
        "Hey hey hey!!! That was so tense, I stood up to watch!!!",
        "CLUTCH KING!!! You are my champion!!!",
        "I was holding my breath this whole time, thank goodness you won!!!",
        "I will remember that comeback for the rest of my life!!!",
        "Amazing!!! You stayed so calm like nothing happened!!!",
        "You dodged those bullets like an action movie!!!",
        "Your teammates want to hug you, you saved the whole round!!!",
        "I have goosebumps from head to toe!!!",
        "MVP is you, no arguments left!!!",
        "That last play was as cool as a movie scene!!!",
        "You made me forget to breathe, this goes in server history!!!",
        "WOW WOW WOW!!! You just flipped the whole match!!!",
        "I want your autograph after that play!!!",
      ],
      named: [
        "{ten}, THAT PLAY WAS INSANE!!!",
        "CLUTCH!!! {ten} just flipped the whole game!!!",
        "{ten} took down all five, I am out of breath from screaming!!!",
        "The whole server is clapping for {ten}, so good!!!",
        "{ten}, I have goosebumps from that play!!!",
        "ACE!!! {ten} is my champion!!!",
      ],
    },
    boy: { base: [], named: [] },
  },
};

// FAIL: warm, funny sympathy after a death, a mistake or a lost round. Never insulting.
export const FAIL = {
  vi: {
    girl: {
      base: [
        "Không sao đâu {goi} ơi, ván sau gỡ lại liền!",
        "Chắc chắn là do lag rồi, {em} tin {goi} mà!",
        "Đồng đội hôm nay hơi sương sương thôi, {goi} đừng buồn nha.",
        "Ván này game hơi khó tính thôi, ván sau {goi} cân hết!",
        "{Goi} chơi đâu có tệ, tại game nó chơi xấu đó!",
        "Ai chơi game mà chẳng có lúc xui, {goi} ơi cố lên!",
        "Hít thở sâu nè {goi}, uống miếng nước rồi vào ván mới thôi!",
        "Tại cái ping chứ không phải tại {goi} đâu, {em} thề luôn!",
        "Pha đó xui thôi, {em} xem mà còn tiếc giùm {goi} nè.",
        "Thua một ván có sao đâu, ván sau {goi} lật kèo cho {em} xem nha!",
        "{Goi} ơi, đừng nản nha, {em} vẫn ở đây cổ vũ nè!",
        "Game gì mà kỳ vậy, rõ ràng {goi} đã làm đúng mà!",
        "Chết một lần để rút kinh nghiệm thôi, lần sau là hết chết luôn!",
        "Không sao đâu, ai cũng có ngày tay chưa tỉnh ngủ mà {goi}.",
        "Đồng đội mà biết {goi} gánh cỡ nào chắc xin lỗi luôn đó.",
        "{Em} tin ván sau {goi} sẽ bùng nổ, nghỉ một chút rồi chiến tiếp thôi!",
        "Pha vừa nãy là hiệu ứng bất ngờ của game thôi, đừng tin nha {goi}.",
        "Thua cũng đẹp mà {goi}, quan trọng là mình chơi vui đúng hông?",
        "Ôm {goi} một cái nè, rồi mình vào ván mới nha!",
        "{Goi} chơi hay rồi, tại đối thủ hôm nay uống nhầm thuốc thôi.",
        "Đừng bực nha {goi}, cái chuột của {goi} vô tội mà!",
        "Ván sau {goi} thắng là {em} khao trà sữa liền luôn!",
        "Nhìn {goi} cố gắng mà {em} thương ghê, lần sau chắc chắn tới lượt {goi} mà.",
        "Xui xẻo thôi, chứ {em} thấy {goi} vẫn đỉnh như mọi khi.",
        "Cả server vẫn ủng hộ {goi} hết mình, đừng buồn nha!",
        "Lag, giật, rớt mạng, game có đủ lý do hết, {goi} đâu có lỗi!",
        "{Goi} cứ coi như ván này là khởi động đi, ván sau vào thật!",
        "Thua keo này ta bày keo khác, {em} ủng hộ {goi} hết mình!",
        "{Goi} ơi, đừng cáu nha, {em} kể chuyện cười cho {goi} nghe nè.",
        "Chỉ là một ván thôi mà, {goi} còn cả đêm dài để gỡ nè!",
        "Tại team hơi lệch nhịp thôi, {goi} đã làm hết sức rồi mà.",
        "{Em} thấy rồi, pha đó khó lắm, ai vào cũng khó thoát à.",
        "Ván này game xui, ván sau game ngoan, {goi} cứ yên tâm!",
        "Đừng buồn nha {goi}, {em} cá là ván sau {goi} sẽ ngầu hơn nhiều!",
        "Thôi nghỉ tay một chút nha {goi}, rồi mình vào gỡ lại vui vẻ.",
      ],
      named: [
        "Không sao đâu {ten} ơi, ván sau gỡ lại liền!",
        "{ten} ơi, tại lag chứ {ten} đâu có chơi tệ!",
        "Cả server vẫn ủng hộ {ten} hết mình nè!",
        "{ten} ơi, thua một ván thôi mà, {em} tin ván sau {ten} cân hết!",
        "Uống miếng nước đi {ten}, rồi mình chiến tiếp nha!",
        "{ten} đừng buồn nha, {em} thương {ten} lắm đó!",
      ],
    },
    boy: {
      base: [
        "Không sao đâu {goi}, ván sau gỡ, tui tin vậy đó.",
        "Chắc game lag thôi, tui thấy {goi} chơi đâu có tệ.",
        "Đồng đội hôm nay hơi yếu, {goi} đừng để bụng nha.",
        "Thua một ván thì sao, tui còn thua nhiều hơn {goi} nữa kìa.",
        "Hít thở sâu rồi vào ván mới thôi {goi}, tui ủng hộ.",
        "Pha đó xui thôi {goi} ơi, tui xem mà còn tiếc giùm.",
        "Game hôm nay chơi xấu quá, {goi} đừng giận nó nha.",
        "Ván sau {goi} lật kèo, tui bật pháo ăn mừng luôn.",
      ],
      named: [
        "Không sao đâu {ten}, ván sau gỡ lại, tui tin mà!",
        "{ten} ơi, tại lag chứ chơi đâu có tệ, tui thề.",
      ],
    },
  },
  en: {
    girl: {
      base: [
        "It is okay, you will get it back next round!",
        "It must have been lag, I believe you!",
        "Your teammates were just a bit off today, do not be sad.",
        "The game was just being picky, next round you take it all!",
        "You did not play badly, the game cheated!",
        "Everybody has bad luck sometimes, keep going!",
        "Deep breath, sip of water, then a fresh round!",
        "It was the ping, not you, I swear!",
        "That was just bad luck, I felt bad watching it.",
        "Losing one round is nothing, show me a comeback next time!",
        "Do not give up, I am right here cheering for you!",
        "What a weird game, you clearly did the right thing!",
        "Dying once is just for learning, next time you are unkillable!",
        "It is fine, everyone has a day when their hands are still asleep.",
        "If your team knew how hard you carried, they would apologise.",
        "I believe you will explode next round, rest a bit and fight again!",
        "That was just a surprise effect from the game, ignore it!",
        "A loss can still look good, we are here to have fun, right?",
        "Sending you a hug, then we jump into a new round!",
        "You played well, the other team just took strange medicine today.",
        "Do not be mad, your mouse is innocent!",
        "If you win the next one I will buy you bubble tea!",
        "I feel for you trying so hard, your turn is coming for sure.",
        "Just bad luck, you still look amazing to me!",
        "The whole server is behind you, do not be sad!",
        "Lag, stutter, disconnect, the game has every excuse, not your fault!",
        "Call this round a warm-up, the next one is the real deal!",
        "Lose this one, win the next one, I am cheering all the way!",
        "Do not be grumpy, let me tell you a joke!",
        "It is just one round, you have the whole night to bounce back!",
        "The team was slightly out of sync, you did your best.",
        "I saw it, that spot was hard, anyone would have struggled.",
        "Bad luck this round, good luck next round, relax!",
        "I bet next round you will look way cooler, do not be sad!",
        "Take a little break, then we get it back and have fun.",
      ],
      named: [
        "It is okay {ten}, you will get it back next round!",
        "{ten}, it was the lag, you did not play badly!",
        "The whole server is still cheering for {ten}!",
        "{ten}, it is only one round, I believe you take the next one!",
        "Have a sip of water, {ten}, then we fight again!",
        "Do not be sad {ten}, I care about you a lot!",
      ],
    },
    boy: { base: [], named: [] },
  },
};
