// Extra Vietnamese fun facts, curated from a larger list: the arithmetic and unit-conversion filler was left out.
// Each entry is one sentence; content/vi.js adds a playful lead-in and an id.
export default [
  "Sao Kim quay ngược chiều so với phần lớn hành tinh.",
  "Hoàng hôn trên Sao Hỏa có thể trông xanh lam gần Mặt Trời.",
  "Sao Thổ có mật độ trung bình thấp hơn nước.",
  "Great Red Spot của Sao Mộc là một cơn bão khổng lồ tồn tại hàng thế kỷ.",
  "Gió trên Sao Hải Vương có thể vượt 2.000 km/h.",
  "Không gian giữa các thiên hà không hoàn toàn trống.",
  "Vật chất sao neutron cực kỳ đặc.",
  "Hố đen không hút mọi thứ như một máy hút bụi vũ trụ.",
  "Nếu Mặt Trời được thay bằng hố đen cùng khối lượng, quỹ đạo Trái Đất về cơ bản vẫn tương tự.",
  "Vũ trụ quan sát được rộng khoảng 93 tỷ năm ánh sáng.",
  "Nhìn xa trong vũ trụ cũng là nhìn về quá khứ.",
  "Âm thanh không truyền qua chân không như qua không khí.",
  "Carbon, oxygen và iron trong cơ thể chúng ta được tạo qua các thế hệ sao.",
  "Chưa quan sát thấy một 'mép vũ trụ'.",
  "Theo thuyết tương đối, tốc độ và hấp dẫn ảnh hưởng tốc độ trôi của thời gian.",
  "Não người chiếm khoảng 2% trọng lượng nhưng dùng khoảng 20% năng lượng lúc nghỉ.",
  "Mô não không có thụ thể đau giống da.",
  "Não người có khoảng 86 tỷ neuron.",
  "Não có thể thay đổi kết nối thần kinh suốt đời.",
  "Ký ức được tái cấu trúc khi nhớ lại.",
  "Não thường tự lấp điểm mù thị giác.",
  "Ánh sáng phải đi qua một số lớp võng mạc trước khi tới photoreceptor.",
  "Tim người trung bình đập khoảng 100.000 lần mỗi ngày.",
  "Tổng chiều dài mạch máu người trưởng thành thường được ước tính khoảng 100.000 km.",
  "Cơ thể không được thay mới hoàn toàn mỗi 7 năm như lời đồn.",
  "Lớp ngoài của da liên tục được thay mới.",
  "Xương là mô sống và liên tục tái cấu trúc.",
  "Gan có khả năng tái tạo đáng kể.",
  "Dạ dày thường có pH khoảng 1-3.",
  "Con người có thể sống mà không có túi mật.",
  "Con người có thể sống với một quả thận khỏe mạnh.",
  "Người trưởng thành thường có 206 xương.",
  "Xương đùi là xương dài nhất cơ thể.",
  "Phổi trái nhỏ hơn phổi phải để dành chỗ cho tim.",
  "Cơ thể người là nơi sống của một hệ sinh thái vi sinh vật khổng lồ.",
  "Bạch tuộc thay đổi màu và kết cấu da rất nhanh.",
  "Phần lớn neuron của bạch tuộc nằm ngoài não trung tâm.",
  "Cá heo có thể ngủ với một bán cầu não hoạt động hơn bán cầu kia.",
  "Một số cá mập cảm nhận được điện trường cực nhỏ.",
  "Cá voi xanh là động vật lớn nhất được biết từng tồn tại.",
  "Tim cá voi xanh có thể nặng hơn 100 kg.",
  "Chim ruồi có thể bay lùi.",
  "Một số chim nhìn được tia cực tím.",
  "Quạ có thể sử dụng công cụ.",
  "Một số voi nhận ra mình trong gương.",
  "Axolotl có thể tái tạo chân và nhiều mô phức tạp.",
  "Một số thằn lằn tự rụng đuôi để thoát kẻ săn mồi.",
  "Tardigrade có thể vào trạng thái gần như ngừng trao đổi chất.",
  "Một số kiến tạo cầu sống bằng cơ thể.",
  "Cá hề có thể thay đổi giới tính.",
  "Một số sứa Turritopsis có thể quay lại giai đoạn phát triển trẻ hơn.",
  "Internet và World Wide Web không phải cùng một thứ.",
  "Web là một dịch vụ chạy trên Internet.",
  "Email có trước World Wide Web.",
  "Website đầu tiên xuất hiện đầu thập niên 1990.",
  "DNS giúp ánh xạ tên miền sang địa chỉ máy tính dùng để định tuyến.",
  "Mật khẩu dài và ngẫu nhiên thường mạnh hơn mật khẩu ngắn chỉ có vẻ phức tạp.",
  "MFA có thể chặn nhiều vụ chiếm tài khoản ngay cả khi mật khẩu lộ.",
  "HTTPS mã hóa đường truyền nhưng không đảm bảo website đáng tin.",
  "Incognito không khiến bạn vô hình trên Internet.",
  "Xóa file khỏi Recycle Bin không nhất thiết xóa vật lý dữ liệu ngay.",
  "CPU hiện đại hoạt động ở hàng tỷ chu kỳ mỗi giây.",
  "GPU rất hữu ích cho AI nhờ xử lý song song.",
  "Neural network không lưu kiến thức đơn giản như database câu chữ.",
  "Language model dự đoán token tiếp theo nhưng có thể tạo hành vi phức tạp.",
  "AI có thể tạo thông tin nghe hợp lý nhưng sai.",
  "Antarctica là một sa mạc.",
  "Phần lớn nước ngọt Trái Đất nằm trong băng và sông băng.",
  "Challenger Deep sâu hơn độ cao Everest tính từ mực nước biển.",
  "Rất ít người từng trực tiếp xuống Challenger Deep.",
  "Các lục địa vẫn di chuyển vài centimet mỗi năm.",
  "Himalaya vẫn thay đổi độ cao do kiến tạo.",
  "Trái Đất hơi phình ở xích đạo.",
  "Mặt Trăng đang rời Trái Đất khoảng 3,8 cm mỗi năm.",
  "Mặt Trăng gần như luôn hướng cùng một mặt về Trái Đất do tidal locking.",
  "Đại Kim tự tháp Giza đã tồn tại khoảng 4.500 năm.",
  "Oxford có hoạt động giảng dạy trước khi Đế chế Aztec hình thành.",
  "T. rex sống gần thời con người hơn so với Stegosaurus.",
  "Đậu phộng thuộc họ legume.",
  "Không phải mọi tế bào trong cơ thể người đều có DNA; hồng cầu trưởng thành không có nhân.",
  "Mercury là hành tinh gần Mặt Trời nhất nhưng Venus nóng hơn.",
  "Mercury hoàn thành một năm trong khoảng 88 ngày Trái Đất.",
  "Olympus Mons trên Mars là núi lửa lớn nhất được biết trong Hệ Mặt Trời.",
  "Ganymede lớn hơn Mercury.",
  "Titan có hồ methane và ethane trên bề mặt.",
  "Enceladus phun hơi nước và băng từ đại dương ngầm.",
  "Uranus quay gần như nằm ngang.",
  "Neptune được dự đoán bằng toán học trước khi được quan sát.",
  "Pluto có vùng hình trái tim tên Tombaugh Regio.",
  "Trọng lực Mặt Trăng khoảng một phần sáu Trái Đất.",
  "ISS quay quanh Trái Đất khoảng mỗi 90 phút.",
  "Phi hành gia trên ISS có thể thấy khoảng 16 lần mặt trời mọc mỗi ngày.",
  "Mặt Trời chứa hơn 99% khối lượng Hệ Mặt Trời.",
  "Lõi Mặt Trời khoảng 15 triệu °C.",
  "Mặt Trời tạo năng lượng chủ yếu bằng nuclear fusion.",
  "Mặt Trời sẽ không nổ thành supernova.",
  "Sirius là sao sáng nhất trên bầu trời đêm nhìn từ Trái Đất.",
  "Milky Way là thiên hà xoắn ốc có thanh.",
  "Milky Way và Andromeda đang tiến lại gần nhau.",
  "Sagittarius A* là hố đen siêu khối lượng ở trung tâm Milky Way.",
  "Hố đen hợp nhất có thể tạo sóng hấp dẫn.",
  "Sóng hấp dẫn được phát hiện trực tiếp lần đầu năm 2015.",
  "White dwarf có thể cỡ Trái Đất nhưng khối lượng gần Mặt Trời.",
  "Pulsar là sao neutron quay nhanh.",
  "Magnetar có từ trường cực mạnh.",
  "Hàng nghìn exoplanet đã được xác nhận.",
  "Một số hành tinh quay quanh hai ngôi sao.",
  "Có rogue planets không quay quanh ngôi sao nào.",
  "Một parsec dài khoảng 3,26 năm ánh sáng.",
  "Ánh sáng chân không đi khoảng 300.000 km/s.",
  "GPS phải hiệu chỉnh hiệu ứng tương đối tính.",
  "Mars có hai vệ tinh Phobos và Deimos.",
  "Saturn không phải hành tinh duy nhất có vành đai.",
  "Jupiter, Uranus và Neptune cũng có vành đai.",
  "Ngày trên Jupiter chỉ khoảng 10 giờ.",
  "Europa có bằng chứng mạnh về đại dương dưới băng.",
  "Venus có áp suất bề mặt khoảng 90 lần Trái Đất.",
  "Mercury có băng nước trong một số miệng hố luôn tối.",
  "Sao xanh thường nóng hơn sao đỏ.",
  "Các mùa chủ yếu do trục Trái Đất nghiêng.",
  "Trái Đất gần Mặt Trời nhất vào đầu tháng 1.",
  "Nhật thực toàn phần cho phép nhìn thấy corona Mặt Trời.",
  "Khoảng 71% bề mặt Trái Đất được phủ nước.",
  "Pacific là đại dương lớn nhất.",
  "Mauna Kea cao hơn Everest nếu đo từ chân dưới biển.",
  "Chimborazo có đỉnh xa tâm Trái Đất hơn Everest.",
  "Lake Baikal là hồ nước ngọt sâu nhất.",
  "Greenland là đảo lớn nhất nếu không tính Australia là đảo.",
  "Africa đi qua cả xích đạo và hai chí tuyến.",
  "Amazon có lưu lượng nước lớn nhất trong các con sông.",
  "Antarctica là sa mạc lớn nhất nếu tính sa mạc cực.",
  "Atacama là một trong những nơi khô nhất Trái Đất.",
  "Antarctica là lục địa lạnh nhất.",
  "Iceland nằm trên ranh giới hai mảng kiến tạo.",
  "Hawaii hình thành chủ yếu trên một hotspot.",
  "Ring of Fire chứa rất nhiều núi lửa và động đất.",
  "Sóng thần có thể di chuyển cực nhanh ở biển sâu.",
  "Sét có thể làm cát nóng chảy thành fulgurite.",
  "Nước nở ra khi đóng băng.",
  "Băng nổi vì ít đặc hơn nước lỏng.",
  "Nước đạt mật độ lớn nhất gần 4°C.",
  "Một đám mây có thể nặng hàng trăm tấn.",
  "Fog về cơ bản là mây sát mặt đất.",
  "Hurricane, typhoon và cyclone là tên khu vực cho cùng loại bão nhiệt đới.",
  "Aurora hình thành khi hạt tích điện tương tác với khí quyển và từ trường.",
  "Từ trường Trái Đất đã đảo cực nhiều lần.",
  "Lõi ngoài Trái Đất là chất lỏng.",
  "Trái Đất khoảng 4,54 tỷ năm tuổi.",
  "Khí quyển chủ yếu là nitrogen.",
  "Oxygen chiếm khoảng 21% khí quyển khô.",
  "Canada có đường bờ biển dài nhất thế giới.",
  "Russia trải qua 11 múi giờ.",
  "Giác mạc không có mạch máu.",
  "Xương nhỏ nhất cơ thể là stapes trong tai.",
  "Umami là một vị cơ bản.",
  "Mùi đóng vai trò lớn trong cảm nhận hương vị.",
  "Men răng là mô cứng nhất cơ thể.",
  "Răng không phải xương.",
  "Trẻ em thường có 20 răng sữa.",
  "Da là cơ quan lớn nhất cơ thể.",
  "Mồ hôi bản thân gần như không có mùi mạnh.",
  "Tóc và móng chủ yếu chứa keratin.",
  "Song sinh cùng trứng vẫn không có vân tay hoàn toàn giống nhau.",
  "Máu người luôn có sắc đỏ.",
  "Hồng cầu trưởng thành sống khoảng 120 ngày.",
  "Tủy xương tạo phần lớn tế bào máu.",
  "Tim có hệ thống điện nội tại.",
  "Tim nằm gần giữa ngực và lệch trái.",
  "Phổi phải thường có ba thùy, phổi trái hai.",
  "Cơ hoành là cơ chính của hô hấp.",
  "Ruột non hấp thụ phần lớn chất dinh dưỡng.",
  "Appendix có mô miễn dịch và không hoàn toàn vô dụng.",
  "Gan sản xuất bile; túi mật lưu trữ và cô đặc nó.",
  "Pancreas vừa hỗ trợ tiêu hóa vừa tạo hormone.",
  "Thận cũng tham gia điều hòa huyết áp.",
  "Cơ thể có hơn 600 cơ xương.",
  "Run khi lạnh giúp tạo nhiệt.",
  "Xương lưu trữ phần lớn calcium của cơ thể.",
  "Bạn thường cao hơn một chút vào buổi sáng.",
  "Con người và hươu cao cổ thường đều có bảy đốt sống cổ.",
  "Giấc ngủ quan trọng cho củng cố trí nhớ.",
  "Não vẫn hoạt động mạnh khi ngủ.",
  "Con người có đồng hồ circadian gần 24 giờ.",
  "Não không thực sự multitask tốt với nhiều nhiệm vụ chú ý cao.",
  "Motion sickness thường liên quan xung đột giữa thị giác và hệ tiền đình.",
  "Caffeine chủ yếu chặn receptor adenosine.",
  "Con người có nhiều hơn năm giác quan cổ điển.",
  "Proprioception giúp biết vị trí tay chân mà không cần nhìn.",
  "Koala có vân tay rất giống người.",
  "Platypus là động vật có vú đẻ trứng.",
  "Echidna cũng là động vật có vú đẻ trứng.",
  "Platypus cảm nhận điện trường từ con mồi.",
  "Gấu Bắc Cực có da đen bên dưới lông.",
  "Penguin không sống tự nhiên ở Bắc Cực.",
  "Ostrich là loài chim sống lớn nhất.",
  "Peregrine falcon cực nhanh khi bổ nhào.",
  "Cú không thể xoay đầu 360 độ.",
  "Flamingo hồng nhờ sắc tố trong thức ăn.",
  "Chim là hậu duệ sống của một nhánh khủng long.",
  "Pterosaur không phải khủng long.",
  "Cá sấu có họ hàng tiến hóa gần với chim hơn thằn lằn.",
  "Mai rùa là một phần bộ xương.",
  "Chameleon đổi màu không chỉ để ngụy trang.",
  "Gecko bám tường nhờ cấu trúc siêu nhỏ trên chân.",
  "Rắn dùng lưỡi thu phân tử mùi.",
  "Seahorse đực mang thai.",
  "Electric eel không phải eel thật.",
  "Whale shark là loài cá lớn nhất.",
  "Orca là thành viên lớn nhất họ dolphin.",
  "Narwhal tusk là một chiếc răng kéo dài.",
  "Sea otter dùng đá làm công cụ.",
  "Vòi voi chứa hàng chục nghìn bó cơ.",
  "Rhino horn chủ yếu làm từ keratin.",
  "Giant panda có một 'ngón cái' giả từ xương cổ tay.",
  "Bat là động vật có vú duy nhất bay chủ động thực sự.",
  "Răng beaver màu cam do men giàu iron.",
  "Capybara là loài gặm nhấm lớn nhất còn sống.",
  "Rabbit không phải rodent.",
  "Mèo không cảm nhận vị ngọt giống người.",
  "Hyena không phải dog.",
  "Cheetah là động vật trên cạn nhanh nhất trong quãng ngắn.",
  "Bonobo và chimpanzee là hai họ hàng sống gần nhất của người.",
  "Coast redwood là loài cây cao nhất còn sống.",
  "Cây lấy phần lớn carbon khối lượng từ CO₂ trong không khí.",
  "Yeast là nấm đơn bào.",
  "Mushroom thường chỉ là cấu trúc sinh sản của nấm.",
  "Coconut là một drupe.",
  "Apple và rose cùng họ Rosaceae.",
  "Avocado là berry theo thực vật học.",
  "Tomato là fruit theo thực vật học.",
  "Vanilla đến từ một loài orchid.",
  "Green, black, white và oolong tea đều có thể từ Camellia sinensis.",
  "Potato là thân củ; sweet potato là rễ củ.",
  "Broccoli, kale và cabbage đều là dạng của Brassica oleracea.",
  "Banana plant là thảo mộc khổng lồ.",
  "Capsaicin kích hoạt receptor cảm nhận nhiệt.",
  "Menthol kích hoạt receptor cảm nhận lạnh.",
  "Sunflower head gồm rất nhiều hoa nhỏ.",
  "Seagrass là thực vật có hoa; kelp là algae.",
  "Starfish không phải fish.",
  "Horseshoe crab gần họ hàng với spider hơn crab thật.",
  "Nguyên tử chủ yếu là khoảng trống theo hình dung cổ điển.",
  "Proton và neutron được cấu tạo từ quark.",
  "Photon không có khối lượng nghỉ.",
  "Ánh sáng thể hiện cả tính sóng và hạt.",
  "0 kelvin bằng khoảng -273,15°C.",
  "Heat và temperature không phải cùng một khái niệm.",
  "Diamond và graphite đều làm từ carbon.",
  "Graphene dày một lớp nguyên tử carbon.",
  "Glass là chất rắn vô định hình, không phải chất lỏng chảy chậm.",
  "Mercury là kim loại lỏng ở nhiệt độ phòng.",
  "Gallium có thể tan trong lòng bàn tay.",
  "Helium được phát hiện trong quang phổ Mặt Trời trước khi tìm thấy trên Trái Đất.",
  "Hydrogen là nguyên tố phổ biến nhất vũ trụ.",
  "Vàng rất dễ dát mỏng.",
  "Soap có một đầu thích nước và một đầu thích dầu.",
  "Surface tension cho phép water strider đi trên nước.",
  "Dry ice thăng hoa trực tiếp thành khí.",
  "Liquid nitrogen sôi khoảng -196°C.",
  "Âm thanh là sóng cơ học cần môi trường vật chất.",
  "Decibel là thang logarithmic.",
  "Radio, microwave, infrared, visible, UV, X-ray và gamma đều là bức xạ điện từ.",
  "Microwave không làm thức ăn trở thành phóng xạ.",
  "Ozone tầng bình lưu hấp thụ nhiều UV có hại.",
  "Half-life mô tả tốc độ phân rã phóng xạ theo thống kê.",
  "Nhà máy điện hạt nhân hiện nay chủ yếu dùng fission.",
  "2 là số nguyên tố chẵn duy nhất.",
  "Không có số nguyên tố lớn nhất.",
  "Möbius strip chỉ có một mặt và một cạnh.",
  "Bluetooth được đặt theo vua Harald Bluetooth.",
  "Wi-Fi không phải viết tắt chính thức của Wireless Fidelity.",
  "USB-C mô tả đầu nối chứ không đảm bảo cùng tốc độ.",
  "SSD không có platter quay như HDD.",
  "IPv4 có khoảng 4,3 tỷ địa chỉ lý thuyết.",
  "IPv6 address dài 128 bit.",
  "Ping thường dùng ICMP.",
  "TCP và UDP có các đặc tính truyền dữ liệu khác nhau.",
  "HTTP/3 sử dụng QUIC.",
  "127.0.0.1 là loopback IPv4 phổ biến.",
  "::1 là loopback IPv6.",
  "VPN không khiến người dùng vô danh tuyệt đối.",
  "Git và GitHub không phải cùng một thứ.",
  "Git không cần Internet để commit local.",
  "Container không phải virtual machine đầy đủ.",
  "Serverless vẫn chạy trên server.",
  "RAID không thay thế backup.",
  "Password manager giúp dùng mật khẩu riêng biệt cho từng tài khoản.",
  "Hashing và encryption không phải cùng một thứ.",
  "Salt giúp bảo vệ password hash khỏi precomputed tables.",
  "QR code có thể chứa URL độc hại.",
  "Malware là thuật ngữ chung cho phần mềm độc hại.",
  "Worm có thể tự lan qua mạng.",
  "Trojan giả dạng phần mềm hợp pháp hoặc hữu ích.",
  "Botnet là mạng thiết bị bị kiểm soát.",
  "Least privilege nghĩa là chỉ cấp quyền tối thiểu cần thiết.",
  "Decompiler hiếm khi khôi phục chính xác source code gốc.",
  "x86-64 và ARM64 là hai ISA phổ biến.",
  "Clock speed một mình không đủ so hiệu năng CPU.",
  "Cosmic rays có thể góp phần gây bit flip.",
  "PNG thường dùng lossless compression.",
  "JPEG thường dùng lossy compression.",
  "Latency và bandwidth không phải cùng một thứ.",
  "GPS receiver chủ yếu nhận tín hiệu từ satellite để tính vị trí.",
  "OLED pixel tự phát sáng.",
  "E-ink giữ hình tĩnh với rất ít năng lượng ở nhiều thiết kế.",
  "JavaScript được tạo rất nhanh vào năm 1995.",
  "Java và JavaScript là hai ngôn ngữ khác nhau.",
  "HTML là markup language.",
  "TypeScript là superset của JavaScript.",
  "AI training và inference là hai giai đoạn khác nhau.",
  "LLM xử lý text dưới dạng token.",
  "Token không luôn bằng một từ.",
  "Fine-tuning thay đổi model weights; prompt engineering thường không.",
  "Transformer dùng attention làm thành phần trung tâm.",
  "VRAM thường là giới hạn quan trọng khi chạy AI local.",
  "Writing xuất hiện độc lập ở nhiều nền văn minh.",
  "Rosetta Stone giúp giải mã hieroglyphs Ai Cập.",
  "Paper được phát triển ở Trung Quốc cổ đại.",
  "Movable type xuất hiện ở Đông Á trước Gutenberg.",
  "Roman numeral cổ điển không có ký hiệu zero.",
  "Algebra lấy tên từ Arabic 'al-jabr'.",
  "Algorithm lấy tên từ al-Khwarizmi.",
  "Eratosthenes ước tính chu vi Trái Đất bằng bóng nắng.",
  "Viking đã đến Bắc Mỹ trước Columbus hàng thế kỷ.",
  "Smallpox là bệnh ở người đầu tiên được xóa sổ toàn cầu.",
  "Marie Curie giành Nobel ở hai lĩnh vực khoa học.",
  "Einstein nhận Nobel chủ yếu cho photoelectric effect.",
  "Darwin và Wallace độc lập phát triển ý tưởng natural selection.",
  "Mendel nghiên cứu di truyền bằng pea plants.",
  "Rosalind Franklin tạo dữ liệu X-ray quan trọng cho cấu trúc DNA.",
  "English thuộc nhánh Germanic.",
  "Emoji có nguồn gốc từ Nhật Bản.",
  "@ có lịch sử trước email hàng thế kỷ.",
  "Basketball được James Naismith tạo năm 1891.",
  "LEGO tên đến từ Danish 'leg godt'.",
  "Velcro được lấy cảm hứng từ burr bám vào lông.",
  "Bubble wrap ban đầu được thử làm wallpaper.",
  "Play-Doh có nguồn gốc từ sản phẩm làm sạch wallpaper.",
  "Can opener xuất hiện hàng chục năm sau canned food.",
  "Caesar salad được tạo ở Mexico.",
  "Fortune cookie hiện đại không phải truyền thống Trung Quốc cổ.",
  "Yogurt được tạo bởi bacteria lên men lactose.",
  "Denim có tên liên hệ với Nîmes, France.",
  "Jeans riveted được patent bởi Levi Strauss và Jacob Davis.",
  "Ignaz Semmelweis cho thấy rửa tay làm giảm tử vong sản khoa.",
  "Antibiotics không trị virus như common cold.",
  "Bacteriophage là virus nhiễm bacteria.",
  "Mitochondria có DNA riêng.",
  "Con người thường có 23 cặp chromosome trong tế bào soma.",
  "Natural selection không có mục tiêu định sẵn.",
  "Con người không tiến hóa từ monkey hiện đại; chúng ta có tổ tiên chung.",
  "Whale tiến hóa từ tổ tiên động vật có vú sống trên cạn.",
  "Flight tiến hóa độc lập ở insects, pterosaurs, birds và bats.",
  "Non-avian dinosaurs tuyệt chủng khoảng 66 triệu năm trước.",
  "Mammals đã sống cùng dinosaurs.",
  "Dog là một trong những động vật được thuần hóa sớm nhất.",
  "Corn hiện đại được chọn lọc từ teosinte.",
  "Domestic chicken có nguồn gốc chủ yếu từ red junglefowl.",
  "Termite có họ hàng gần với cockroach hơn ant.",
];
