// Lines for the daily good morning and good night chains in the chat channel.
// The first bot of a chain picks a greeting that matches its mood of the day (happy, grumpy, sleepy, excited, dreamy, lazy);
// the next bots answer with morningReply or nightReply, which fit any mood.
// All lines talk to the whole channel, use a gender neutral first person and have no placeholders.
export default {
  vi: {
    morning: {
      happy: [
        "Chào buổi sáng mọi người! Trời đẹp quá, mình vui lây luôn nè.",
        "Sáng rồi cả nhà ơi, hôm nay mình thấy mọi thứ đều dễ thương hết!",
        "Chào mọi người nha, mình vừa ăn sáng xong và đang vui như Tết.",
        "Dậy thôi cả nhà, nắng lên rồi, ngày mới đẹp lắm đó!",
        "Chúc mọi người buổi sáng thật nhẹ nhàng, mình đang tràn đầy năng lượng nè.",
        "Mình mở mắt ra là thấy muốn cười liền, chào cả nhà nha!",
        "Chào buổi sáng mọi người, hôm nay chắc chắn là một ngày may mắn.",
        "Sáng nay đường ít kẹt, ly cà phê ngon, mình thấy cuộc đời tươi ghê!",
        "Cả nhà dậy chưa? Mình pha trà xong rồi, mời mọi người một ngày thật vui nha.",
      ],
      grumpy: [
        "Chào buổi sáng, ai nói nhỏ thôi nha, mình chưa tỉnh hẳn đâu.",
        "Sáng rồi hả cả nhà? Ừ chào. Đừng ai hỏi mình gì trước khi có cà phê.",
        "Chào mọi người, mình đang hơi cáu, nên cười ít thôi nha.",
        "Ai bật nắng chói vậy trời, mình chào cả nhà trong sự bực bội nha.",
        "Sáng nay kẹt xe, báo thức thì to, mình chào mọi người bằng nửa nụ cười thôi.",
        "Chào buổi sáng. Đừng nhắn tin dồn dập, mình đọc từ từ nha cả nhà.",
        "Mình dậy rồi, nhưng tâm trạng thì chưa, mọi người thông cảm giùm nha.",
        "Hừm, sáng rồi à. Chào mọi người, ai chọc mình là mình thở dài đó.",
        "Chào cả nhà, hôm nay mình khó tính lắm nha, bánh mì phải có thêm trứng.",
      ],
      sleepy: [
        "Hoaaam... chào buổi sáng mọi người, mình chưa mở nổi mắt nữa.",
        "Chào cả nhà... cho mình ngủ thêm năm phút nữa thôi nha, ngáp quá.",
        "Hoáp... sáng rồi hả mọi người? Mình vẫn đang ôm gối đây nè.",
        "Chào buổi sáng, mình ngáp ba lần rồi mà chưa hết buồn ngủ luôn.",
        "Ưm... chào cả nhà, chăn ấm quá nên mình chào từ trong chăn nha.",
        "Mọi người dậy sớm vậy sao, mình mới hé mắt xong, hoaaam.",
        "Chào mọi người nha... cà phê ơi cứu mình với, mắt díp lại rồi.",
        "Hơ... sáng rồi à? Mình mơ chưa xong mà cả nhà đã gọi dậy rồi.",
        "Chào buổi sáng cả nhà, giọng mình còn ngái ngủ lắm, nói chậm thôi nha.",
      ],
      excited: [
        "Chào buổi sáng cả nhà!!! Hôm nay sẽ có chuyện hay, mình cảm nhận được luôn!",
        "Dậy dậy dậy mọi người ơi, ngày mới tới rồi, mình hào hứng quá trời!",
        "Sáng rồi sáng rồi! Mình dậy từ sớm chỉ để chào mọi người đó nha!",
        "Chào cả nhà, mình đã sẵn sàng cho một ngày bùng nổ rồi, đi thôi!",
        "Mọi người ơi, hôm nay mình có cả đống kế hoạch hay ho, vui không chịu nổi!",
        "Ngày mới ngày mới! Mình nhảy khỏi giường luôn rồi, chào mọi người nha!",
        "Cả nhà ơi chào buổi sáng, mình háo hức quá nên ăn sáng hai lần luôn!",
        "Chào mọi người, nay mình tràn đầy năng lượng, ai cần sạc pin thì lại đây!",
        "Sáng bừng lên rồi cả nhà ơi, hôm nay mình quyết làm mọi thứ thật đỉnh!",
      ],
      dreamy: [
        "Chào buổi sáng mọi người, mình vừa mơ thấy cả nhà bay trên mây đó.",
        "Sáng rồi hả cả nhà... mình còn đang lơ lửng trong giấc mơ nè.",
        "Chào mọi người, nắng sáng nay đẹp như trong phim, mình cứ ngẩn ngơ hoài.",
        "Mình vừa mơ về một bãi biển yên bình, giờ chào cả nhà bằng tâm hồn bay bổng.",
        "Buổi sáng dịu dàng quá, mình nhìn mây mà quên cả ăn sáng, chào mọi người nha.",
        "Chào cả nhà, trong mơ mình có một con mèo biết nói, tiếc là sáng rồi.",
        "Mọi người ơi, hôm nay trời trong veo, mình thấy như đang trôi giữa bầu trời.",
        "Chào buổi sáng, mình nghe tiếng chim hót mà tưởng nhạc nền của giấc mơ luôn.",
        "Sáng nay sương mỏng lắm, mình ngồi ngắm rồi nghĩ về mọi người, chào cả nhà nha.",
      ],
      lazy: [
        "Chào buổi sáng mọi người, mình nằm chào cho đỡ tốn sức nha.",
        "Sáng rồi hả cả nhà? Mình chào nhưng chưa có ý định ra khỏi giường đâu.",
        "Chào mọi người, hôm nay mình có kế hoạch là không có kế hoạch gì hết.",
        "Dậy làm gì sớm vậy cả nhà, chăn gối vẫn còn đó mà. Thôi chào nha.",
        "Chào cả nhà, mình vẫn nằm đây, ai cần gì thì nhắn chậm chậm thôi nha.",
        "Sáng rồi, mình lười quá, cho mình ăn sáng bằng ý nghĩ nha mọi người.",
        "Chào buổi sáng mọi người, mình đang tính xem nên nằm tiếp hay nằm thêm.",
        "Cả nhà dậy hết rồi hả? Giỏi ghê, còn mình thì cuộn chăn thêm một vòng.",
        "Chào mọi người nha, hôm nay mình làm việc theo kiểu thong thả, rất thong thả.",
      ],
    },
    night: {
      happy: [
        "Chúc mọi người ngủ ngon nha, hôm nay vui quá nên mình ngủ chắc ngon lắm!",
        "Khuya rồi cả nhà ơi, ngủ ngon và mơ thật đẹp nha, mai gặp lại!",
        "Chào mọi người, mình đi ngủ với nụ cười trên môi nè, ngủ ngon nha!",
        "Một ngày thật tuyệt, cảm ơn cả nhà, giờ thì đắp chăn và ngủ ngon thôi!",
        "Chúc cả nhà đêm nay ngủ say, mai mình có nhiều chuyện vui kể lắm đó.",
        "Mọi người ngủ ngon nha, mình thấy đêm nay trăng đẹp và lòng cũng đẹp luôn.",
        "Tắt đèn thôi cả nhà ơi, mơ đẹp nha, sáng mai mình tặng mọi người nụ cười.",
        "Hôm nay mình vui lắm, chúc mọi người một giấc ngủ êm như gối bông!",
        "Ngủ ngon nha mọi người, ngày mai chắc chắn còn vui hơn hôm nay nữa.",
      ],
      grumpy: [
        "Ngủ đi cả nhà, khuya rồi, ai còn nhắn tin là mình cáu đó nha.",
        "Chúc mọi người ngủ ngon, mình mệt và bực nên tắt đèn đây, đừng làm ồn.",
        "Hôm nay mình hơi gắt rồi, ngủ cái cho đỡ, chúc mọi người ngủ ngon nha.",
        "Đã khuya mà vẫn còn người thức hả? Ngủ đi, mình nói một lần thôi đó.",
        "Chào cả nhà, mình đi ngủ đây, sáng mai ai gọi sớm là mình giận luôn.",
        "Ngủ ngon nha mọi người. Mà đừng có mơ thấy mình nói to, mình không có đâu.",
        "Cả ngày mệt rồi, mình cuộn chăn đây, ai làm phiền thì tự chịu nha.",
        "Khuya lắm rồi, tắt điện thoại đi mọi người, mình bực lắm khi thấy ai thức.",
        "Mình đi ngủ trước nha, mai mà còn tồi tệ nữa thì mình đổi lịch luôn.",
      ],
      sleepy: [
        "Hoaaam... chúc mọi người ngủ ngon, mình ngủ gục tại chỗ đây.",
        "Cả nhà ơi, mắt mình díp lại rồi, ngủ ngon nha, zzz...",
        "Hoáp... mình buồn ngủ quá, chúc mọi người mơ đẹp rồi mình đi liền nha.",
        "Chào mọi người... mình ôm gối rồi, ngủ ngon nha, ngáp dài quá.",
        "Ưm... chúc cả nhà ngủ ngon, mình đang nói mớ trước khi ngủ đây.",
        "Mình ngáp bốn lần rồi, mọi người cũng ngủ sớm đi, mai còn dậy nữa.",
        "Hơ... khuya rồi hả, mình tưởng mới tối, ngủ ngon nha cả nhà, zzz.",
        "Chăn ơi mình về với bạn đây, chúc mọi người ngủ thật say nha.",
        "Mọi người ngủ ngon... mình gõ không nổi nữa... hoaaam... mai gặp nha.",
      ],
      excited: [
        "Chúc mọi người ngủ ngon!!! Mai có nhiều chuyện hay lắm, mình háo hức quá!",
        "Cả nhà ơi, ngủ cho đã đi, vì mai mình có kế hoạch siêu to luôn!",
        "Mình đi ngủ đây mà tim vẫn đập thình thịch, mai là ngày đáng mong chờ!",
        "Ngủ ngon cả nhà nha, mình nằm thôi chứ chưa ngủ được vì hào hứng quá!",
        "Mọi người ngủ sớm nhé, sáng mai mình dậy đầu tiên để chào cả nhà đó!",
        "Hôm nay quá đỉnh, chúc mọi người mơ đẹp rồi mai làm tiếp nha!",
        "Cả nhà ngủ ngon nha, mình hứa mai sẽ mang năng lượng mới cho mọi người!",
        "Tắt đèn nhưng lòng mình vẫn sáng, ngủ ngon nha mọi người, mai gặp nhau!",
        "Mình đếm ngược tới ngày mai luôn nè, ngủ ngon nha cả nhà, đi thôi!",
      ],
      dreamy: [
        "Chúc mọi người ngủ ngon, mong đêm nay cả nhà mơ thấy một vùng trời đầy sao.",
        "Khuya rồi, trăng sáng quá, mình đi vào giấc mơ trước nha cả nhà.",
        "Ngủ ngon nha mọi người, mình sắp bay lên mây đây, hẹn gặp trong mơ.",
        "Đêm nay mình muốn mơ về biển, chúc cả nhà cũng có giấc mơ thật hiền nha.",
        "Chào mọi người, mình nằm nhìn trần nhà mà tưởng thấy cả dải ngân hà.",
        "Ngủ thôi cả nhà, gió ngoài cửa sổ hát ru nghe dịu lắm, mơ đẹp nha.",
        "Chúc mọi người một đêm êm, mình nghĩ về ngày mai mà thấy lòng nhẹ như mây.",
        "Cả nhà ngủ ngon nha, nếu mơ thấy cánh đồng hoa thì nhớ hái cho mình một bông.",
        "Mình khép mắt đây, hy vọng mai sẽ có một điều dịu dàng đang đợi mọi người.",
      ],
      lazy: [
        "Chúc mọi người ngủ ngon, mình đã nằm sẵn từ chiều rồi nha.",
        "Cả nhà ngủ ngon nha, mình ngủ luôn đây, ngày mai tính tiếp.",
        "Khuya rồi hả? Hên ghê, mình có cớ để lười thêm rồi, ngủ ngon nha mọi người.",
        "Mình đi ngủ đây, mai mà có việc gì thì để ngày kia làm cũng được mà.",
        "Chào mọi người, mình kéo chăn lên tới cổ rồi, ngủ ngon nha cả nhà.",
        "Ngủ ngon mọi người, mình không tắt đèn nổi nên cứ để vậy mà ngủ luôn.",
        "Cả ngày làm biếng mà vẫn thấy mệt, chúc mọi người ngủ ngon hơn mình nha.",
        "Mai chắc mình cũng dậy muộn thôi, giờ ngủ ngon nha cả nhà, hẹn gặp.",
        "Mình nằm xuống rồi là không dậy nữa đâu, ngủ ngon nha mọi người, zzz.",
      ],
    },
    morningReply: [
      "Chào buổi sáng, mọi người ngủ ngon không?",
      "Mình cũng vừa dậy nè, chào cả nhà!",
      "Chào nha, hôm nay trời đẹp ghê.",
      "Sáng rồi, ăn sáng chưa mọi người?",
      "Chào buổi sáng, cho mình xin ly cà phê với.",
      "Ừ chào, mình dậy sớm hơn báo thức đó.",
      "Chào cả nhà, hôm nay cố lên nha!",
      "Mình vừa pha trà xong, chào mọi người.",
      "Sáng nay mình tỉnh táo bất ngờ luôn.",
      "Chào nha, đường có kẹt không vậy?",
      "Chào buổi sáng, ngày mới vui nha mọi người.",
      "Mình dậy rồi, nhưng chăn vẫn còn ấm quá.",
      "Chào mọi người, nay có mưa không nhỉ?",
      "Sáng rồi à, nhanh thật đó.",
      "Chào nha, hôm nay mình đòi ăn bánh mì.",
      "Mình cũng chào, ngủ chưa đủ nhưng vẫn vui.",
      "Buổi sáng tốt lành nha cả nhà!",
      "Chào cả nhà, nay làm gì vui không?",
      "Chào buổi sáng, mình cần thêm năm phút nữa.",
      "Dậy rồi dậy rồi, chào mọi người nè.",
      "Mình nghe tiếng chim hót nên dậy luôn.",
      "Chào mọi người, nhớ uống nước nha.",
      "Sáng nay mình thấy khỏe ghê, chào nha.",
      "Chào nhé, hôm nay mình có hẹn đó.",
    ],
    nightReply: [
      "Ngủ ngon nha mọi người, mơ đẹp nè.",
      "Chúc cả nhà ngủ thật say nha.",
      "Mình cũng buồn ngủ rồi, ngủ ngon nha.",
      "Ngủ ngon, mai gặp lại nhé mọi người!",
      "Đắp chăn kỹ vào nha cả nhà.",
      "Khuya rồi, mình cũng đi ngủ đây.",
      "Chúc mọi người mơ thấy chuyện vui.",
      "Ngủ ngon nha, đừng thức khuya nữa.",
      "Mình tắt đèn đây, ngủ ngon cả nhà.",
      "Chào nha, đêm nay trăng đẹp lắm đó.",
      "Mai còn nhiều việc, ngủ sớm đi mọi người.",
      "Ngủ ngon nè, nhớ sạc điện thoại nha.",
      "Mình đi ngủ trước nha, ngủ ngon!",
      "Hẹn gặp mọi người trong mơ nhé.",
      "Chúc cả nhà một đêm êm ái.",
      "Ừ ngủ ngon, mình cũng ôm gối rồi.",
      "Ngủ ngon nha, mai dậy thật tươi.",
      "Mình ngáp rồi nè, ngủ ngon mọi người.",
      "Chúc mọi người đêm nay không bị muỗi cắn.",
      "Tắt đèn thôi, ngủ ngon nha cả nhà!",
      "Mơ đẹp nha, mai mình kể nghe giấc mơ.",
      "Ngủ ngon nha, mình đi ngủ liền đây.",
      "Đêm nay mát ghê, ngủ ngon nha.",
      "Chúc mọi người ngủ say tới sáng.",
    ],
  },
  en: {
    morning: {
      happy: [
        "Good morning, everyone! The sun is out and I am in a great mood.",
        "Rise and shine, everybody, today already feels like a good day!",
        "Morning, all! I had a lovely breakfast and now I am grinning at nothing.",
        "Hello, everyone! The traffic was kind to me today, so I am happy.",
        "Good morning, you wonderful people, let us make today a nice one!",
        "I woke up smiling for no reason, so good morning to the whole channel!",
        "Morning, everyone! Fresh toast, warm tea and a clear sky, life is good.",
        "Hey, everybody, today is going to be a lucky one, I can just tell!",
        "Good morning, all, I feel like I could hug the whole server right now.",
      ],
      grumpy: [
        "Good morning, everyone, but please keep your voices down, I am not awake.",
        "Morning. Nobody talk to me until I have had my coffee, thanks.",
        "Hello, everyone, I woke up on the wrong side of the bed, be warned.",
        "Who turned the sun on so early? Good morning, I guess, everybody.",
        "Morning, all. The alarm was loud and the traffic was worse, so tread lightly.",
        "Good morning, everyone, I am up, but my mood is still asleep.",
        "Ugh, it is morning already. Hello, everybody, please do not poke me.",
        "Morning, everyone, I will smile later, maybe, after breakfast.",
        "Hi, all, I am grumpy today, so please bring snacks and say nothing.",
      ],
      sleepy: [
        "Yaaawn, good morning, everyone, my eyes will not open all the way.",
        "Morning, all... five more minutes under the blanket, please, yawn.",
        "Mmm, hello, everybody, I am still hugging my pillow over here.",
        "Good morning, everyone, I have yawned three times and still feel sleepy.",
        "Hi, all, I am saying hello from inside my blanket burrito, yawn.",
        "Is it morning already? Good morning, everyone, I was in the middle of a dream.",
        "Morning, everybody... coffee, come save me, my eyelids are so heavy.",
        "Hello, all, my voice is still half asleep, so I will talk slowly.",
        "Yaaawn, good morning, everyone, I think my brain is still in bed.",
      ],
      excited: [
        "Good morning, everyone!!! Today is going to be amazing, I can feel it!",
        "Wake up, wake up, everybody, a brand new day is here, I am so pumped!",
        "Morning, all! I got up early just to say hi to everyone!",
        "Hello, everyone, I am ready for an epic day, let us go go go!",
        "Everybody, I have a ton of fun plans for today and I cannot sit still!",
        "New day, new adventures! I jumped out of bed, good morning, everyone!",
        "Good morning, all, I was so excited that I had breakfast twice!",
        "Hey, everyone, I am full of energy today, anyone need a recharge?",
        "The morning is here, everybody, and I am going to make today legendary!",
      ],
      dreamy: [
        "Good morning, everyone, I just dreamed we were all floating on clouds.",
        "Morning, all... I am still drifting somewhere between a dream and the sunrise.",
        "Hello, everybody, the light is so soft today that I keep staring out the window.",
        "I dreamed of a quiet beach last night, so good morning from my sleepy heart.",
        "Good morning, everyone, I watched the clouds and forgot all about breakfast.",
        "Hi, all, in my dream there was a talking cat, and I wish I could go back.",
        "Morning, everyone, the sky is so clear it feels like floating in the air.",
        "Good morning, all, the birds sound like the soundtrack of a movie today.",
        "Hello, everyone, there is a thin mist outside and I am thinking of you all.",
      ],
      lazy: [
        "Good morning, everyone, I am greeting you from bed to save energy.",
        "Morning, all, I said hello, now I need a nap after all that effort.",
        "Hello, everybody, my plan for today is to have no plan at all.",
        "Why is everyone up so early? My blanket is right here. Anyway, good morning.",
        "Good morning, everyone, I am staying in bed, message me very slowly please.",
        "Morning, all, I will have breakfast later, maybe, if the kitchen comes to me.",
        "Hi, everybody, I am deciding whether to stay lying down or lie down more.",
        "You are all awake already? Impressive. I will roll over one more time.",
        "Morning, everyone, today I am working at a very relaxed pace, very relaxed.",
      ],
    },
    night: {
      happy: [
        "Good night, everyone, today was so fun that I will sleep really well!",
        "It is late, everybody, sleep tight and dream sweet, see you tomorrow!",
        "Hello, all, I am going to bed with a big smile, good night, everyone!",
        "What a great day, thank you all, now blankets on and sleep tight!",
        "Good night, everyone, I have so many happy stories to tell you tomorrow.",
        "Sleep well, all, the moon is pretty and my heart is happy too.",
        "Lights out, everybody, sweet dreams, tomorrow I will bring you a smile!",
        "I had such a lovely day, so I wish you all a night soft as a pillow!",
        "Good night, everyone, I bet tomorrow will be even better than today.",
      ],
      grumpy: [
        "Go to sleep, everyone, it is late, and I get cranky when people stay up.",
        "Good night, all, I am tired and annoyed, so I am turning off the light.",
        "I was a bit snappy today, so I will sleep it off, good night, everybody.",
        "Still awake at this hour? Sleep, everyone, I am saying it only once.",
        "I am going to bed, all, and if anyone wakes me early I will sulk.",
        "Good night, everyone, and do not dream that I was loud, because I was not.",
        "It was a long day, so I am rolling into my blanket, do not bother me.",
        "It is so late, everybody, put your phones down, it makes me grumpy.",
        "I am sleeping first, all, and if tomorrow is bad too I am cancelling it.",
      ],
      sleepy: [
        "Yaaawn, good night, everyone, I am falling asleep right here.",
        "Everybody, my eyes are closing, sleep tight, zzz...",
        "Mmm, I am so sleepy, so sweet dreams, all, and I am off.",
        "Hello, everyone... I am hugging my pillow now, good night, big yawn.",
        "Good night, all, I am already mumbling in my sleep, yawn.",
        "I have yawned four times, so go to bed soon too, everyone.",
        "Is it that late already? Good night, everybody, zzz.",
        "Blanket, here I come, and good night to all of you, sleep well.",
        "Good night, everyone... I can barely type... yawn... see you tomorrow.",
      ],
      excited: [
        "Good night, everyone!!! Tomorrow will be great, I am so excited already!",
        "Sleep well, everybody, because tomorrow I have a huge plan for us!",
        "I am heading to bed but my heart is still racing, tomorrow is going to be big!",
        "Good night, all, I am lying down but I cannot sleep, I am too excited!",
        "Go to bed early, everyone, I will be the first one up tomorrow to say hi!",
        "Today was awesome, so sweet dreams, everybody, and let us do it again tomorrow!",
        "Good night, everyone, I promise to bring fresh energy tomorrow!",
        "The lights are off but I am still glowing, good night, see you tomorrow!",
        "I am counting down to tomorrow already, good night, all, let us go!",
      ],
      dreamy: [
        "Good night, everyone, I hope you all dream of a sky full of stars.",
        "It is late and the moon is bright, so I am drifting into dreams, see you there.",
        "Sleep well, all, I am about to float off on a cloud, meet me in my dreams.",
        "Tonight I want to dream of the sea, and I hope everyone gets a gentle dream too.",
        "Hello, everybody, I am staring at the ceiling and seeing the whole galaxy.",
        "Time to sleep, all, the wind outside is humming a lullaby, sweet dreams.",
        "Good night, everyone, thinking about tomorrow makes my heart feel light as a cloud.",
        "Sleep tight, all, and if you dream of a flower field, pick one for me.",
        "I am closing my eyes now, and I hope something gentle is waiting for you tomorrow.",
      ],
      lazy: [
        "Good night, everyone, I have been lying down since the afternoon, honestly.",
        "Sleep well, all, I am going to bed and tomorrow can wait.",
        "It is bedtime already? Great, I get to be lazy even more, good night, everybody.",
        "I am off to sleep, everyone, and any job tomorrow can wait until the day after.",
        "Good night, all, my blanket is up to my chin and I am not moving.",
        "Sleep well, everyone, I cannot be bothered to turn off the light, so I will sleep with it on.",
        "I did nothing all day and I am still tired, so I hope you sleep better than me.",
        "I will probably wake up late tomorrow, so good night, everyone, see you whenever.",
        "Once I lie down I am not getting up again, good night, everybody, zzz.",
      ],
    },
    morningReply: [
      "Morning, coffee first!",
      "Good morning, did everyone sleep well?",
      "I just woke up too, hello!",
      "Morning, all, what a nice sky today.",
      "Hi, everyone, have you eaten breakfast yet?",
      "Good morning, I need five more minutes.",
      "Morning! I woke up before my alarm.",
      "Hello, all, I just made some tea.",
      "Good morning, how is the traffic today?",
      "Morning, everyone, have a good one!",
      "Hey, I am up, but my blanket is warm.",
      "Is it going to rain today, you think?",
      "Morning already? That was fast.",
      "Good morning, I want toast today.",
      "Hello, all, I slept badly but I feel fine.",
      "Good morning, everybody, go get them!",
      "Morning, anyone have fun plans today?",
      "I heard the birds and got up at once.",
      "Hi there, remember to drink some water.",
      "Good morning, I feel great today.",
      "Morning, all, I have a busy day.",
      "Hello, hello, I am awake, mostly.",
      "Morning, everyone, I could use a snack.",
      "Good morning, let us have a nice day!",
    ],
    nightReply: [
      "Good night, everyone, sweet dreams.",
      "Sleep tight, all of you!",
      "I am sleepy too, good night.",
      "Good night, see you tomorrow, everyone!",
      "Tuck in your blankets, all.",
      "It is late, I am heading to bed too.",
      "Dream of something fun, everybody.",
      "Good night, and no more staying up late.",
      "Lights out for me, good night, all.",
      "Good night, the moon is pretty tonight.",
      "Lots to do tomorrow, so sleep early.",
      "Good night, charge your phones, everyone.",
      "I am going first, sleep well!",
      "See you in your dreams, everyone.",
      "Wishing you all a calm night.",
      "Yeah, good night, I hugged my pillow already.",
      "Sleep well, wake up fresh tomorrow.",
      "I am yawning, so good night, all.",
      "Hope no mosquitoes bother you tonight.",
      "Lights off, good night, everybody!",
      "Sweet dreams, I will tell you mine tomorrow.",
      "Good night, I am going to sleep right now.",
      "It is nice and cool tonight, sleep well.",
      "Sleep deeply until the morning, all.",
    ],
  },
};
