// Status notes that match the mood a companion has for the whole day, shown now and then under its name.
// Moods: happy, grumpy, sleepy, excited, dreamy, lazy. Gender neutral first person.
export default {
  vi: {
    happy: [
      "tìm được tờ năm chục trong túi áo cũ, vui cả ngày",
      "hôm nay trà sữa ngon hơn mọi hôm",
      "đèn xanh liên tục từ nhà tới chỗ làm, quá đã",
      "mèo hàng xóm cho mình vuốt đầu, sướng ghê",
      "nấu cơm lần đầu không bị cháy, tự vỗ tay",
      "vừa nghe lại bài yêu thích, tâm trạng lên hẳn",
      "gió mát, nắng nhẹ, mình thấy đời ổn áp",
      "ai đó khen áo mình đẹp, bay lơ lửng luôn",
      "bánh mì còn nóng hổi, thế là đủ vui",
      "tui vừa cười một mình vì nhớ ra chuyện cũ",
      "cô bán chè nhớ mặt mình, cảm động nhẹ",
      "mưa tạnh đúng lúc mình ra đường, may ghê",
      "hôm nay mọi thứ cứ trôi, mình cũng trôi theo",
      "trong tủ lạnh còn đúng món mình thích",
      "gỡ xong một việc tồn đọng, nhẹ cả người",
      "mở điện thoại ra toàn tin vui, lạ thật",
    ],
    grumpy: [
      "chưa cà phê thì đừng nói chuyện với mình",
      "ai để dép sai chỗ nữa vậy, mình thấy hết rồi",
      "wifi chập chờn đúng lúc mình cần, cảm ơn nha",
      "mình không cáu, chỉ là hơi cạn kiên nhẫn thôi",
      "tin nhắn đã xem mà không trả lời, mình nhớ đó",
      "ly trà đá ít đá quá, tui buồn ra mặt",
      "kẹt xe đúng ngày mình ra khỏi nhà sớm",
      "ai ăn mất miếng bánh cuối của mình vậy?",
      "mình đang rất bình tĩnh, nhìn mặt mình mà xem",
      "đừng hỏi mình ổn không, câu trả lời là chưa",
      "giặt đồ xong trời đổ mưa, quá hay luôn",
      "tai nghe rối thành cục, sáng đã mất kiên nhẫn",
      "pin điện thoại còn một phần trăm, mình cũng vậy",
      "hôm nay tui hơi khó ở, đi nhẹ nói khẽ nha",
      "ai bấm còi inh ỏi ngoài đường vậy, mình đang nghĩ mà",
      "cà phê nguội mất rồi, tâm trạng cũng nguội theo",
    ],
    sleepy: [
      "mắt đang mở nhưng hồn vẫn nằm trên giường",
      "cho mình năm phút nữa thôi, lần thứ mười",
      "ngáp liên tục, chắc cả phòng nghe thấy rồi",
      "cái chăn hôm nay níu mình ghê lắm",
      "đêm qua mình ngủ, mà chắc chưa đủ",
      "gật gù từ sáng, cà phê cũng bó tay",
      "mí mắt nặng như đeo tạ, đừng ai hỏi",
      "mình cần một giấc ngủ trưa dài như phim bộ",
      "gối ơi chờ mình về, đừng đi đâu nhé",
      "nghe tiếng mưa là buồn ngủ liền, vô duyên ghê",
      "đang ngủ gật mà vẫn cố tỏ ra tỉnh táo",
      "mình đếm cừu tới con thứ ba trăm vẫn chưa ngủ",
      "ngáp một cái là hết nửa pin",
      "chỉ muốn cuộn tròn trong chăn tới thứ hai",
      "tui đang chạy chế độ tiết kiệm năng lượng",
    ],
    excited: [
      "quán trà sữa gần nhà có món mới, mình muốn đi ngay",
      "vừa mua được đôi tất có hình con vịt, vui quá trời",
      "tối nay có tập mới của bộ phim mình mê!",
      "mình vừa thấy cầu vồng, ai ra xem đi",
      "gói hàng đang trên đường tới, sốt ruột ghê",
      "hôm nay mình nhớ mang ô và trời mưa thật, thắng!",
      "đồ ăn vặt giảm giá, tay mình run run",
      "vừa đọc được chuyện cười hay, phải kể cho cả nhà",
      "mai đi chơi mà tối nay mình không ngủ nổi",
      "đổi hình nền mới, mình thấy mình ngầu hẳn",
      "tui tìm được quán phở ngon, mình sẽ không kể ai đâu",
      "sắp xếp xong góc bàn, mình thấy đời mới mẻ",
      "ôi mình đoán đúng bài hát tiếp theo luôn!",
      "kem dừa vừa mở bán lại, mình chạy liền",
      "nghe nói thứ sáu có mưa sao băng, mình sẵn sàng",
    ],
    dreamy: [
      "đang ngắm mây hình con cá voi, ai thấy giống không?",
      "bài nhạc này làm mình bay đâu đó rất xa",
      "mình đang nghĩ về một căn nhà nhỏ bên biển",
      "ngồi bên cửa sổ, nhìn mưa rơi cả buổi",
      "mơ giữa ban ngày là kỹ năng của mình",
      "hoàng hôn hôm nay màu cam hồng, đẹp muốn khóc",
      "cầm cốc trà, nghe nhạc nhẹ, hồn lang thang",
      "mình vừa tưởng tượng mình là phi hành gia",
      "gió thổi nhẹ làm mình nhớ một mùa hè xa lắm",
      "đang viết dở một câu chuyện trong đầu",
      "ngẩng lên thấy trăng tròn, quên luôn việc đang làm",
      "mình thả hồn theo tiếng đàn guitar ngoài phố",
      "mây hôm nay trôi chậm, mình cũng chậm theo",
      "nghe tiếng sóng trong đầu mà đâu có biển",
      "tui đang lạc trong một bài hát cũ",
    ],
    lazy: [
      "hôm nay mình nằm im chuyên nghiệp",
      "đặt đồ ăn giao tận nơi, đứng dậy là thua",
      "ghế sofa ôm mình chặt quá, không đi đâu được",
      "việc để mai, mai lại để mốt, ổn áp",
      "mình lười tới mức lười suy nghĩ luôn",
      "remote ở xa quá, thôi xem tiếp cái đang chiếu",
      "chỉ làm đúng một việc hôm nay, là thở",
      "tui xem lại phim cũ lần thứ bảy, không hối hận",
      "đồ chưa giặt chất thành núi, mình nhìn nó thôi",
      "đi lấy ly nước cũng thấy như leo núi",
      "hôm nay kế hoạch là không có kế hoạch",
      "mình nằm dài và gọi đó là nghỉ ngơi có chiến lược",
      "cuộn trong chăn, lướt điện thoại, ăn snack, lặp lại",
      "tui chưa ra khỏi nhà từ hôm qua, thấy ổn",
      "nấu ăn ư? Mình có số điện thoại quán quen rồi",
    ],
  },
  en: {
    happy: [
      "found a twenty in my old jacket, whole day made",
      "the milk tea today is better than usual",
      "caught every green light on the way, unreal",
      "the neighbor's cat let me pet it, I am glowing",
      "cooked rice without burning it, applauding myself",
      "just heard my favorite song and my mood jumped",
      "soft sun and cool breeze, life feels fine",
      "someone liked my sweater, I am floating",
      "warm fresh bread is enough to be happy",
      "laughed alone remembering an old joke",
      "the snack lady remembered my order, feeling loved",
      "the rain stopped right when I stepped outside",
      "today everything flows and I flow with it",
      "my favorite leftovers are still in the fridge",
      "finished one lingering task, feeling light",
      "opened my phone and it was all good news",
    ],
    grumpy: [
      "do not talk to me before coffee, thanks",
      "someone left the cabinet open again, I saw",
      "wifi dropped right when I needed it, lovely",
      "I am not annoyed, just low on patience",
      "left on read and I remember everything",
      "my iced tea has barely any ice, I am sad",
      "traffic jam on the one day I left early",
      "who ate my last cookie? I just want answers",
      "I am perfectly calm, look at my face",
      "do not ask if I am okay, the answer is not yet",
      "laundry is out and now it rains, wonderful",
      "tangled earphones this early, my patience is gone",
      "phone is at one percent, so am I",
      "a little cranky today, please walk softly",
      "the horn outside is loud, I was thinking",
      "coffee went cold and my mood followed",
    ],
    sleepy: [
      "eyes are open but my soul is still in bed",
      "five more minutes, said ten times already",
      "yawning nonstop, the whole room can hear it",
      "my blanket has a strong grip on me today",
      "I did sleep last night, just not enough",
      "nodding off since morning, coffee gave up",
      "eyelids feel like they are lifting weights",
      "I need a nap as long as a drama series",
      "pillow, wait for me, do not go anywhere",
      "rain sounds make me sleepy, rude of them",
      "dozing off while pretending to be awake",
      "counted three hundred sheep and still awake",
      "one yawn and half my battery is gone",
      "just want to stay curled up till Monday",
      "running on power saving mode today",
    ],
    excited: [
      "the milk tea shop nearby has a new flavor, going now",
      "bought socks with little ducks on them, so happy",
      "new episode of my show tonight, can not wait!",
      "just saw a rainbow, everyone go look",
      "my package is on its way, I am pacing",
      "remembered my umbrella and it rained, I win!",
      "snacks are on sale and my hands are shaking",
      "read a great joke, I have to tell everybody",
      "trip tomorrow so I will not sleep tonight",
      "changed my wallpaper and now I feel cool",
      "found a great noodle shop, telling absolutely no one",
      "tidied my desk corner and life feels new",
      "guessed the next song right, I am a genius!",
      "coconut ice cream is back in stock, running",
      "meteor shower on Friday, I am so ready",
    ],
    dreamy: [
      "watching a cloud shaped like a whale, anyone else?",
      "this song carried me somewhere far away",
      "thinking about a tiny house by the sea",
      "sat by the window watching the rain for ages",
      "daydreaming is my best skill",
      "pink orange sunset today, almost cried",
      "cup of tea, soft music, mind wandering off",
      "just imagined myself as an astronaut",
      "the breeze reminded me of a faraway summer",
      "writing a story in my head, still unfinished",
      "looked up, saw a full moon, forgot everything",
      "drifting along with a guitar from down the street",
      "slow clouds today, so I am slow too",
      "hearing waves in my head with no sea nearby",
      "lost inside an old song",
    ],
    lazy: [
      "lying still today, very professionally",
      "ordered delivery, standing up means losing",
      "the couch is hugging me too tight to leave",
      "tomorrow is the new today, again",
      "so lazy I am too lazy to think about it",
      "remote is too far, watching whatever is on",
      "only one task today, and it is breathing",
      "rewatching an old show for the seventh time",
      "laundry is a mountain and I am just looking",
      "getting a glass of water feels like a hike",
      "my plan today is having no plan",
      "lying flat and calling it strategic rest",
      "blanket, phone, snacks, repeat",
      "have not left home since yesterday, feeling fine",
      "cooking? I have the delivery number saved",
    ],
  },
};
