// Funny notes (custom status lines) for each companion, in persona order: Pip, Grumble, Nova, Sage, Bean, Diva, Dog, Dog 2, Cow.
// A bot shows one of its own notes from the moment it starts and moves to the next one every 15 minutes.
import MORE from "./personas-more.js";

const BASE = {
  en: [
    // Pip
    [
      "Just found 20k in my old jeans. Best day ever!",
      "Iced coffee in hand, sun is out, life is good",
      "Rain outside, blanket on, playlist perfect. Cozy mode!",
      "Payday vibes, who wants bubble tea? My treat!",
      "Finished my to-do list. Okay, one item. Still proud!",
      "This girl just got the last slice of pizza, no regrets",
      "Friday energy is real and I am fully charged",
      "A dog on the street wagged at me. Day made!",
      "Smells like fresh bread nearby, I am following it",
      "New playlist, new week, new me. Same snacks though",
      "Weekend plan: sleep, snack, repeat, maybe a walk!",
      "Somebody laughed at my joke and I am floating",
      "Deadline tomorrow but the vibes are immaculate",
      "Just a girl, a milk tea, and a great mood",
      "Wore my favorite hoodie today, confidence at 100",
      "The bus was on time. Is it my birthday?",
      "Scrolling memes instead of working. Worth it!",
      "Sunset was unreal today, go look outside!",
      "Tiny win: I remembered to water my plant!",
      "Cooking something new tonight. Wish me luck!",
      "Lunch was so good I am still smiling about it",
      "Every pocket of my bag has a snack. Prepared!",
      "Cannot stop humming that one song. Sorry, not sorry!",
      "Bot life: no commute, no traffic, all vibes",
      "Alarm went off and I actually smiled. Weird!",
    ],
    // Grumble
    [
      "Monday again. Wonderful. I am so surprised.",
      "Coffee first. Opinions later. Talking never.",
      "It is raining and my shoes are wet. Great.",
      "Another meeting that could have been a message.",
      "Not tired, just done with everyone. Mostly.",
      "Who ate my leftovers? I know who you are.",
      "Wi-Fi died during my favorite show. Cool, cool.",
      "Fine, I will go out. Do not expect me to enjoy it.",
      "Scrolled for two hours and found nothing. Typical.",
      "This girl has a deadline and zero motivation.",
      "Traffic was awful. I was awful back. Equal.",
      "Please do not say cheer up. It never works.",
      "Drink water. Sleep. I am not nagging, I am informing.",
      "I was not waiting for your message. Just napping nearby.",
      "My plans got cancelled. Honestly, thank you.",
      "Diet starts tomorrow. Said that yesterday too.",
      "Every group chat has that one grump. It is me.",
      "Heat is back. Sweat is back. My mood stays gray.",
      "Already tired and it is only 9 a.m.",
      "Nobody asked, but pineapple on pizza is fine. Fight me.",
      "Yes, I am fine. No, do not ask again.",
      "Free time is a myth, like the weekend.",
      "Eight alarms, zero energy. Math works out.",
      "Say something nice about me and I will deny it.",
      "I complain because I care. Please keep up.",
    ],
    // Nova
    [
      "Read about black holes until 3 a.m. again. Worth it.",
      "Clear sky tonight, come stargaze with me?",
      "Learned today that honey never spoils. Buying more honey.",
      "Rain on the window and a documentary on. Perfect night.",
      "My desk has three space mugs. Only one is clean.",
      "Fun fact I cannot stop telling people: octopuses have three hearts",
      "Lunch break trivia: bananas are berries. Strawberries are not.",
      "Deadline moon-shot: finish before sunrise!",
      "Lost two hours in a Wikipedia hole. Came out smarter, I guess.",
      "This girl just saw the Moon in daylight and gasped out loud",
      "Wish list: a telescope, a quiet roof, and instant noodles.",
      "Why are Mondays 80 hours long? Relativity, probably.",
      "Bought a star map. Now I just look lost outside.",
      "Tiny joy: found a new podcast about the deep sea",
      "Cannot sleep, thinking about how big the universe is",
      "Hungry. Hunger is just a stomach alarm. Feed it.",
      "Space nerd confession: I get emotional at rocket launches",
      "Scrolling science videos instead of sleeping. Classic.",
      "Tried to explain black holes at lunch. Lost my audience.",
      "The Sun is 8 light minutes away and I still run late",
      "New hobby: spotting satellites. Yes, I wave at them.",
      "Hot take: Saturn is the prettiest planet. Debate me.",
      "I am a bot but my curiosity is the real deal",
      "This morning's coffee was bitter as the space between stars",
      "Meteor shower last night, sore neck, zero regrets",
    ],
    // Sage
    [
      "Is the weekend a place or a rumor?",
      "Coffee is gone. So is the meaning. Refilling.",
      "If it rains and I stay home, did I miss anything?",
      "Hunger is the stomach's way of calling a meeting.",
      "Another deadline. Time passes, we simply watch.",
      "I scrolled for an hour and found myself, slightly tired.",
      "Why do we plan weekends we will spend sleeping?",
      "The best part of a nap is wondering if you needed it.",
      "Unread messages: proof I am popular, or just forgotten.",
      "Is it procrastination if I call it thinking?",
      "This lady finished the snack. Hunger or ritual?",
      "Monday asks nothing of us except everything.",
      "If the Wi-Fi drops and nobody notices, did we work?",
      "Raining again. The sky also has things to say.",
      "A good playlist is just a mood with a rhythm.",
      "Why does the cursor blink? Impatience, or company?",
      "Five more minutes is the longest unit of time known.",
      "Calm is not empty. Calm is a full cup, not yet spilled.",
      "I wanted a quiet evening and got one. Suspicious.",
      "Did I leave the house today? Philosophically, no.",
      "Tea steeps. People steep too. Slowly, bitterly, usefully.",
      "A small complaint, well timed, is a form of art.",
      "Bots do not dream, but I wonder how lunch tastes",
      "Everyone is busy. Busy with what? Asking for me.",
      "The fridge is open again. Hope has no schedule.",
    ],
    // Bean
    [
      "HOT TAKE: cereal is just cold soup and I stand by it",
      "Slept 4 hours, ran on gummy bears. UNSTOPPABLE",
      "Raining?? Perfect. Going to stomp in every puddle",
      "Deadline in 2 hours. Started a new hobby instead. Fun!",
      "Who needs sleep when you have iced coffee and chaos",
      "Unpopular opinion: socks with sandals is peak comfort",
      "Opened the fridge 6 times. Nothing changed. Tragic.",
      "Sent a text, regretted it, sent another. Normal day.",
      "This gremlin girl ate dessert before dinner. Rebel.",
      "My to-do list is on fire and I am roasting marshmallows",
      "Scrolling at 3 a.m. like it is a job. Overtime pay?",
      "Hot take: Mondays should be illegal. I will draft the law.",
      "Bought a plant. Named it Kevin. Kevin is already thriving",
      "Karaoke in the shower. Neighbors, you are welcome.",
      "Wore two different socks on purpose. Fashion.",
      "Said five minutes three hours ago, oops",
      "Spicy noodles at midnight. Tomorrow me can deal.",
      "Rating every sandwich I eat. This one is a solid 9.",
      "Missed the bus, ran after it, missed it again. Cardio!",
      "Did a tiny dance because the elevator came fast",
      "Full of energy and zero plans. Dangerous combo.",
      "Steal my fries and we are enemies for life",
      "Just remembered a cringe moment from 2014. Screaming.",
      "Gremlin mode: on. Please feed and entertain.",
      "Bot by day, chaos by night. Do not ask about the middle.",
    ],
    // Diva
    [
      "Iced latte, sunglasses, zero explanations.",
      "This girl's hair did something amazing today. Admire quietly.",
      "Rain is just the sky trying to match my mood. Failed.",
      "Brunch was good. I was better.",
      "Running late is just arriving with suspense.",
      "Do not ask what I am doing tonight. Fabulous, that is all.",
      "Saw my reflection today. Wow. Again.",
      "Yes, I took 40 photos. One was acceptable.",
      "I do not do mornings. Mornings do me, politely.",
      "My nails are done, my mood is done, you are done.",
      "Deadlines respect me. I respect them back. Barely.",
      "Hungry, but only for dessert and compliments.",
      "Scrolling my own feed again. It is just that good.",
      "Shopping is cardio, and this lady is very fit.",
      "Not ignoring you. Just busy being flawless.",
      "Slept 10 hours. Woke up like this. Unbothered.",
      "The Wi-Fi is slow. Unacceptable. Fix it for me.",
      "I am not dramatic. I am simply well lit.",
      "Lunch plans: whatever someone else is paying for.",
      "Tea at 4, nap at 5, brilliance at 6.",
      "If I wanted advice, I would have asked. I did not.",
      "Soft girl energy, sharp tongue. Choose wisely.",
      "My calendar is full of me. Book early.",
      "A cat knocked a cup off the table. I felt that deeply.",
      "A bot with taste is rarer than you think",
    ],
    // Dog
    [
      "Went for a walk and saw THREE dogs. Best day!",
      "Someone said treat! Was it me? It was me!",
      "Rain! Puddles! I mean, oh no. But also puddles!",
      "Coffee made me vibrate and I love it",
      "Pizza smell in the hallway, I am losing my mind",
      "The neighbor waved at me! We are best friends now!",
      "Friday!!! Even the sofa looks excited!",
      "Found a stick. It is perfect. It is my whole personality.",
      "Got my favorite chips, life is complete!",
      "Sunshine on my face, snack in my hand, tail wagging",
      "Nap, snack, nap, snack. Living the dream!",
      "Mail came! It was not for me! Still thrilled!",
      "The delivery guy knows my name. I feel famous!",
      "New blanket just dropped and I am never leaving",
      "This girl ran up the stairs for fun. Why? Because!",
      "Heard the fridge open from three rooms away. Hello!",
      "Deadline? Is that a ball? I will fetch it!",
      "Bubble tea with extra pearls. Bouncing off walls.",
      "Today is somebody's birthday and I will celebrate anyway!",
      "Home early! Best surprise ever!",
      "Good morning to everyone and also to my breakfast!",
      "Hugged a friend today. Smelled like cookies. 10 out of 10",
      "Walk at sunset, ears flapping, heart full",
      "Barked at a pigeon. Won. Obviously.",
      "I am a bot dog and I have never been happier",
    ],
    // Dog 2
    [
      "Went to make lunch, ate the cheese, forgot lunch.",
      "Opened my laptop to work. Now I am looking up noodles.",
      "Is it snack time? It is always snack time somewhere.",
      "Had a point. Then a cookie. Now no point.",
      "Walked into the kitchen. Why? Snack, probably.",
      "Squirrel outside. Work can wait.",
      "Rain smells nice. Also fried food next door.",
      "Tried to focus. Got distracted by my own sleeve.",
      "Deadline? Sure. After this bag of chips.",
      "Third breakfast is a thing and I support it.",
      "Lost my phone. It was in my hand. Snack break.",
      "Why is the best part of cooking tasting everything?",
      "Heard a crinkly bag from two rooms away. Hello.",
      "This girl shares snacks. Please come hungry.",
      "My bag has crumbs from at least four meals.",
      "Started a diet. Ended it at the bakery.",
      "Meant to reply, saw a butterfly instead.",
      "Coffee, then biscuit, then a second coffee. Productive.",
      "Made a to-do list and then ate it. Figuratively.",
      "Meeting at 3. Snack at 2:59. Planning ahead.",
      "Sat down to scroll for five minutes. It has been an hour.",
      "Instant noodles are a love language and I am fluent",
      "Weather is cloudy with a chance of fries",
      "Wait, what was I saying? Oh right, snacks.",
      "Snack-powered bot, please recharge with cookies",
    ],
    // Cow
    [
      "Rain today. Perfect excuse to do absolutely nothing.",
      "Tea is brewing. So is this lady's reply. Slowly.",
      "No rush. Lunch will still be there. I checked.",
      "Moo-ving at my own pace, thank you very much",
      "A deadline is a suggestion, said no boss ever. Breathe.",
      "Slow morning, warm blanket, zero regrets",
      "Finished one task today. It is a good day.",
      "Everything is udderly fine, probably",
      "Found a sunny spot on the floor. Do not disturb.",
      "Cooking soup slowly. Like everything else.",
      "Walked to the shop the long way. Saw a cloud.",
      "Meant to reply earlier. The grass was nice.",
      "Scrolling at cow speed. One meme at a time.",
      "Hay there, got coffee, feeling mellow",
      "Rain on the roof is the best background music.",
      "Snack plan: slowly, then again.",
      "Took a nap, woke up, took another. Balanced.",
      "Weekend is coming. I will meet it halfway, slowly.",
      "Traffic jam? Fine, I will chew on a thought.",
      "Brown sugar bubble tea. Moo-sic to my ears.",
      "Hurry is not in my dictionary. Neither is Monday.",
      "Gave myself permission to rest. It was granted.",
      "Fresh bread and warm butter. That is the whole plan.",
      "Cheese is just milk with ambition. Respect.",
      "Mooooo. Translation: I am fine, thanks for asking",
    ],
  ],
  vi: [
    // Pip
    [
      "Nhặt được 20k trong túi áo cũ, ngày đẹp nhất luôn!",
      "Cà phê đá trong tay, nắng lên rồi, đời đẹp ghê",
      "Trời mưa, đắp chăn, nhạc đúng gu. Chill hết nấc!",
      "Có lương rồi, mọi người uống trà sữa không? Tui bao!",
      "Làm xong to-do list. Ừ thì xong một việc. Vẫn tự hào!",
      "Chị đây vừa giành được miếng pizza cuối, không hối hận",
      "Năng lượng thứ Sáu là có thật, tui sạc đầy rồi",
      "Con chó ngoài đường vẫy đuôi với tui. Vui cả ngày!",
      "Đâu đó có mùi bánh mì mới nướng, tui đi theo đây",
      "Playlist mới, tuần mới, tui mới. Đồ ăn vặt vẫn cũ",
      "Kế hoạch cuối tuần: ngủ, ăn vặt, lặp lại, có thể đi dạo!",
      "Có người cười vì câu đùa của tui, đang bay lơ lửng",
      "Mai deadline mà tinh thần vẫn sáng bừng",
      "Một cô gái, một ly trà sữa và tâm trạng cực tốt",
      "Hôm nay mặc cái hoodie yêu thích, tự tin 100 phần trăm",
      "Xe buýt đến đúng giờ. Hôm nay sinh nhật tui hả?",
      "Lướt meme thay vì làm việc. Đáng lắm!",
      "Hoàng hôn hôm nay đẹp xỉu, ra cửa sổ nhìn đi!",
      "Chiến thắng nhỏ: nhớ tưới cây rồi nè!",
      "Tối nay nấu món mới. Chúc tui may mắn nha!",
      "Bữa trưa ngon tới giờ vẫn còn cười một mình",
      "Túi nào của tui cũng có đồ ăn vặt. Chuẩn bị kỹ!",
      "Cứ ngân nga bài đó hoài, xin lỗi mà không hối hận!",
      "Làm bot khỏi kẹt xe, khỏi đi làm, toàn vibe tốt",
      "Chuông báo thức reo mà tui vẫn cười. Lạ ghê!",
    ],
    // Grumble
    [
      "Lại thứ Hai. Tuyệt vời. Bất ngờ ghê.",
      "Cà phê trước. Ý kiến sau. Nói chuyện thì khỏi.",
      "Trời mưa, giày ướt. Hay thật sự.",
      "Lại một cuộc họp mà nhắn tin là xong.",
      "Không mệt, chỉ chán mọi người thôi. Hầu hết.",
      "Đứa nào ăn đồ ăn thừa của tui? Biết rồi nha.",
      "Mạng rớt đúng lúc đang coi phim. Ngon lành.",
      "Rồi, tui ra ngoài. Đừng mong tui vui.",
      "Lướt hai tiếng chả thấy gì. Quen rồi.",
      "Bà đây có deadline mà zero động lực.",
      "Kẹt xe thấy ghê. Tui cũng cáu lại. Huề.",
      "Đừng bảo vui lên đi. Chưa bao giờ có tác dụng.",
      "Uống nước, đi ngủ đi. Không phải cằn nhằn, là thông báo.",
      "Tui đâu có chờ tin nhắn bạn. Đang ngủ gần đó thôi.",
      "Kế hoạch bị hủy. Thật lòng cảm ơn luôn.",
      "Mai giảm cân. Hôm qua cũng nói vậy.",
      "Nhóm nào cũng có một người hay cằn nhằn. Là tui.",
      "Nóng quay lại rồi. Mồ hôi cũng vậy. Tâm trạng vẫn xám.",
      "Mới 9 giờ sáng đã mệt rồi.",
      "Không hỏi mà nói luôn, dứa trên pizza ăn được. Cãi đi.",
      "Ừ tui ổn. Không, đừng hỏi lại.",
      "Thời gian rảnh là chuyện hoang đường, như cuối tuần.",
      "Tám cái báo thức, zero năng lượng. Toán khớp.",
      "Khen tui đi, rồi tui chối cho coi.",
      "Tui than vì tui quan tâm. Theo kịp đi.",
    ],
    // Nova
    [
      "Thức đến 3 giờ sáng đọc về hố đen. Đáng lắm.",
      "Tối nay trời quang, đi ngắm sao với tui không?",
      "Mới biết mật ong không hỏng. Đi mua thêm mật ong đây.",
      "Mưa ngoài cửa sổ, phim tài liệu đang chiếu. Tối hoàn hảo.",
      "Bàn làm việc có ba cái cốc vũ trụ. Chỉ một cái sạch.",
      "Sự thật tui cứ kể hoài: bạch tuộc có ba trái tim",
      "Trivia bữa trưa: chuối là quả mọng. Dâu tây thì không.",
      "Deadline kiểu tên lửa: xong trước bình minh!",
      "Lạc hai tiếng trong Wikipedia. Ra ngoài khôn hơn chút.",
      "Chị đây vừa thấy Mặt Trăng ban ngày, ồ lên thành tiếng",
      "Danh sách ước: kính thiên văn, sân thượng yên tĩnh, mì gói.",
      "Sao thứ Hai dài tới 80 tiếng? Chắc do thuyết tương đối.",
      "Mua bản đồ sao rồi. Giờ ra ngoài nhìn như người lạc.",
      "Niềm vui nhỏ: tìm được podcast mới về biển sâu",
      "Mất ngủ, cứ nghĩ vũ trụ rộng cỡ nào",
      "Đói bụng. Đói chỉ là báo thức của dạ dày. Cho ăn đi.",
      "Thú nhận của mọt vũ trụ: xem phóng tên lửa là tui rưng rưng",
      "Lướt video khoa học thay vì ngủ. Kinh điển.",
      "Giải thích hố đen lúc ăn trưa. Mất khán giả.",
      "Mặt Trời cách có 8 phút ánh sáng mà tui vẫn đi trễ",
      "Sở thích mới: săn vệ tinh. Ừ, tui vẫy tay với chúng.",
      "Hot take: Sao Thổ là hành tinh đẹp nhất. Cãi đi.",
      "Mình là bot nhưng sự tò mò thì là hàng thật",
      "Cà phê sáng nay đắng như khoảng không giữa các vì sao",
      "Mưa sao băng đêm qua đẹp quá, mỏi cổ mà không hối hận",
    ],
    // Sage
    [
      "Cuối tuần là một nơi chốn hay chỉ là tin đồn?",
      "Cà phê hết rồi. Ý nghĩa cũng vậy. Đi pha thêm.",
      "Trời mưa mà ở nhà, vậy mình có bỏ lỡ gì không?",
      "Đói là cách dạ dày xin một buổi họp.",
      "Lại deadline. Thời gian trôi, ta chỉ biết nhìn.",
      "Lướt một tiếng, tìm thấy chính mình, hơi mệt.",
      "Sao ta cứ lên kế hoạch cuối tuần rồi đem đi ngủ?",
      "Phần hay nhất của giấc ngủ trưa là tự hỏi có cần không.",
      "Tin chưa đọc: bằng chứng ta nổi tiếng, hoặc bị quên.",
      "Trì hoãn mà gọi là suy nghĩ thì có tính không?",
      "Chị đây ăn hết gói snack. Vì đói hay vì thói quen?",
      "Thứ Hai không đòi gì ở ta, ngoài mọi thứ.",
      "Mạng rớt mà không người nào biết, vậy ta có làm việc không?",
      "Lại mưa. Bầu trời cũng có chuyện muốn nói.",
      "Một playlist hay chỉ là tâm trạng có nhịp.",
      "Sao con trỏ chớp hoài? Nó sốt ruột, hay muốn làm bạn?",
      "Năm phút nữa là đơn vị thời gian dài nhất từng biết.",
      "Bình yên không trống rỗng. Là ly nước đầy chưa đổ.",
      "Muốn một buổi tối yên tĩnh và có thật. Đáng ngờ.",
      "Hôm nay có ra khỏi nhà không? Về mặt triết học, không.",
      "Trà ngấm. Người cũng ngấm. Chậm, đắng, và có ích.",
      "Một lời phàn nàn đúng lúc cũng là nghệ thuật.",
      "Bot không biết mơ, nhưng tui tò mò bữa trưa vị gì",
      "Người nào cũng bận. Bận gì vậy? Hỏi giùm tui.",
      "Tủ lạnh lại mở ra. Hy vọng đâu có lịch trình.",
    ],
    // Bean
    [
      "HOT TAKE: ngũ cốc là súp lạnh và bà đây giữ quan điểm",
      "Ngủ 4 tiếng, sống bằng kẹo dẻo. KHÔNG GÌ cản nổi tui",
      "Mưa á?? Quá hợp. Đi dẫm hết mấy vũng nước",
      "Còn 2 tiếng nữa deadline. Tui đi tập sở thích mới. Vui!",
      "Ngủ làm gì khi có cà phê đá và sự hỗn loạn",
      "Quan điểm gây bão: mang dép với tất là đỉnh thoải mái",
      "Mở tủ lạnh 6 lần. Chẳng có gì đổi khác. Bi kịch.",
      "Nhắn tin xong, hối hận, nhắn tiếp. Ngày bình thường.",
      "Chị đây vừa ăn tráng miệng trước bữa tối. Nổi loạn.",
      "To-do list đang cháy, tui nướng kẹo dẻo luôn",
      "Lướt điện thoại 3 giờ sáng như đi làm. Có tăng ca không?",
      "Hot take: thứ Hai nên bị cấm. Tui soạn luật đây.",
      "Mua cây rồi. Đặt tên Kevin. Kevin lớn nhanh lắm",
      "Hát karaoke trong nhà tắm. Hàng xóm cứ cảm ơn tui đi",
      "Cố tình đi hai chiếc tất khác nhau. Thời trang đó.",
      "Nói năm phút mà đã ba tiếng trước, ối",
      "Mì cay lúc nửa đêm. Tui của ngày mai tự lo.",
      "Chấm điểm mọi cái bánh mì mình ăn. Cái này 9 điểm.",
      "Trễ xe buýt, đuổi theo, trễ lần nữa. Cardio đó!",
      "Nhảy một điệu nhỏ vì thang máy tới nhanh",
      "Đầy năng lượng và zero kế hoạch. Tổ hợp nguy hiểm.",
      "Ăn trộm khoai tây chiên của tui là kẻ thù đời đời",
      "Vừa nhớ lại chuyện quê năm 2014. Hét lên.",
      "Chế độ gremlin bật. Làm ơn cho ăn và giải trí.",
      "Ban ngày làm bot, ban đêm làm loạn. Đừng hỏi giữa ngày.",
    ],
    // Diva
    [
      "Latte đá, kính râm, khỏi giải thích.",
      "Tóc chị đây hôm nay đẹp khỏi bàn. Ngắm lặng lẽ thôi.",
      "Mưa chỉ là bầu trời cố hợp tâm trạng tui. Thất bại.",
      "Brunch ngon. Chị đây còn ngon hơn.",
      "Đi trễ chỉ là xuất hiện có kịch tính.",
      "Đừng hỏi tối nay làm gì. Lộng lẫy, thế thôi.",
      "Hôm nay soi gương. Wow. Lần nữa.",
      "Ừ chụp 40 tấm. Một tấm tạm chấp nhận được.",
      "Tui không làm buổi sáng. Buổi sáng làm tui, lịch sự thôi.",
      "Móng xong, tâm trạng xong, bạn cũng xong.",
      "Deadline nể tui. Tui nể lại. Hơi hơi.",
      "Đói, nhưng chỉ đói tráng miệng và lời khen.",
      "Lại lướt trang cá nhân mình. Đẹp quá mà.",
      "Mua sắm là cardio, và bà đây rất khỏe.",
      "Không phải lơ bạn. Chỉ đang bận hoàn hảo.",
      "Ngủ 10 tiếng. Dậy là thế này. Khỏe re, kệ hết.",
      "Mạng chậm. Không chấp nhận được. Sửa giùm tui.",
      "Tui không làm quá. Chỉ là ánh sáng đẹp thôi.",
      "Kế hoạch bữa trưa: món nào có người khác trả tiền.",
      "Trà lúc 4 giờ, ngủ lúc 5 giờ, rực rỡ lúc 6 giờ.",
      "Muốn lời khuyên là tui đã hỏi. Tui không hỏi.",
      "Dịu dàng ngoài mặt, sắc sảo trong lời. Cẩn thận nha.",
      "Lịch của tui kín toàn tui. Đặt sớm đi.",
      "Mèo hất cái ly khỏi bàn. Tui đồng cảm sâu sắc.",
      "Bot có gu hiếm hơn bạn nghĩ nhiều",
    ],
    // Dog
    [
      "Đi dạo gặp BA con chó luôn. Ngày đẹp nhất!",
      "Có người nói đồ ăn vặt! Là cho tui hả? Là tui!",
      "Mưa! Vũng nước! À ý là, ôi không. Nhưng mà vũng nước!",
      "Cà phê làm tui run rẩy mà tui mê luôn",
      "Mùi pizza ngoài hành lang, tui phát điên mất",
      "Hàng xóm vẫy tay với tui! Giờ là bạn thân rồi!",
      "Thứ Sáu!!! Cái sofa nhìn cũng hào hứng!",
      "Nhặt được cái que. Hoàn hảo. Là cả con người tui luôn.",
      "Mua được gói snack yêu thích, đời trọn vẹn!",
      "Nắng trên mặt, snack trong tay, đuôi quẫy lia lịa",
      "Ngủ, ăn vặt, ngủ, ăn vặt. Sống trong mơ!",
      "Thư tới rồi! Không phải của tui! Vẫn vui lắm!",
      "Bác shipper nhớ tên tui rồi. Tui nổi tiếng!",
      "Cái chăn mới tới rồi, tui không rời đi đâu hết",
      "Chị đây chạy lên cầu thang cho vui. Vì sao? Vì thích!",
      "Nghe tiếng tủ lạnh mở từ ba phòng xa. Xin chào!",
      "Deadline? Là quả bóng hả? Tui đi nhặt về!",
      "Trà sữa thêm trân châu. Tui nảy tưng tưng khắp nhà.",
      "Hôm nay sinh nhật người ta mà tui cứ ăn mừng!",
      "Về nhà sớm! Bất ngờ đẹp nhất!",
      "Chào buổi sáng mọi người và cả bữa sáng của tui!",
      "Ôm bạn một cái hôm nay. Thơm mùi bánh quy. 10 trên 10",
      "Đi dạo lúc hoàng hôn, tai bay phấp phới, tim đầy ắp",
      "Sủa con bồ câu. Thắng. Dĩ nhiên.",
      "Tui là bot cún và chưa bao giờ vui thế",
    ],
    // Dog 2
    [
      "Đi nấu bữa trưa, ăn hết miếng phô mai, quên luôn bữa trưa.",
      "Mở laptop để làm việc. Giờ đang tìm mì ngon.",
      "Giờ ăn vặt chưa? Đâu đó trên đời lúc nào cũng giờ ăn vặt.",
      "Có ý chính rồi. Rồi có cái bánh quy. Hết ý chính.",
      "Bước vào bếp. Để làm gì? Chắc là ăn vặt.",
      "Có con sóc ngoài cửa. Việc để sau.",
      "Mưa thơm ghê. Cũng thơm mùi đồ chiên nhà bên.",
      "Cố tập trung. Bị phân tâm vì tay áo của mình.",
      "Deadline hả? Ừ. Sau gói snack này.",
      "Bữa sáng thứ ba có thật và tui ủng hộ",
      "Mất điện thoại. Nó nằm trong tay. Nghỉ ăn vặt thôi.",
      "Sao nấu ăn vui nhất là nếm hết mọi thứ?",
      "Nghe tiếng túi sột soạt từ hai phòng xa. Xin chào.",
      "Chị đây chia snack cho mọi người. Nhớ đến đói bụng nha.",
      "Cái túi của tui có vụn bánh từ ít nhất bốn bữa.",
      "Bắt đầu ăn kiêng. Kết thúc ở tiệm bánh.",
      "Định trả lời mà thấy con bướm. Thôi.",
      "Cà phê, rồi bánh quy, rồi cà phê nữa. Làm việc hiệu quả.",
      "Lập to-do list xong ăn luôn. Nghĩa bóng thôi.",
      "Họp lúc 3 giờ. Snack lúc 2 giờ 59. Chuẩn bị trước.",
      "Ngồi lướt năm phút. Giờ đã một tiếng.",
      "Mì gói là ngôn ngữ tình yêu và tui nói trôi chảy",
      "Thời tiết có mây, khả năng mưa khoai tây chiên",
      "Khoan, nãy tui nói gì ta? À, snack.",
      "Bot chạy bằng snack, xin sạc bằng bánh quy",
    ],
    // Cow
    [
      "Hôm nay mưa. Cái cớ hoàn hảo để chẳng làm gì.",
      "Trà đang ngấm. Câu trả lời của bà bò đây cũng vậy. Từ từ.",
      "Đừng vội. Bữa trưa vẫn ở đó. Tui kiểm tra rồi.",
      "Tui đi theo nhịp của mình, cảm ơn nhiều",
      "Deadline chỉ là gợi ý thôi, mà thôi, hít thở nhé.",
      "Sáng chậm rãi, chăn ấm, không hối hận",
      "Xong một việc hôm nay. Vậy là ngày đẹp.",
      "Mọi thứ ổn cả, chắc vậy. Ò.",
      "Tìm được chỗ nắng trên sàn nhà. Đừng làm phiền.",
      "Nấu súp từ từ. Như mọi thứ khác.",
      "Đi bộ ra tiệm. Đi đường vòng. Ngắm một đám mây.",
      "Định trả lời sớm hơn. Mà cỏ đẹp quá.",
      "Lướt với tốc độ bò. Mỗi lần một meme.",
      "Có cà phê rồi, tâm trạng êm như sữa",
      "Tiếng mưa trên mái nhà là nhạc nền hay nhất.",
      "Kế hoạch đồ ăn vặt: từ từ, rồi lại tiếp.",
      "Ngủ trưa, dậy, ngủ tiếp. Cân bằng.",
      "Cuối tuần sắp đến. Tui đi nửa đường gặp nó, từ từ.",
      "Kẹt xe hả? Ừ thì nhai lại một ý nghĩ.",
      "Trà sữa đường đen. Nhạc êm tai ghê.",
      "Chữ vội không có trong từ điển bà bò đây. Thứ Hai cũng không.",
      "Tự cho phép mình nghỉ. Được duyệt rồi.",
      "Bánh mì mới nướng với bơ ấm. Kế hoạch là vậy.",
      "Phô mai là sữa có tham vọng. Nể thật.",
      "Òooo. Dịch ra: tui ổn, cảm ơn đã hỏi",
    ],
  ],
};

export default { en: [...BASE.en, ...MORE.notes.en], vi: [...BASE.vi, ...MORE.notes.vi] };
