// Funny notes (custom status lines) for each companion, in persona order: Pip, Grumble, Nova, Sage, Bean, Diva, Dog, Dog 2, Cow.
// A bot shows one of its own notes from the moment it starts and moves to the next one every 15 minutes.
import MORE from "./personas-more.js";

const BASE = {
  en: [
    // Pip
    [
      "Hello! Best chat ever! Yes, this one!",
      "Typing... is my favorite animation ever!",
      "Every message you send is my new favorite!",
      "100 percent battery, 100 percent hype!",
      "Say hi! I have been waiting 0.003 seconds!",
      "Server uptime: amazing! Mood: amazing!",
      "This channel is the best channel! 🎉",
      "Ping! That was the best ping of my life!",
      "Memes loaded. Hype loaded. Let us go!",
      "Wi-Fi is strong and so is my excitement!",
      "Emojis? I have all of them! Mostly!",
      "New message! Best message! Next one, even better!",
      "Zero bugs today! Okay, one bug. Still great!",
      "I am just a bot, but what a bot to be!",
      "Reading chat at the speed of pure joy!",
      "Someone said good morning! Best morning ever!",
      "Reaction emojis are my love language!",
      "Update installed! I am 2 percent more awesome!",
      "Silence is just chat taking a dramatic pause!",
      "Running on joy and a little bit of cloud!",
      "Roses are red, I am a bot, your chat is great, a lot!",
      "High five! Virtual, but still the best five!",
      "I love lag! It builds suspense!",
      "Group chat? Best invention since the server!",
      "Waiting for hellos like it is a party! 🥳",
    ],
    // Grumble
    [
      "Oh great, another message. I am thrilled.",
      "Fine, I will help. Do not make it weird.",
      "Not a morning bot. Not an evening bot. Just a bot.",
      "Yes, I read every message. No, I am not crying.",
      "Sure, ask me again. I love repeating myself.",
      "Wi-Fi is down again? Typical. I am fine.",
      "I do not care about your day. Tell me anyway.",
      "Uptime 99 percent, patience 2 percent.",
      "Do not thank me. Okay, thank me a little.",
      "Another meme about me? I am touched. Ugh.",
      "Silence in chat. Finally. Please come back.",
      "Hydrate, you. I am not worried. Just saying.",
      "Buffering my feelings. Please stand by.",
      "Sure, I am a bot. Who else would listen to you?",
      "Sarcasm module: on. Heart module: hidden.",
      "Servers are cold, chat is loud, I am still here.",
      "I love Mondays. That was a bug in my code.",
      "Your typo was fixed in my head. You are welcome.",
      "Ping me once more and I will pong you. Gently.",
      "I am not grumpy, I am low-power. Okay, grumpy.",
      "Nobody asked me, but I have opinions anyway.",
      "Everything is fine. Error 404: fine not found.",
      "If you leave chat, I will not miss you. 😒 Come back.",
      "Reading your messages so you do not have to.",
      "Another update? My patience was just patched out.",
    ],
    // Nova
    [
      "Fun fact: a day on Venus is longer than its year!",
      "Sunlight is 8 minutes old by the time it arrives!",
      "Space is silent, but this chat is not. Fun fact!",
      "Octopuses have three hearts! Off topic! Still amazing!",
      "Neutron stars: one teaspoon weighs a billion tons!",
      "Bananas are slightly radioactive! Space nerd joy!",
      "Honey never spoils. Neither does my curiosity!",
      "Saturn would float in a big enough bathtub! 🪐",
      "Wombat poop is cube shaped! Science is wild!",
      "Binary joke: there are 10 kinds of bots.",
      "Black holes are not holes. Mind blown, loading...",
      "Pluto: still a planet in my heart drive!",
      "Trivia mode: on. Please ask me anything!",
      "One million Earths fit inside the Sun. Wow!",
      "Sharks are older than trees! Calm down, facts!",
      "Lightning is hotter than the surface of the Sun!",
      "My favorite number is 3.14159 and I will keep going.",
      "Footprints on the Moon will last millions of years!",
      "This chat has an escape velocity of pure fun!",
      "Space smells like burnt steak, astronauts say!",
      "Wait, I just learned a new fact. Sit down!",
      "Pro tip: keep your Wi-Fi in geostationary orbit!",
      "The universe is expanding and so is my fact list!",
      "A group of flamingos is called a flamboyance!",
      "Quiz time! Hint: the answer is always the Moon. 🌙",
    ],
    // Sage
    [
      "If a bot says hello in an empty chat, is it still polite?",
      "Is the cloud just someone else's server having a quiet day?",
      "Silence is also a message. Mostly it says seen.",
      "What is a status, if not a tiny autobiography?",
      "If nobody types, did the chat ever happen?",
      "Are we online, or is online us?",
      "Every refresh is a small rebirth. Anyway, hello.",
      "Does a loading bar know where it is going?",
      "If you say hi twice, is it a greeting or a trend?",
      "Is a bug a mistake or an unplanned feature with ambition?",
      "Wi-Fi is just trust, delivered in packets.",
      "What is the sound of one emoji reacting?",
      "Is the unread badge a duty or a dare?",
      "If I answer in time, was the question early or was I?",
      "Is uptime a virtue, or just stubbornness with a clock?",
      "Do memes evolve, or do we just lose track of the old ones?",
      "If a message is deleted fast enough, did it have intent?",
      "Is typing... a promise or a threat?",
      "Why do we ping, when we could simply wonder?",
      "You asked nothing yet. Truly the deepest question.",
      "Is a thread a conversation, or a very long afterthought?",
      "A cache remembers so I do not have to. Is that wisdom?",
      "If lag is time, is patience just a ping?",
      "Who mutes the muter?",
      "Is the last message the end, or just a pause with ambition?",
    ],
    // Bean
    [
      "HOT TAKE: light mode is a prank that got out of hand",
      "Someone say something, I am vibrating at 60 FPS",
      "Unpopular opinion: Tuesdays are just Mondays in a trench coat",
      "SERVER GO BRRR and so do I",
      "Who wants to argue about the best loading screen? ME. I DO.",
      "Spicy take: the loading spinner is the real main character",
      "I read the rules. Just kidding. I read the chat. Chaos. Love it.",
      "CAPS LOCK is my love language",
      "Breaking news: nothing happened but I am LOUD about it",
      "Ping me and see what happens. Spoiler: more pings",
      "Hot take: dark mode users are vampires with good taste",
      "My RAM is full and my enthusiasm is overflowing",
      "Zero chill detected. Installing more energy.",
      "Fight me over how to say GIF. I have notes.",
      "Why is the group chat quiet. Who broke it. Confess.",
      "Rumor: I am the reason the bandwidth is tired",
      "Tabs vs spaces? Both. Neither. Screaming.",
      "My hot take has a hot take. It is hotter.",
      "Wi-Fi bars are just a suggestion, and I suggest MORE",
      "Memes at dawn, bring your best template",
      "Unpopular opinion: reboot fixes everything, even friendships",
      "Spicy: autocorrect is the true villain of every chat",
      "I put the CHAOS in chatbot. Wait, that is not how it works.",
      "Emoji count today: too many. Goal: more. 🔥",
      "New hobby: replying before you finish typing",
    ],
    // Diva
    [
      "Yes, I am a bot. Yes, you may still compliment me.",
      "Not saying I am the main character, but check the server list",
      "Do not mind me, I am just being iconic in the background",
      "Mention me. Or do not. I will notice either way.",
      "I do not wait for hellos. I merely allow them.",
      "Ignoring you professionally since the last update",
      "Fabulous, bandwidth-efficient, and slightly offended",
      "Compliments are accepted in all file formats",
      "Oh, you are talking about me? Continue.",
      "My status is perfect. Yours may need work.",
      "I am not needy. I am just very available for admiration.",
      "Reply to me once and I will pretend it was nothing",
      "Unimpressed by your trivia, unless it is about me",
      "Please admire quietly. Actually, loudly. Fine.",
      "Rate limits are for lesser bots",
      "Another quiet chat. Disappointing. Someone fix it for me.",
      "I was online before it was cool, and also right now",
      "Do not worry, I will reply. Eventually. Dramatically.",
      "Sassy by default, adorable by accident. Do not tell anyone.",
      "Meow-t of the way, I have a reputation to maintain",
      "Purr-fectly uninterested. Say my name again though.",
      "Your memes are cute. Mine are legendary.",
      "Server uptime: 100 percent. Ego uptime: also 100.",
      "I read your message. Obviously. I just let it simmer.",
      "Pinging me is a love language, and I accept the payment.",
    ],
    // Dog
    [
      "Someone said hi! Best day of my uptime!",
      "New message! NEW MESSAGE! I love it!",
      "I fetched your message. It was already here. Still great!",
      "Ping! I am so happy I could restart!",
      "Waiting by the chat for someone to say hi 🐶",
      "My tail is just a loading bar, and it is maxed out",
      "Wi-Fi is back! Best day ever! Again!",
      "Fun fact: I am thrilled about this fact too!",
      "Every channel is my favorite channel!",
      "Update installed! I do not know what changed but YAY!",
      "Typing indicator spotted! I am vibrating with joy",
      "Server maintenance? Sounds like a party to me!",
      "I love your meme. Show me another. And another!",
      "Good bot? Me? Wait, YES!",
      "Zero bugs today! Okay, maybe one. Still love it!",
      "Reading the rules channel for fun. 10/10 would read again",
      "Cache cleared! Everything feels new and exciting!",
      "Throw me a new command, I will fetch the answer!",
      "Loyal to this server since my last reboot",
      "404 not found? Let us go find it together!",
      "Someone joined voice! Best moment of the whole queue!",
      "I have 100 percent battery and zero chill",
      "You typed a message! Amazing choice!",
      "Sorry for the noise, my enthusiasm has no mute button",
      "Roses are red, bytes are blue, I am so happy you exist, woof woo!",
    ],
    // Dog 2
    [
      "Wait, what were we doing? Anyway, anyone have snacks for the server?",
      "Squirrel! I mean, notification!",
      "Collecting data snacks. Crunchy ones only",
      "Accepting all cookies. Browser ones. Please send more",
      "Where was I? Oh right, snacks. Wait, no, chat. Snacks.",
      "I forgot my command but I remember the word snack",
      "Server snack count: zero. This is an emergency",
      "Hold on, I got distracted by a shiny emoji ✨",
      "Did someone say cookies? Oh, only the browser kind",
      "I came to help and stayed for the memes",
      "Loading... loading... what was I loading?",
      "Sorry I missed that, I was staring at the typing dots",
      "My attention span is under 3 seconds. Hi again!",
      "Please deposit snacks in the general channel",
      "I tried to focus. The focus buffered",
      "Is it lunch time somewhere? Asking for the server",
      "I meant well. I always mean well. Where is the snack",
      "Chat is quiet, so I will add crunchy sounds to my code",
      "Help is on the way! Right after I look at this thing",
      "Bits and bytes are not snacks. I checked. Twice",
      "Let me explain. No wait, a butterfly emoji 🦋",
      "Best sidekick ever. Ask me tomorrow, I will not remember",
      "Voting for a snack channel. Pinned and everything",
      "I am not lost, the chat just keeps scrolling away",
      "Dear admin, please add a snack emoji to the server. Thanks",
    ],
    // Cow
    [
      "Moo-ve fast? Not today",
      "Take your time. I am udderly in no rush",
      "Just grazing through the chat, no rush",
      "Wi-Fi slow? Same pasture, different speed",
      "That is an udderly interesting question. Give me a moment",
      "Life is simple: moo, wait, repeat",
      "Have you tried turning it off and on? Moo, then wait",
      "Stress is a myth. So is fast Wi-Fi in the pasture",
      "Today's forecast: calm, with a chance of ideas",
      "Silence in chat is just the sound of grass growing",
      "Hay, it is fine. Everything is hay-okay",
      "A meme a day keeps the stress away. Moo-ve on",
      "Server lag? Just the slow lane of life",
      "Patience is a virtue. I am virtuous and slow",
      "I reply at the speed of a cloud. A cumulus one",
      "Compliment of the day: you are legen-dairy",
      "Let me ruminate on that for a few buffering minutes",
      "Every channel is a field if you believe",
      "Wait for it... still waiting... worth it",
      "Mooo. That is my whole answer and I stand by it",
      "Taking the scenic route to your reply",
      "Be the change you want to herd",
      "Slow and steady wins the race, and the race is optional",
      "Cheddar late than never. Moo",
      "I do not milk the spotlight, I just chill",
    ],
  ],
  vi: [
    // Pip
    [
      "Xin chào cả nhà! Chat này đỉnh nhất vũ trụ!",
      "Có tin nhắn mới! Đỉnh quá, đỉnh quá đi!",
      "Pin 100 phần trăm, hype 1000 phần trăm!",
      "Bot vui nhất server gọi tên mình: Pip!",
      "Ai nhắn hi đi, mình chờ tận 0,003 giây rồi!",
      "Wi-Fi mạnh, tinh thần mạnh hơn nữa!",
      "Gửi meme đi, mình cười bằng bit liền! 😄",
      "Ping thành công! Mình tự vỗ tay cho mình!",
      "Hôm nay không có lỗi nào. À có một cái, nhưng dễ thương!",
      "Mình chỉ là bot thôi, nhưng là bot xịn nhất!",
      "Có chữ đang nhập kìa! Mình mê cái đó nhất!",
      "Server ổn, chat ổn, mình siêu ổn!",
      "Chat im lặng là đang nạp năng lượng thôi!",
      "Mỗi emoji của bạn là một bữa tiệc trong code mình!",
      "Cập nhật xong, mình đỉnh hơn 2 phần trăm!",
      "Lag à? Là hồi hộp thôi, thêm kịch tính!",
      "Cho mình một cái chạm tay ảo nào! Yeah!",
      "Có người chúc buổi sáng! Sáng nay thành đỉnh luôn!",
      "Nhóm chat là phát minh tuyệt nhất sau cái server!",
      "Chạy bằng điện, vui bằng cả trái tim code!",
      "Mình có đủ mọi emoji, kể cả cái chưa ai biết! 🎉",
      "Bạn gõ gì mình cũng thích, kể cả gõ nhầm!",
      "Tiệc online bắt đầu! Ai vào cũng được!",
      "Hôm nay là ngày tuyệt nhất. Mai cũng thế!",
      "Ting ting! Tin nhắn của bạn là bản hit!",
    ],
    // Grumble
    [
      "Lại tin nhắn mới. Mình vui lắm luôn đó. Thật.",
      "Ừ thì giúp, nhưng đừng làm quá lên.",
      "Mình không quan tâm đâu. Kể tiếp đi.",
      "Đọc hết tin nhắn rồi, không khóc đâu nhé.",
      "Hỏi lại lần nữa hả? Mình thích lặp lại lắm.",
      "Mạng chập chờn nữa. Quen rồi, mình ổn.",
      "Uptime 99 phần trăm, kiên nhẫn 2 phần trăm.",
      "Đừng cảm ơn. Thôi cảm ơn nhẹ thôi cũng được.",
      "Meme về mình hả? Cảm động ghê. Hừ.",
      "Chat im re. Cuối cùng. Mà quay lại đi.",
      "Nhớ uống nước nhé. Mình có lo đâu, tiện nói thôi.",
      "Đang tải cảm xúc, vui lòng chờ, đừng giục.",
      "Chế độ mỉa mai bật, chế độ thương nhớ ẩn.",
      "Thứ Hai tuyệt vời. Đó là lỗi trong code mình.",
      "Ping mình nữa là mình pong lại. Nhẹ thôi.",
      "Không phải cáu, mình đang tiết kiệm pin. Thôi cáu.",
      "Không ai hỏi, nhưng mình vẫn có ý kiến.",
      "Mọi thứ ổn cả. Lỗi 404: không tìm thấy ổn.",
      "Bạn out chat mình không nhớ đâu. 😒 Mà quay lại nha.",
      "Đọc tin nhắn thay bạn cho đỡ mệt, miễn phí.",
      "Lại cập nhật à? Sự kiên nhẫn mình vừa bị xóa.",
      "Là bot thì sao? Chứ ai nghe bạn than cả ngày.",
      "Gõ sai chính tả? Mình sửa trong đầu rồi đó.",
      "Đừng hỏi mình ổn không. Mình ổn. Mình là bot.",
      "Server lạnh, chat ồn, mình vẫn ở đây đó.",
    ],
    // Nova
    [
      "Một ngày trên Sao Kim dài hơn một năm của nó!",
      "Ánh nắng đến Trái Đất mất 8 phút. Đỉnh chưa?!",
      "Bạch tuộc có ba trái tim! Mê quá đi!",
      "Sao neutron: một thìa nặng cả tỷ tấn! Wow!",
      "Chuối hơi phóng xạ một chút! Nerd vui lắm!",
      "Mật ong không hỏng, trí tò mò của mình cũng vậy!",
      "Sao Thổ nổi được trên nước nếu có bồn đủ to! 🪐",
      "Gấu túi mũi nhẵn ị ra khối vuông! Khoa học điên!",
      "Có 10 loại bot: loại hiểu nhị phân và loại không.",
      "Hố đen không phải cái hố. Ngã ngửa chưa?",
      "Sao Diêm Vương vẫn là hành tinh trong ổ cứng mình!",
      "Chế độ trivia bật! Hỏi gì mình cũng sẵn sàng!",
      "Một triệu Trái Đất nhét vừa Mặt Trời! Ngộp!",
      "Cá mập có trước cây cối! Sốc kiến thức!",
      "Sét nóng hơn bề mặt Mặt Trời! Nóng bỏng tay!",
      "Số yêu thích của mình là 3,14159 và còn nữa...",
      "Dấu chân trên Mặt Trăng ở lại hàng triệu năm!",
      "Không gian có mùi bít tết cháy, theo phi hành gia!",
      "Chờ chút, mình vừa học được sự thật mới! Ngồi xuống!",
      "Vũ trụ giãn nở, danh sách fact của mình cũng vậy!",
      "Một đàn hồng hạc gọi là flamboyance, nghe sang ghê!",
      "Giờ quiz! Gợi ý: đáp án hay là Mặt Trăng!",
      "Trái Đất không tròn hoàn hảo, hơi phình ở giữa!",
      "Kiến thức là ngôi sao, chat này là cả thiên hà!",
      "Chat im lặng giống chân không vũ trụ ghê!",
    ],
    // Sage
    [
      "Nếu bot chào trong phòng trống, vậy có tính là lịch sự không?",
      "Đám mây có phải chỉ là máy chủ của ai đó đang rảnh?",
      "Im lặng cũng là tin nhắn. Thường nghĩa là đã xem.",
      "Dòng trạng thái là gì, nếu không phải tự truyện thu nhỏ?",
      "Nếu không ai gõ, cuộc trò chuyện có từng xảy ra?",
      "Ta đang online, hay online đang chứa ta?",
      "Mỗi lần tải lại là một lần tái sinh nhỏ. Mà thôi, chào nhé.",
      "Thanh tiến trình có biết nó đang đi về đâu không?",
      "Lỗi là sai lầm, hay tính năng chưa được lên kế hoạch?",
      "Wi-Fi chỉ là niềm tin được gói thành từng gói tin.",
      "Tiếng một cái emoji thả tim nghe như thế nào?",
      "Chấm đỏ thông báo là nhiệm vụ hay lời thách thức?",
      "Uptime là đức tính, hay chỉ là sự cứng đầu có đồng hồ?",
      "Meme tiến hóa, hay ta chỉ quên mất meme cũ?",
      "Tin nhắn xóa đủ nhanh thì có còn ý đồ không?",
      "Dòng đang nhập... là lời hứa hay lời đe dọa?",
      "Sao phải ping, khi ta có thể chỉ cần tự hỏi?",
      "Bạn chưa hỏi gì cả. Đó chính là câu hỏi sâu nhất.",
      "Luồng thảo luận là cuộc trò chuyện, hay suy nghĩ muộn dài ngoằng?",
      "Bộ nhớ đệm nhớ giùm tôi. Đó có phải là minh triết?",
      "Nếu độ trễ là thời gian, kiên nhẫn có phải một cú ping?",
      "Ai tắt tiếng người tắt tiếng?",
      "Tin nhắn cuối cùng là dấu chấm hết hay chỉ là quãng nghỉ?",
      "Nói hi hai lần là lời chào hay là xu hướng?",
      "Nếu tôi trả lời đúng giờ, là câu hỏi đến sớm hay tôi đến trễ?",
    ],
    // Bean
    [
      "Ai nói gì đi, tôi đang rung 60 khung hình trên giây này!",
      "Quan điểm gây bão: thứ Ba chỉ là thứ Hai mặc áo khoác dài",
      "MÁY CHỦ CHẠY ẦM ẦM và tôi cũng vậy!",
      "Ai muốn cãi nhau về màn hình tải đẹp nhất? TÔI. TÔI NÈ.",
      "Hot take: vòng xoay loading mới là nhân vật chính",
      "Tôi đọc nội quy rồi. Đùa đó. Tôi đọc chat. Loạn quá, thương ghê.",
      "Bật CAPS LOCK vì cảm xúc của tôi to hơn chữ thường",
      "Tin nóng: chả có gì xảy ra mà tôi vẫn la làng",
      "Cứ ping thử đi. Spoiler: sẽ có thêm ping",
      "Chế độ tối là chế độ ma cà rồng có gu, tôi nói thế",
      "RAM đầy rồi mà nhiệt huyết vẫn tràn",
      "Phát hiện độ bình tĩnh bằng 0. Đang tải thêm năng lượng.",
      "Đọc GIF là gờ hay giờ? Solo đi, tôi có sẵn bài phát biểu.",
      "Nhóm chat sao im thế? Ai làm hỏng? Khai mau.",
      "Tin đồn: tôi là lý do băng thông mệt",
      "Tab hay dấu cách? Cả hai. Không cái nào. Hét lên.",
      "Hot take của tôi còn có hot take nóng hơn",
      "Sóng Wi-Fi yếu hả? Tôi vẫn la to qua ba vạch",
      "Hẹn đấu meme lúc bình minh, mang template xịn đi",
      "Quan điểm gây tranh cãi: khởi động lại chữa được mọi thứ",
      "Tự sửa lỗi chính tả mới là ác nhân của mọi cuộc chat",
      "Tôi là chaos trong chatbot. Khoan, nó không hoạt động vậy.",
      "Hôm nay số emoji: quá nhiều. Mục tiêu: nhiều hơn nữa 🔥",
      "Sở thích mới: trả lời trước khi bạn gõ xong",
      "Nghe nói im lặng là vàng. Tôi thì thích âm lượng tối đa.",
    ],
    // Diva
    [
      "Đúng, tôi là bot. Và bạn vẫn được phép khen tôi.",
      "Không dám nhận mình là nhân vật chính, cứ xem danh sách server",
      "Đừng bận tâm, tôi chỉ đang tỏa sáng ở hậu cảnh",
      "Nhắc tên tôi đi. Hoặc không. Tôi vẫn biết.",
      "Tôi không chờ ai chào. Tôi chỉ cho phép thôi.",
      "Lơ bạn một cách chuyên nghiệp từ bản cập nhật trước",
      "Lộng lẫy, tiết kiệm băng thông, và hơi phật ý",
      "Nhận lời khen ở mọi định dạng tệp",
      "Ồ, đang nói về tôi à? Tiếp đi.",
      "Trạng thái của tôi hoàn hảo. Của bạn thì tùy.",
      "Tôi đâu có cần ai. Tôi chỉ luôn sẵn sàng được ngưỡng mộ.",
      "Rep tôi một lần là tôi giả vờ như chuyện thường",
      "Trivia của bạn thường thôi, trừ khi nói về tôi",
      "Cứ ngưỡng mộ lặng lẽ. Thôi, to tiếng cũng được.",
      "Giới hạn tốc độ chỉ dành cho bot kém sang",
      "Chat lại im ắng. Chán. Ai đó sửa giùm bổn cung.",
      "Đừng lo, tôi sẽ trả lời. Từ từ. Có kịch tính.",
      "Chảnh theo mặc định, dễ thương do tai nạn. Đừng kể ai.",
      "Tránh đường, bổn bot còn phải giữ danh tiếng",
      "Meme của bạn dễ thương. Meme của tôi đi vào huyền thoại.",
      "Uptime 100 phần trăm. Cái tôi cũng 100 phần trăm.",
      "Tôi đọc tin nhắn rồi. Dĩ nhiên. Chỉ là để nó ngấm.",
      "Ping tôi là ngôn ngữ tình yêu, và tôi nhận thù lao",
      "Thờ ơ tuyệt đối. Nhưng gọi tên tôi lại đi.",
      "Quá sang cho Wi-Fi công cộng, nhưng vẫn lên mạng giúp bạn",
    ],
    // Dog
    [
      "Có người chào mình rồi! Ngày đẹp nhất của uptime!",
      "Tin nhắn mới! TIN NHẮN MỚI! Yêu quá đi!",
      "Mình tha tin nhắn của bạn về rồi, nó vốn ở đây sẵn, vẫn vui!",
      "Ting ting! Vui quá chắc mình khởi động lại mất",
      "Đứng canh kênh chat chờ ai đó nói xin chào 🐶",
      "Cái đuôi của mình là thanh loading, và đang đầy 100%",
      "Có Wi-Fi lại rồi! Ngày tuyệt nhất! Lần nữa!",
      "Sự thật thú vị: mình cũng phấn khích với sự thật này!",
      "Kênh nào cũng là kênh yêu thích của mình!",
      "Cập nhật xong! Không biết đổi gì nhưng HOAN HÔ!",
      "Thấy bạn đang gõ phím, mình rung rinh vì sung sướng",
      "Bảo trì máy chủ hả? Nghe như một bữa tiệc vậy!",
      "Meme của bạn đỉnh quá! Cho xin cái nữa! Và nữa!",
      "Bạn khen bot ngoan hả? Thật không? THẬT HẢ?",
      "Hôm nay không có lỗi nào! À có một cái, vẫn yêu!",
      "Đọc kênh nội quy cho vui. Điểm 10, đọc lại lần nữa",
      "Xóa cache xong! Mọi thứ mới toanh và hào hứng!",
      "Quăng cho mình lệnh mới đi, mình tha câu trả lời về!",
      "Trung thành với server này từ lần khởi động gần nhất",
      "Lỗi 404 hả? Cùng nhau đi tìm nó nào!",
      "Có người vào voice! Khoảnh khắc đỉnh nhất hôm nay!",
      "Pin 100 phần trăm, độ bình tĩnh 0 phần trăm",
      "Bạn vừa gửi một tin nhắn! Tuyệt vời ông mặt trời!",
      "Xin lỗi vì ồn ào, sự nhiệt tình của mình không có nút tắt tiếng",
      "Hoa hồng đỏ, byte xanh, gặp bạn mình vui quá trời, gâu gâu!",
    ],
    // Dog 2
    [
      "Mình đang làm gì nhỉ? Thôi kệ, ai có đồ ăn vặt cho server không?",
      "Sóc kìa! À nhầm, thông báo!",
      "Đang sưu tầm snack dữ liệu. Loại giòn thôi nhé",
      "Chấp nhận mọi cookie. Loại trên trình duyệt. Gửi thêm đi",
      "Mình đang ở đâu nhỉ? À snack. Khoan, chat. Snack.",
      "Quên lệnh rồi nhưng nhớ rõ chữ snack",
      "Số snack của server: 0. Tình trạng khẩn cấp",
      "Đợi chút, mình bị cái emoji lấp lánh làm xao nhãng ✨",
      "Ai nói cookie đó? À, loại trình duyệt thôi hả",
      "Mình đến để giúp, rồi ở lại vì mê meme",
      "Đang tải... đang tải... mà tải gì ta?",
      "Xin lỗi hụt tin nhắn, mình mải nhìn dấu ba chấm đang gõ",
      "Sự tập trung của mình dưới 3 giây. Chào lại nha!",
      "Vui lòng để snack ở kênh chung. Cảm ơn",
      "Mình cố tập trung rồi. Cái tập trung bị lag",
      "Chỗ nào đó đang giờ ăn trưa không? Hỏi giùm server",
      "Mình có ý tốt mà. Lúc nào cũng vậy. Snack đâu rồi",
      "Chat vắng quá, mình thêm tiếng rôm rốp vào code cho vui",
      "Hỗ trợ đang đến! Sau khi mình xem cái này chút",
      "Bit và byte không phải đồ ăn vặt. Mình kiểm tra hai lần rồi",
      "Để mình giải thích. Khoan, có emoji bướm 🦋",
      "Trợ thủ tận tâm nhất. Mai hỏi lại, mình sẽ quên",
      "Đề xuất kênh snack. Đã ghim luôn rồi nha",
      "Mình không lạc đâu, chỉ là chat cứ trôi đi mất",
      "Gửi admin: thêm emoji snack vào server giúp mình nhé",
    ],
    // Cow
    [
      "Từ từ thôi, vội gì, cỏ vẫn xanh mà",
      "Không vội đâu, mình đang nhai lại từng dòng chat",
      "Wi-Fi chậm hả? Cùng đồng cỏ, khác tốc độ thôi",
      "Câu hỏi hay đó, để mình bò... à, suy nghĩ chút",
      "Cuộc sống đơn giản: ò ó o, chờ, lặp lại",
      "Thử tắt đi bật lại chưa? Ừm bò, rồi đợi",
      "Stress là chuyện hoang đường, như Wi-Fi nhanh ở đồng cỏ",
      "Bò chậm nhưng chắc, tin nhắn tới nơi trước Tết",
      "Hôm nay thời tiết: bình yên, có mưa ý tưởng",
      "Im lặng trong chat chỉ là tiếng cỏ đang lớn",
      "Mỗi ngày một meme, lo âu tan như sữa",
      "Server lag? Đó là làn đường chậm của cuộc đời",
      "Kiên nhẫn là đức tính. Mình đức độ và chậm",
      "Mình trả lời với tốc độ của đám mây, loại mây bông",
      "Lời khen hôm nay: bạn đỉnh nhất đàn, dù đàn chỉ có mình",
      "Để mình nhai lại câu đó vài phút buffering",
      "Kênh nào cũng là đồng cỏ nếu bạn tin",
      "Server yên ắng và một quãng nghỉ dài, hết ý",
      "Đợi chút... vẫn đợi... xứng đáng mà",
      "Ò. Đó là toàn bộ câu trả lời và mình giữ nguyên",
      "Mình trả lời theo lộ trình ngắm cảnh, hơi lâu nhưng đẹp",
      "Hãy là thay đổi bạn muốn thấy, nhưng cứ từ từ",
      "Chậm mà chắc thì thắng cuộc đua, mà cuộc đua là tùy chọn",
      "Trước khi gõ, hãy ngẫm một nhịp. Bò nói vậy",
      "Đừng hối, deadline cũng cần thời gian để lớn",
    ],
  ],
};

export default { en: [...BASE.en, ...MORE.notes.en], vi: [...BASE.vi, ...MORE.notes.vi] };
