// Lines for /khen, when the companions cheer on someone who is playing or streaming.
// Placeholders: {goi} how the player is called (anh, chị or bạn), {Goi} the same with a capital, {goiLong} the stretched version
// (anhhh), {em} how a girl calls herself (em, or tui when she talks to "bạn"), {Em} with a capital, {ten} the name the member typed.
// girl and boy are for the two kinds of bots in Vietnamese; English lines are the same for everyone and live under girl.
// crush lines are only used for "anh" and "chị", and only for the girls; named lines only when a name was given.
export default {
  vi: {
    girl: {
      base: [
        "{Goi} hay quá!",
        "{Goi} giỏi quá trời luôn!",
        "Pha xử lý đó đỉnh thật sự, {goi} ơi!",
        "{Em} xem {goi} chơi mà quên cả thở.",
        "{Goi} chơi đỉnh quá, {em} nổi da gà luôn!",
        "Trời ơi {goi} ơi, quá đỉnh!",
        "Cứu {em}, {goi} chơi hay quá chịu không nổi!",
        "{Goi} là số một, {em} nói thật đó.",
        "Ván này {goi} gánh cả team luôn rồi!",
        "{Goi} cứ bình tĩnh, {em} tin {goi} win!",
        "Tay {goi} có nam châm hay sao mà trúng hoài vậy!",
        "{Em} đứng hình luôn, {goi} chơi gì mà đỉnh dữ vậy!",
        "{Goi} ơi cố lên, cả server đang cổ vũ {goi} nè!",
        "Một pha hay như vậy phải vỗ tay ba phút!",
        "Nhìn {goi} chơi là {em} hết lo luôn.",
        "{Goi} chơi đẹp quá, {em} phải lưu lại clip này!",
        "Quá hay, quá giỏi, quá đỉnh, {goi} có gì không giỏi vậy?",
        "{Em} fan cứng của {goi} từ ván đầu tiên luôn á!",
        "Ván nào {goi} cũng hay, đúng là cao thủ!",
        "{Goi} thở thôi cũng đã ngầu rồi!",
        "Đỉnh của chóp luôn {goi} ơi!",
        "{Goi} mà không win thì ai win, nói {em} nghe thử!",
        "Cả server đang đứng dậy vỗ tay cho {goi} nè!",
        "{Goi} lo gì thua, có {em} cổ vũ rồi!",
        "Pha này {goi} chơi như chủ giải vậy đó!",
        "{Em} tự hào về {goi} ghê, chơi hay thiệt!",
        "Ai dám nói {goi} chơi dở, ra đây {em} nói chuyện!",
        "Mỗi lần {goi} bấm là một lần {em} la hét!",
        "Đẳng cấp là đây chứ đâu, {goi} ơi!",
        "{Goi} đang tỏa sáng như đèn sân khấu luôn!",
        "Mắt {em} chỉ có {goi} thôi, mấy thứ khác mờ hết rồi!",
        "{Goi} chơi mượt quá, {em} xem mà mê mẩn luôn!",
      ],
      crush: [
        "{Em} muốn đẻ con cho {goiLong} luôn á, hay quá trời!!!",
        "{Goi} chơi vậy ai mà không mê, {em} đổ {goiLong} rồi nè!",
        "Lấy {em} đi {goi}, {em} cổ vũ {goi} cả đời luôn!",
        "{Em} muốn đẻ con cho {goiLong} quá đi!",
        "Hay vậy mà còn dễ thương nữa chứ, {em} chịu hết nổi rồi {goiLong}!",
        "{Goi} ơi, {em} yêu {goi} nhất trần đời {goiLong}!",
      ],
      named: [
        "{ten} ơi, {goi} hay quá chừng!",
        "{ten} giỏi quá, {em} xem mà mê luôn!",
        "Cả server đang gọi tên {ten}: {ten}! {ten}!",
        "{ten} ơi cố lên, {em} tin {goi} làm được!",
        "{ten} chơi đỉnh quá, phải khen một trăm lần!",
        "Cảm ơn {ten} đã cho {em} xem pha vừa rồi!",
      ],
    },
    boy: {
      base: [
        "{Goi} chơi đỉnh quá, tui nể thật sự!",
        "Pha này đúng là chuyên nghiệp, {goi} ơi!",
        "Nhìn {goi} chơi mà tui muốn đi học lại từ đầu.",
        "{Goi} cứ chơi tiếp đi, tui vỗ tay mỏi tay luôn!",
        "Tui là fan của {goi} từ phút đầu tiên, nhớ nha!",
        "Gánh team kiểu này thì tui xin bái phục {goi}!",
        "{Goi} chơi hay quá, tui phải ghi chép lại để học!",
        "Chơi thế này thì chưa thấy ai cản nổi {goi} đâu!",
      ],
      named: [
        "{ten} chơi hay quá, tui xin bái phục!",
        "Cả server đang gọi tên {ten}, hay lắm {ten}!",
      ],
    },
  },
  en: {
    girl: {
      base: [
        "You are so good at this!",
        "That play was unreal!",
        "Absolutely incredible, keep going!",
        "I cannot stop watching you play!",
        "You make it look so easy!",
        "Every move is perfect!",
        "You are carrying the whole team!",
        "The whole server is cheering for you!",
        "That was cleaner than a freshly wiped keyboard!",
        "You are on fire right now!",
        "I am your biggest fan and I will say it again!",
        "Nobody plays like you!",
        "Please do that again, I missed it, I was too busy being amazed!",
        "You are the main character today!",
        "That aim is legally questionable, in the best way!",
        "I believe in you, you got this!",
        "Chat is going wild!",
        "You just made my whole day!",
        "Genius level play, truly!",
        "Clip that, frame it, hang it on the wall!",
        "You are so talented it hurts!",
        "Do not stop, you are glowing!",
        "That was a masterpiece!",
        "My respect for you just went up again!",
        "You are my favourite player ever!",
        "Standing ovation from every bot here!",
        "What a legend!",
        "Your skills are unreal, I am speechless!",
        "Win or lose, you look great doing it!",
        "The crowd goes wild, and the crowd is thirty bots!",
      ],
      named: [
        "{ten}, you are incredible!",
        "Come on {ten}, you got this!",
        "Everybody say it with me: {ten}! {ten}!",
        "{ten} is on fire today!",
        "That was all {ten}, wow!",
        "{ten} makes it look so easy!",
      ],
    },
    boy: { base: [], named: [] },
  },
};

// Lines for /che: friendly teasing of a player who just missed, never about looks, family or anything personal.
// Same placeholders and groups as above, without crush lines.
export const TEASE = {
  vi: {
    girl: {
      base: [
        "{Goi} chơi vậy mà cũng dám bật stream hả?",
        "Ủa {goi} ơi, tay {goi} để quên ở nhà hả?",
        "{Em} tưởng {goi} đang chơi ván tập, hóa ra ván thật hả?",
        "Pha đó là cố ý đúng không? Nói là cố ý đi {goi}!",
        "{Goi} ơi, cái chuột có làm gì {goi} đâu mà {goi} đối xử với nó vậy?",
        "Cả server đang nín cười giùm {goi} đó.",
        "{Em} xem mà thương {goi} luôn, cố lên nha, hơi khó nhưng cố lên.",
        "Lag à? Chắc là lag rồi, đúng không {goi}? Đúng không?",
        "{Goi} chơi kiểu này {em} tưởng đang xem phim hài.",
        "Ván sau {goi} thử nhìn vào màn hình xem sao nha!",
        "Chê {goi} một tí thôi, vì {em} biết {goi} chịu được mà!",
        "Đồng đội của {goi} chắc đang cầu nguyện đó.",
        "Pha này mà cũng thua thì {em} xin đổi game cho {goi}!",
        "{Goi} ơi, game này có hướng dẫn đó, {em} gửi link cho nè.",
        "Hay quá {goi} ơi... hay cho mấy đứa đối thủ đó!",
        "{Goi} đừng buồn, ai cũng có ngày tay mình đi chơi riêng.",
        "Bàn phím của {goi} chắc cũng đang xấu hổ giùm {goi}.",
        "{Em} đếm rồi, pha vừa nãy là lần thứ năm trong ván này luôn đó {goi}!",
        "{Goi} chơi như đang thử nghiệm xem game có chịu nổi không vậy.",
        "Cho {goi} thêm một ván nữa để gỡ gạc, {em} rộng lượng lắm!",
        "{Goi} ơi, nhân vật của {goi} đang gửi đơn xin nghỉ việc đó.",
        "Đừng lo {goi}, ván sau chắc chắn sẽ hay hơn. Chắc vậy đó.",
        "{Em} thấy {goi} cố gắng lắm rồi, cố gắng theo hướng ngược lại.",
        "Pha này mà đưa vô clip thì thành meme luôn đó {goi}!",
        "{Goi} chơi vậy là có chiến thuật gì mà {em} chưa hiểu hả?",
        "Chuẩn bị tinh thần đi {goi}, cả server sẽ nhắc pha này cả tuần.",
        "{Goi} ơi, đối thủ gửi lời cảm ơn vì {goi} đã giúp đỡ nhiệt tình!",
        "Đẹp lắm {goi}, đẹp theo kiểu {em} không dám nhìn lần hai!",
        "{Goi} chơi tệ một chút cho tụi {em} có chuyện để nói thôi mà, đúng hông?",
        "Thôi {goi} nghỉ tay uống miếng nước đi, để tay {goi} tỉnh lại.",
        "{Goi} mà thắng ván này là {em} đi ăn kẹo luôn đó!",
        "{Em} chê {goi} vì thương {goi} đó nha, đừng có giận!",
      ],
      named: [
        "{ten} ơi, pha vừa rồi là gì vậy trời?",
        "{ten} chơi vậy là có kế hoạch gì hả, nói {em} nghe thử!",
        "Cả server đang nhìn {ten} và nín cười đó.",
        "{ten} ơi, cố lên, hơi khó thôi chứ chưa tới mức bó tay!",
        "{ten} ơi, ván sau chắc chắn khá hơn, {em} tin vậy... hơi hơi.",
        "Chê {ten} là vì thương {ten} đó nha!",
      ],
    },
    boy: {
      base: [
        "{Goi} chơi kiểu này thì tui cũng chịu thua luôn, thua luôn cách hiểu.",
        "Tay {goi} đang đi nghỉ mát đâu rồi, gọi về chơi đi!",
        "Tui xem mà muốn nhắn tin an ủi {goi} luôn.",
        "{Goi} cứ yên tâm, tui sẽ không clip pha này. Chắc vậy.",
        "Pha vừa nãy chắc là cố ý, tui tin vậy cho {goi} đỡ buồn.",
        "{Goi} chơi vậy thì đối thủ chắc cảm ơn cả họ nhà {goi} đó.",
        "Tui chê {goi} một câu thôi, vì tui biết {goi} sẽ gỡ lại.",
        "Ván sau {goi} thử bật chế độ nghiêm túc xem sao.",
      ],
      named: [
        "{ten} ơi, pha đó là gì vậy trời, tui cũng không biết nữa.",
        "Chê {ten} một tí thôi, ván sau hay hơn nha!",
      ],
    },
  },
  en: {
    girl: {
      base: [
        "You play like that and still hit the stream button?",
        "Did you leave your hands at home today?",
        "I thought that was a practice round. It was the real one?",
        "That was on purpose, right? Say it was on purpose!",
        "What did that mouse ever do to you?",
        "The whole server is holding in laughter for you.",
        "I feel for you, keep going, it is a little hard but keep going.",
        "Lag, right? It must have been lag. Right? Right?",
        "Watching this feels like a comedy show.",
        "Next round, try looking at the screen, just an idea!",
        "I only tease you because I know you can take it!",
        "Your teammates are probably praying right now.",
        "If you lose this one I will swap your game for you!",
        "This game has a tutorial, I can send you the link.",
        "Great job, truly great, for the other team!",
        "Do not be sad, everybody has a day when their hands go on vacation.",
        "Your keyboard is probably embarrassed for you.",
        "I counted, that was the fifth time this round!",
        "You play like you are testing whether the game can take it.",
        "One more round to make up for it, I am generous like that!",
        "Your character just filed a resignation letter.",
        "Do not worry, the next round will be better. Probably.",
        "I can see you are trying hard, just in the opposite direction.",
        "If that goes in a clip, it becomes a meme!",
        "Is that a strategy I do not understand yet?",
        "Brace yourself, the server will mention this play all week.",
        "The other team says thank you for your generous help!",
        "Beautiful, in a way I cannot look at twice!",
        "Take a sip of water, let your hands wake up.",
        "If you win this one I will eat my own keyboard!",
      ],
      named: [
        "{ten}, what was that play?",
        "{ten}, is that a plan? Please explain!",
        "The whole server is looking at {ten} and holding in laughter.",
        "Come on {ten}, it is hard, not impossible!",
        "{ten}, the next round will be better, I believe it, a little.",
        "I only tease {ten} because I care!",
      ],
    },
    boy: { base: [], named: [] },
  },
};
