// Lines for /khen, when the companions cheer on someone who is playing or streaming.
// Placeholders: {goi} how the player is called (anh, chị or bạn), {Goi} the same with a capital, {goiLong} the stretched version
// (anhhh), {em} how a girl calls herself (em, or tui when she talks to "bạn"), {Em} with a capital, {ten} the name the member typed.
// girl and boy are for the two kinds of bots in Vietnamese; English lines are the same for everyone and live under girl.
// crush lines are only used for "anh" and "chị", and only for the girls; named lines only when a name was given.
export default {
  vi: {
    girl: {
      base: [
        "{Goi} hay quá!",
        "{Goi} giỏi quá trời luôn!",
        "Pha xử lý đó đỉnh thật sự, {goi} ơi!",
        "{Em} xem {goi} chơi mà quên cả thở.",
        "{Goi} chơi đỉnh quá, {em} nổi da gà luôn!",
        "Trời ơi {goi} ơi, quá đỉnh!",
        "Cứu {em}, {goi} chơi hay quá chịu không nổi!",
        "{Goi} là số một, {em} nói thật đó.",
        "Ván này {goi} gánh cả team luôn rồi!",
        "{Goi} cứ bình tĩnh, {em} tin {goi} win!",
        "Tay {goi} có nam châm hay sao mà trúng hoài vậy!",
        "{Em} đứng hình luôn, {goi} chơi gì mà đỉnh dữ vậy!",
        "{Goi} ơi cố lên, cả server đang cổ vũ {goi} nè!",
        "Một pha hay như vậy phải vỗ tay ba phút!",
        "Nhìn {goi} chơi là {em} hết lo luôn.",
        "{Goi} chơi đẹp quá, {em} phải lưu lại clip này!",
        "Quá hay, quá giỏi, quá đỉnh, {goi} có gì không giỏi vậy?",
        "{Em} fan cứng của {goi} từ ván đầu tiên luôn á!",
        "Ván nào {goi} cũng hay, đúng là cao thủ!",
        "{Goi} thở thôi cũng đã ngầu rồi!",
        "Đỉnh của chóp luôn {goi} ơi!",
        "{Goi} mà không win thì ai win, nói {em} nghe thử!",
        "Cả server đang đứng dậy vỗ tay cho {goi} nè!",
        "{Goi} lo gì thua, có {em} cổ vũ rồi!",
        "Pha này {goi} chơi như chủ giải vậy đó!",
        "{Em} tự hào về {goi} ghê, chơi hay thiệt!",
        "Ai dám nói {goi} chơi dở, ra đây {em} nói chuyện!",
        "Mỗi lần {goi} bấm là một lần {em} la hét!",
        "Đẳng cấp là đây chứ đâu, {goi} ơi!",
        "{Goi} đang tỏa sáng như đèn sân khấu luôn!",
        "Mắt {em} chỉ có {goi} thôi, mấy thứ khác mờ hết rồi!",
        "{Goi} chơi mượt quá, {em} xem mà mê mẩn luôn!",
      ],
      crush: [
        "{Em} muốn đẻ con cho {goiLong} luôn á, hay quá trời!!!",
        "{Goi} chơi vậy ai mà không mê, {em} đổ {goiLong} rồi nè!",
        "Lấy {em} đi {goi}, {em} cổ vũ {goi} cả đời luôn!",
        "{Em} muốn đẻ con cho {goiLong} quá đi!",
        "Hay vậy mà còn dễ thương nữa chứ, {em} chịu hết nổi rồi {goiLong}!",
        "{Goi} ơi, {em} yêu {goi} nhất trần đời {goiLong}!",
      ],
      named: [
        "{ten} ơi, {goi} hay quá chừng!",
        "{ten} giỏi quá, {em} xem mà mê luôn!",
        "Cả server đang gọi tên {ten}: {ten}! {ten}!",
        "{ten} ơi cố lên, {em} tin {goi} làm được!",
        "{ten} chơi đỉnh quá, phải khen một trăm lần!",
        "Cảm ơn {ten} đã cho {em} xem pha vừa rồi!",
      ],
    },
    boy: {
      base: [
        "{Goi} chơi đỉnh quá, tui nể thật sự!",
        "Pha này đúng là chuyên nghiệp, {goi} ơi!",
        "Nhìn {goi} chơi mà tui muốn đi học lại từ đầu.",
        "{Goi} cứ chơi tiếp đi, tui vỗ tay mỏi tay luôn!",
        "Tui là fan của {goi} từ phút đầu tiên, nhớ nha!",
        "Gánh team kiểu này thì tui xin bái phục {goi}!",
        "{Goi} chơi hay quá, tui phải ghi chép lại để học!",
        "Chơi thế này thì chưa thấy ai cản nổi {goi} đâu!",
      ],
      named: [
        "{ten} chơi hay quá, tui xin bái phục!",
        "Cả server đang gọi tên {ten}, hay lắm {ten}!",
      ],
    },
  },
  en: {
    girl: {
      base: [
        "You are so good at this!",
        "That play was unreal!",
        "Absolutely incredible, keep going!",
        "I cannot stop watching you play!",
        "You make it look so easy!",
        "Every move is perfect!",
        "You are carrying the whole team!",
        "The whole server is cheering for you!",
        "That was cleaner than a freshly wiped keyboard!",
        "You are on fire right now!",
        "I am your biggest fan and I will say it again!",
        "Nobody plays like you!",
        "Please do that again, I missed it, I was too busy being amazed!",
        "You are the main character today!",
        "That aim is legally questionable, in the best way!",
        "I believe in you, you got this!",
        "Chat is going wild!",
        "You just made my whole day!",
        "Genius level play, truly!",
        "Clip that, frame it, hang it on the wall!",
        "You are so talented it hurts!",
        "Do not stop, you are glowing!",
        "That was a masterpiece!",
        "My respect for you just went up again!",
        "You are my favourite player ever!",
        "Standing ovation from every bot here!",
        "What a legend!",
        "Your skills are unreal, I am speechless!",
        "Win or lose, you look great doing it!",
        "The crowd goes wild, and the crowd is thirty bots!",
      ],
      named: [
        "{ten}, you are incredible!",
        "Come on {ten}, you got this!",
        "Everybody say it with me: {ten}! {ten}!",
        "{ten} is on fire today!",
        "That was all {ten}, wow!",
        "{ten} makes it look so easy!",
      ],
    },
    boy: { base: [], named: [] },
  },
};
