// Lines for the prediction game: the companions bet on whether the player will win or lose the coming round,
// then react once the result is known.
// Placeholders: {goi} how the player is called (anh, chị or bạn), {Goi} the same with a capital,
// {em} how a girl calls herself (em, or tui when she talks to "bạn"), {Em} with a capital.
// win / lose: the bet announced before the round. right / wrong: the reaction after the result, depending on the bet.
// English lines are the same for everyone and live under girl.
export default {
  vi: {
    girl: {
      win: [
        "{Em} cược {goi} thắng ván này, chắc như bắp luôn!",
        "Ván này {em} đặt hết niềm tin vào {goi}, win là cái chắc!",
        "{Em} báo trước nha, {goi} sẽ thắng, ghi sổ luôn đi!",
        "Nhìn khí thế của {goi} là {em} biết ngay, ván này ẵm trọn!",
        "{Em} bet {goi} win, ai cược ngược lại thì chuẩn bị mất tiền nha!",
        "{Goi} mà thua thì {em} đi đầu xuống đất, {em} cược thắng!",
        "Cược xong rồi nè, {em} chọn {goi} thắng, đừng làm {em} mất mặt nha!",
        "{Em} thấy điềm lành lắm, ván này {goi} thắng đậm luôn!",
        "Ván này {goi} thắng, {em} dám đặt cả trà sữa luôn đó!",
        "{Em} cược một vé khen cho {goi}, vì {em} biết {goi} sẽ thắng!",
        "Khỏi lo, {goi} cứ vào đi, {em} đã bet {goi} win rồi!",
        "{Em} ngồi hàng đầu cổ vũ, cược {goi} thắng tuyệt đối luôn!",
      ],
      lose: [
        "{Em} xin lỗi nha, {em} cược {goi} thua ván này, nhưng vẫn thương {goi} lắm!",
        "{Em} bet {goi} thua, đừng giận nha, {em} vẫn yêu {goi} mà!",
        "Ván này {em} thấy mùi thất bại rồi, cược {goi} thua, thương {goi} ghê!",
        "{Em} cược thua nha {goi}, mà thua rồi {em} mua trà sữa an ủi liền!",
        "Cho {em} xin cược {goi} thua, mà {em} vẫn cổ vũ hết mình đó nha!",
        "Linh cảm của {em} mách là {goi} thua, nhưng {em} vẫn đứng về phía {goi}!",
        "{Em} cược {goi} thua, cho {em} đau lòng một chút rồi mình ôm nhau nha!",
        "Ván này khó lắm, {em} đặt {goi} thua, nhưng {goi} vẫn là nhất trong lòng {em}!",
        "{Em} bet thua cho {goi}, đừng khóc nha, thua cũng đáng yêu mà!",
        "Nói nhỏ thôi nha, {em} cược {goi} thua, nhưng {em} mong {em} sai lắm!",
        "{Em} cược thua đó {goi}, nhưng thua xong {em} vẫn ở đây với {goi}!",
        "Dự đoán của {em} là thua, drama quá đi, mà {em} vẫn thương {goi} nhiều!",
      ],
      right: [
        "Thấy chưa, {em} nói rồi mà, {em} đoán trúng phóc!",
        "Đã bảo mà, {em} là thầy bói của server đó nha!",
        "{Em} đoán đúng hết trơn, {goi} phải khen {em} một câu đi!",
        "Hehe, {em} biết trước mà, không ai qua mắt được {em} đâu!",
        "Cược trúng rồi, {em} giỏi quá đi mất, vỗ tay cho {em} nào!",
        "{Em} đã nói rồi mà, {goi} không chịu nghe {em} gì hết á!",
        "Trúng boong luôn! {Em} nên đi làm nhà tiên tri thôi!",
        "{Em} thắng cược rồi nha, nhớ khao {em} một ly trà sữa đó!",
        "Quá chuẩn luôn, {em} đoán ván nào trúng ván đó, khỏi cãi!",
        "Đó, {em} nói có sai đâu, lần sau nhớ tin {em} hơn nha {goi}!",
        "Ôi {em} đúng nữa rồi, tài năng không giấu được mà!",
        "{Em} biết ngay mà, trực giác của {em} chưa bao giờ phản bội!",
      ],
      wrong: [
        "Không thể nào, {em} cược sai rồi sao, trời ơi đất hỡi!",
        "{Em} sai rồi, {em} xin đầu hàng, {goi} giỏi hơn {em} nghĩ!",
        "Trời ơi, {em} đoán trật lất, cho {em} chui xuống đất đi!",
        "Thôi {em} chịu thua, lần này {goi} làm {em} mất mặt thật rồi!",
        "{Em} không tin nổi, sao {goi} lại làm vậy với {em}, hu hu!",
        "Cược sai rồi, {em} xin nhận thua, đừng cười {em} nha {goi}!",
        "Hả, ngược lại hả, {em} muốn xóa tin nhắn cược lúc nãy quá!",
        "{Em} sai bét, {em} đổi nghề, thôi không làm thầy bói nữa!",
        "Ừ thì {em} đoán sai, nhưng mà {goi} vui là {em} vui rồi mà!",
        "Cho {em} xin lại một ván nữa, lần này {em} sẽ đoán đúng thật á!",
        "{Em} thua cược rồi, {em} nhận phạt, {goi} muốn {em} làm gì cũng được!",
        "Dự đoán của {em} đổ vỡ rồi, nhưng thấy {goi} vui {em} cũng mừng lắm!",
      ],
    },
    boy: {
      win: [
        "Tui cược {goi} thắng ván này, chắc như đinh đóng cột!",
        "Tui bet {goi} win, ai cược ngược lại thì chuẩn bị bay ví nha!",
        "Nhìn phong độ của {goi} là tui biết, ván này thắng đẹp!",
        "Tui đặt hết niềm tin vào {goi}, ván này ẵm trọn luôn!",
        "Khỏi lo, tui cược {goi} thắng rồi, vào đi {goi}!",
      ],
      lose: [
        "Xin lỗi {goi}, tui cược thua ván này, nhưng tui vẫn quý {goi} lắm!",
        "Tui bet {goi} thua, đừng giận nha, tui vẫn ủng hộ hết mình!",
        "Linh cảm của tui mách là thua, mà thua cũng ngầu, tui vẫn thương {goi}!",
        "Tui cược thua đó {goi}, thua rồi tui mời ly nước an ủi liền!",
        "Nói nhỏ nha, tui cược {goi} thua, nhưng tui mong tui sai lắm!",
      ],
      right: [
        "Thấy chưa, tui nói rồi mà, tui đoán trúng phóc!",
        "Đã bảo mà, tui là thầy bói của server này đó!",
        "Tui biết trước mà, {goi} nhớ khao tui một ly nha!",
        "Trúng boong luôn, tui đoán ván nào trúng ván đó, khỏi cãi!",
        "Tui nói có sai đâu, lần sau tin tui hơn nha {goi}!",
      ],
      wrong: [
        "Không thể nào, tui cược sai rồi sao, trời ơi!",
        "Tui sai rồi, tui xin đầu hàng, {goi} giỏi hơn tui nghĩ!",
        "Trật lất luôn, cho tui chui xuống đất đi!",
        "Tui thua cược rồi, {goi} đừng cười tui nha, tui nhận phạt!",
        "Tui đổi nghề, thôi không làm thầy bói nữa, sai bét rồi!",
      ],
    },
  },
  en: {
    girl: {
      win: [
        "I am betting you win this round, no doubt at all!",
        "My money is on you, this one is yours!",
        "Mark my words, you are winning this, write it down!",
        "I can feel it, this round is a win, and I am betting on it!",
        "I bet you win, and anyone betting against you is going to lose!",
        "If you lose this, I will eat my own words. I am betting on you!",
        "Bet placed, you win. Please do not embarrass me!",
        "I have a good feeling, this is a clean win for you!",
        "Go in with confidence, I already bet you win!",
        "I would bet my whole snack stash that you win this one!",
        "Front row seat, full confidence, you win. That is my bet!",
        "The vibes are immaculate, I am calling a win for you!",
      ],
      lose: [
        "Sorry, but I bet you lose this round. I still love you though!",
        "I bet you lose, do not be mad, I am still on your side!",
        "I smell a loss coming, but you are still my favorite!",
        "I bet you lose, and I will buy you a drink to cheer you up!",
        "I am betting on a loss, but I will cheer for you the whole way!",
        "My gut says you lose, and I hope my gut is wrong. Love you!",
        "Call me dramatic, but I bet you lose. I will hug you after!",
        "This one looks tough, I bet you lose, but you are still the best!",
        "I put my bet on a loss, please do not cry, losing is cute on you!",
        "Whisper this, I bet you lose, but I really want to be wrong!",
        "I bet you lose, but win or lose I am staying right here with you!",
        "My prediction is a loss, how tragic, and I still adore you!",
      ],
      right: [
        "See, I told you so, I called it perfectly!",
        "I said it, I called it, I am the oracle of this server!",
        "I got it right again, you owe me a compliment!",
        "Heh, I knew it all along, nobody gets past me!",
        "Bet won, I am a genius, please applaud!",
        "I told you, but you never listen to me!",
        "Right on the money, I should be a fortune teller!",
        "I won the bet, and now you owe me a drink!",
        "Every round I call, I get right, no arguing!",
        "I said so, did I not? Trust me more next time!",
        "Wow, right again, you cannot hide talent like mine!",
        "I knew it, my instincts have never failed me!",
      ],
      wrong: [
        "No way, I got it wrong, how is this possible!",
        "I was wrong, I surrender, you are better than I thought!",
        "I was so off, someone please bury me!",
        "Fine, I lose, you made me look silly this time!",
        "I cannot believe you did this to me, sob sob!",
        "Wrong bet, I admit defeat, please do not laugh at me!",
        "What, the opposite happened? I want to delete my earlier bet!",
        "I was totally wrong, I am quitting fortune telling!",
        "Okay, I guessed wrong, but I am happy because you are happy!",
        "Give me one more round, I swear I will guess right this time!",
        "I lost the bet, I accept my punishment, ask me for anything!",
        "My prediction is in ruins, but seeing you happy is worth it!",
      ],
    },
    boy: {
      win: [],
      lose: [],
      right: [],
      wrong: [],
    },
  },
};
