// Status notes that depend on the local time of day, so the companions look like people living through their day.
// Buckets: morning 05-10h, noon 11-13h, afternoon 14-17h, evening 18-21h, night 22-23h, latenight 00-04h, weekend (Saturday and Sunday, daytime).
export default {
  vi: {
    morning: [
      "cà phê đầu ngày chưa kịp ngấm",
      "dậy rồi, nhưng mới được nửa người",
      "sáng nay ăn gì đây ta?",
      "kẹt xe từ sáng sớm, quen rồi",
      "báo thức kêu năm lần mới chịu dậy",
      "trời mát, tâm trạng cũng ổn ổn",
      "bánh mì sáng nay ngon bất ngờ",
      "mở mắt ra là thấy deadline đang nhìn",
      "nhạc buổi sáng bật lên cho tỉnh",
      "ra đường mà quên mang áo mưa, liều thật",
      "ly cà phê thứ hai rồi, chưa tính",
      "sáng thứ hai nào mà chẳng uể oải",
      "đang lướt tin tức cho tỉnh ngủ",
      "hôm nay phải làm xong việc sớm, nói vậy thôi",
      "ngáp một cái dài ngoằng",
      "mùi cơm sáng bên nhà hàng xóm thơm ghê",
    ],
    noon: [
      "đói rồi, trưa nay ăn gì?",
      "cơm trưa xong là buồn ngủ liền",
      "nắng gắt quá, không muốn ra đường",
      "đang nghĩ xem nên ăn cơm hay ăn bún",
      "nghỉ trưa mười phút thôi, hứa",
      "trà đá giữa trưa là chân ái",
      "họp xong mà bụng réo ầm ầm",
      "trưa rồi mà việc chưa xong nổi một nửa",
      "đặt đồ ăn mà shipper chưa tới, đói muốn xỉu",
      "mình ăn nhiều quá, giờ lười luôn",
      "trời nóng muốn chảy ra luôn",
      "hôm nay ăn cơm tấm, hạnh phúc đơn giản vậy thôi",
      "lướt mạng một chút rồi mới làm tiếp",
      "ai rủ đi ăn trưa không?",
      "ngủ gật trên bàn một xíu thôi",
      "căn tin hôm nay hết món mình thích rồi",
    ],
    afternoon: [
      "chiều rồi mà đầu óc vẫn ở buổi sáng",
      "cần một ly trà sữa gấp",
      "còn hai tiếng nữa là hết giờ, cố lên",
      "deadline đang thở sau gáy",
      "nắng chiều đẹp mà mình ngồi trong phòng",
      "đang đếm từng phút đến giờ về",
      "ngồi họp mà hồn đã bay đi đâu",
      "trời đổ mưa bất ngờ, kẹt ở quán cà phê",
      "đói bụng lúc ba giờ chiều, ai hiểu không",
      "tiếng mưa trên mái tôn nghe êm ghê",
      "chiều nay có kế hoạch gì chưa nhỉ?",
      "mệt nhưng vẫn phải cố thêm chút nữa",
      "bật playlist chill cho đỡ chán",
      "mới nhận thêm việc, tui xin khóc một lúc",
      "ăn vặt giữa giờ là quyền con người",
      "kẹt xe giờ tan tầm, nhìn mà nản",
    ],
    evening: [
      "tan làm rồi, về nhà thôi",
      "tối nay ăn gì cho đỡ tốn công nấu?",
      "đang nấu cơm, khói bay mù mịt",
      "mưa tối nay nghe thích ghê",
      "nằm dài trên ghế sofa, không muốn nhúc nhích",
      "xem tập phim mới, đừng làm phiền",
      "về tới nhà là thấy đời tươi hẳn",
      "tối nay tính đi dạo một vòng",
      "đang nghe lại bài hát cũ, nhớ ghê",
      "hôm nay mệt nhưng cũng đáng",
      "tắm xong thấy mình như người mới",
      "đồ ăn giao tới rồi, mừng quá trời",
      "lướt mạng xã hội mà quên cả giờ",
      "trời tối sớm quá, mới đó đã hết ngày",
      "hẹn bạn đi ăn tối, đói sẵn rồi",
      "dọn nhà một chút cho thấy mình có ích",
    ],
    night: [
      "định ngủ sớm mà chưa buồn ngủ",
      "mười một giờ rồi, thêm một tập nữa thôi",
      "đang nằm lướt điện thoại, lại thế rồi",
      "tối nay trời yên, nghe nhạc nhẹ nhẹ",
      "ngày mai lại phải dậy sớm, thôi kệ",
      "đánh răng xong là sắp ngủ rồi",
      "nằm nghĩ vu vơ về đủ thứ chuyện",
      "một ly sữa nóng rồi đi ngủ",
      "hôm nay thế là đủ rồi nhé",
      "đèn tắt hết, chỉ còn màn hình sáng",
      "mắt díp lại mà tay vẫn cầm điện thoại",
      "chuẩn bị đồ cho ngày mai, ngoan ghê",
      "tiếng quạt quay đều, buồn ngủ ghê",
      "ai còn thức không, tui hơi cô đơn",
      "đếm cừu thôi, chắc không hiệu quả",
      "chúc mọi người ngủ ngon, mình sắp đi đây",
    ],
    latenight: [
      "mấy giờ rồi mà vẫn chưa ngủ nổi",
      "mất ngủ rồi, ai thức cùng không?",
      "đói bụng lúc khuya, mì gói gọi tên mình",
      "sáng mai chắc chết mất",
      "đêm yên tĩnh, nghĩ lung tung hết cả",
      "nghe nhạc nhỏ nhỏ cho khỏi ồn hàng xóm",
      "ba giờ sáng rồi, đúng là cú đêm",
      "mắt thâm quầng thêm một tầng nữa",
      "nằm trằn trọc mãi không ngủ được",
      "chạy deadline giữa đêm, thương mình ghê",
      "ngoài trời mưa rả rích, thích thật",
      "đêm khuya thì ý tưởng cứ ùa về",
      "cà phê giờ này là lựa chọn sai lầm",
      "lỡ xem thêm một tập, thế là sáng",
      "tiếng côn trùng ngoài hiên nghe hay ghê",
      "ngủ thôi, hứa là lần này ngủ thật",
    ],
    weekend: [
      "cuối tuần rồi, được lười đàng hoàng",
      "hôm nay không báo thức, sướng ghê",
      "sáng cuối tuần ngủ nướng là chân lý",
      "đi cà phê với bạn, nói chuyện trên trời dưới đất",
      "dọn phòng mà dọn mãi chưa xong",
      "cuối tuần mà vẫn dậy sớm, thật khó hiểu",
      "tính đi chơi mà trời mưa, thôi ở nhà",
      "xem phim cả ngày, không ai cấm",
      "đi chợ cuối tuần, mua nhiều hơn cần thiết",
      "hôm nay nấu ăn thử, hy vọng không cháy",
      "chủ nhật mà đã nghĩ đến thứ hai, buồn ghê",
      "đi dạo công viên, nắng nhẹ ghê",
      "cuối tuần là phải ăn một bữa thật ngon",
      "nằm đọc truyện cả buổi, không hối hận",
      "hẹn bạn đi chơi, hy vọng không ai hủy kèo",
      "giặt đồ phơi đồ, cuộc sống người lớn đó",
    ],
  },
  en: {
    morning: [
      "first coffee has not kicked in yet",
      "awake, but only about half of me",
      "what even is breakfast today?",
      "traffic already, and it is barely seven",
      "snoozed the alarm five times, personal record",
      "cool morning, decent mood",
      "that morning toast was surprisingly good",
      "opened my eyes and a deadline stared back",
      "morning playlist on to wake up my brain",
      "forgot my umbrella again, bold move",
      "second coffee, not counting the first",
      "mondays should come with a warning label",
      "scrolling the news to wake up slowly",
      "plan is to finish early today, famous last words",
      "yawning like it is a sport",
      "the neighbor's breakfast smells amazing",
    ],
    noon: [
      "hungry already, what is for lunch?",
      "post lunch sleepiness hits instantly",
      "the sun is too strong to go outside",
      "deciding between rice and noodles, a tough one",
      "ten minute nap, I promise",
      "iced tea at noon is pure happiness",
      "meeting over and my stomach is loud",
      "noon and I have done maybe half of nothing",
      "food delivery is late, fading away here",
      "ate too much, now I am useless",
      "it is so hot I might melt",
      "lunch was great, simple joys really",
      "a bit of scrolling before getting back to it",
      "anyone up for lunch?",
      "just a tiny nap on the desk",
      "the cafeteria ran out of my favorite again",
    ],
    afternoon: [
      "afternoon and my brain is still on morning mode",
      "need a milk tea right now",
      "two more hours, hang in there",
      "the deadline is breathing down my neck",
      "pretty afternoon light, stuck indoors",
      "counting minutes until clock out",
      "in a meeting but my mind left an hour ago",
      "sudden rain, stuck in a cafe",
      "hungry at three pm, anyone relate?",
      "rain on the roof sounds so soothing",
      "any plans for later?",
      "tired but pushing through a little more",
      "chill playlist on to beat the boredom",
      "just got more work, allow me a moment to cry",
      "snacks between tasks are a human right",
      "rush hour traffic, just looking at it is tiring",
    ],
    evening: [
      "off work, heading home",
      "what is for dinner that needs zero effort?",
      "cooking dinner and the kitchen is full of smoke",
      "tonight's rain sounds lovely",
      "lying on the couch, refusing to move",
      "new episode on, do not disturb",
      "home at last, life feels brighter",
      "thinking about a short evening walk",
      "replaying old songs, feeling nostalgic",
      "tiring day, but a good one",
      "fresh out of the shower, a new person",
      "the food delivery arrived, hallelujah",
      "scrolling and lost track of time",
      "it gets dark so early, the day just vanished",
      "dinner with friends soon, already starving",
      "tidied up a bit to feel useful",
    ],
    night: [
      "meant to sleep early, not sleepy yet",
      "eleven already, one more episode only",
      "lying in bed scrolling, again",
      "quiet night, soft music on",
      "early start tomorrow, whatever",
      "teeth brushed, almost asleep",
      "lying here thinking about random things",
      "warm milk then bed",
      "that is enough for today",
      "lights off, just the screen glowing",
      "eyes closing but the phone is still in my hand",
      "packed my stuff for tomorrow, so responsible",
      "the fan hums steadily, so sleepy",
      "anyone still up? feeling a little lonely",
      "counting sheep, probably will not work",
      "good night everyone, heading off soon",
    ],
    latenight: [
      "what time is it and why am I awake",
      "can not sleep, anyone up with me?",
      "late night hunger, instant noodles are calling",
      "tomorrow morning is going to hurt",
      "quiet night, overthinking everything",
      "music on low so the neighbors stay happy",
      "three am, officially a night owl",
      "dark circles just added a new floor",
      "tossing and turning, no luck",
      "deadline mode at midnight, be kind to me",
      "soft rain outside, honestly lovely",
      "ideas always show up late at night",
      "coffee right now would be a mistake",
      "one more episode and suddenly it is dawn",
      "crickets outside sound kind of nice",
      "sleeping now, for real this time",
    ],
    weekend: [
      "weekend, finally allowed to be lazy",
      "no alarm today, bliss",
      "sleeping in on weekends is a law",
      "coffee with a friend, talking about everything",
      "cleaning my room and it is never done",
      "up early on a weekend, make it make sense",
      "had plans but it rains, so staying in",
      "movie marathon all day, nobody can stop me",
      "weekend market run, bought more than needed",
      "trying a new recipe, hoping nothing burns",
      "sunday and already thinking about monday, sad",
      "walking in the park, such gentle sun",
      "weekends need one really good meal",
      "read all morning, zero regrets",
      "meeting friends later, hoping nobody cancels",
      "laundry day, peak adult life",
    ],
  },
};
