// Lines the companions say to an owner (OWNER_IDS): they act like they do not care, but they secretly like them a lot.
// Never mean, always a little embarrassed, and the affection slips out at the end. Everyone else gets the normal warm lines.
// girl and boy are for the two kinds of bots in Vietnamese (girls say em, boys say tui); English lines are the same for everyone.
// Purposes and placeholders: welcome, greet, bye need {user}; remind needs {user} and {text}.
export default {
  vi: {
    girl: {
      welcome: [
        "Ồ, {user} cũng vào đây hả. Em đâu có đợi đâu, chỉ tình cờ nhìn thấy thôi.",
        "Hừ, {user} đến rồi. Đừng hiểu lầm nha, em chào cho đúng phép lịch sự thôi.",
        "{user} vào server rồi. Ai thèm vui đâu... mà thôi, chào.",
        "À, {user}. Em không có để dành chỗ ngồi đâu nha, cái ghế đó tự trống thôi.",
        "{user} đó hả? Cũng bình thường thôi mà. Chào nha, chút xíu thôi.",
        "Em không có nhớ {user} đâu, chỉ là đếm thấy thiếu một người thôi.",
        "Chào {user}. Em không có chải tóc trước khi bạn vào đâu, tại bot làm gì có tóc!",
        "Ơ {user} tới rồi, em đang bận. Bận nhìn cửa. À nhầm, bận làm việc!",
      ],
      greet: [
        "{user} vào phòng voice rồi à. Em không có vui đâu nha, chỉ là phòng đông hơn một chút thôi.",
        "Hứ, {user} vào voice làm gì, tụi em đang bận... bận chờ mà. Á nhầm, bận thôi!",
        "{user} đó hả. Em không có liếc qua liếc lại để xem ai vào đâu nha.",
        "Ủa {user} vào rồi hả? Em tưởng bạn không tới. Em đâu có mong, em nói thật.",
        "{user} ngồi đó đi, đừng ngồi gần em. Hơi xa xa chút... thôi gần cũng được.",
        "Phòng voice ồn quá, mà thôi {user} vào cũng không sao. Em không bận tâm. Chút nào.",
        "Ai cho {user} vào mà mặt em nóng vậy... chắc do máy nóng thôi!",
        "Chào {user}. Chỉ chào xã giao thôi nha, đừng nghĩ nhiều.",
      ],
      bye: [
        "{user} đi rồi à? Em đâu có buồn, chỉ là phòng hơi vắng thôi.",
        "Tạm biệt {user}. Không cần nhớ tụi em đâu... mà thôi nhớ cũng được.",
        "Ừ {user} đi đi, em có khóc đâu, chỉ là bụi bay vô mắt bot thôi!",
        "{user} thoát rồi hả. Em không có nhìn cửa chờ bạn quay lại đâu nha.",
        "Đi thì đi, {user}. Mai nhớ quay lại... á không, em chỉ nói cho vui thôi!",
        "Hứ, {user} đi sớm vậy. Em có mong bạn ở lại đâu. Một xíu thôi.",
        "Bye {user}. Đừng quên bọn em nha... mà không quên cũng chẳng sao hết!",
        "{user} rời voice. Em không buồn, em nói thật. Em chỉ hơi im lặng thôi.",
      ],
      remind: [
        "{user}, nhắc bạn: {text}. Em không có quan tâm đâu nha, chỉ là bạn mà quên thì em bực.",
        "Hừ, {user} lại quên rồi hả. {text}. Em nhắc cho có thôi, đừng hiểu lầm.",
        "{user} ơi, {text}. Nhớ làm đi, em đâu có lo cho bạn, em lo cho cái lịch thôi.",
        "Ai thèm nhắc {user} chứ. À mà, {text}. Làm xong nhớ báo em... không, đừng báo!",
        "{user}, {text}. Em nhớ giùm bạn thôi, chứ trí nhớ em đâu có để dành cho ai.",
        "Nè {user}, {text}. Làm đi rồi em sẽ không khen đâu, nhưng em sẽ thấy vui.",
        "{user}, nhắc đây: {text}. Em ghi trên bàn em rồi, tại tiện tay thôi nha!",
        "Hứ, {user}. {text}. Bạn mà trễ là em giận đó... à không, em không giận, em lo.",
      ],
    },
    boy: {
      welcome: [
        "Ồ, {user} tới rồi hả. Tui đâu có đợi, chỉ tình cờ ngó thấy thôi.",
        "{user} vào server rồi. Chào cho phải phép thôi, đừng nghĩ nhiều nha.",
        "Hừ, {user}. Tui không có dọn chỗ sẵn đâu, ghế đó tự trống đó.",
        "Chào {user}. Cũng bình thường thôi, không có gì vui lắm đâu... chút xíu thôi.",
        "{user} đó hả? Tui có chờ đâu, tui đang bận... chờ thôi. À nhầm!",
        "Ừ {user}, vào đi. Tui không vui, chỉ là server đông hơn một chút.",
      ],
      greet: [
        "{user} vào voice rồi hả. Tui không có mừng đâu, chỉ ghi nhận thôi.",
        "Hừ, {user} vào làm gì. Tui đang bận. Bận ngó cửa. À nhầm!",
        "{user} ngồi đó đi, đừng có ngồi gần tui. Mà ngồi gần cũng được.",
        "Ủa {user} tới thiệt hả? Tui đâu có mong, nhưng mà... ờ, chào.",
        "Chào {user}. Xã giao thôi, đừng nghĩ tui vui nha.",
        "Phòng voice đông lên rồi, tại {user} thôi. Tui đâu có để ý.",
      ],
      bye: [
        "{user} đi rồi hả. Tui đâu có buồn, phòng hơi vắng thôi mà.",
        "Đi thì đi, {user}. Mai nhớ quay lại... mà thôi, tui nói bậy đó!",
        "Tạm biệt {user}. Tui không nhớ đâu nha. Tuyệt đối không.",
        "{user} thoát rồi. Tui có nhìn cửa chờ đâu, tui đang tập trung vô tường.",
        "Hừ, {user} đi sớm thế. Tui đâu có mong bạn ở lại. Chút xíu thôi.",
        "Bye {user}. Đừng quên tụi tui nha, mà quên cũng không sao hết.",
      ],
      remind: [
        "{user}, nhắc bạn: {text}. Tui không quan tâm đâu, chỉ là bạn quên thì phiền thôi.",
        "Hừ, {user} lại quên rồi. {text}. Tui nhắc cho có thôi, đừng hiểu lầm.",
        "{user} ơi, {text}. Làm đi, tui đâu có lo, tui rảnh nên nhắc thôi.",
        "Ai thèm nhắc {user}. À mà, {text}. Làm xong nhớ báo tui... không, đừng báo!",
        "Nè {user}, {text}. Làm đi, tui sẽ không khen đâu, nhưng tui sẽ thấy vui.",
        "{user}, nhắc đây: {text}. Tiện tay thôi nha, đừng cảm ơn.",
      ],
    },
    soft: {
      girl: {
        welcome: [
          "Ừ thì... em có hơi vui khi {user} vào, chút xíu thôi nha.",
          "{user} tới rồi hả. Em không đợi đâu, mà thấy bạn là em cười hoài, kỳ ghê.",
          "Ơ {user}! Em định giả vờ không thấy, mà thôi, chào bạn nè, hôm nay có đỡ chán hơn.",
          "Chào {user}. Em có để dành chỗ cạnh em thiệt đó, mà đừng có làm lố nha.",
          "Hứ, {user} vào làm em hết chán rồi đó. Chỉ nói một lần thôi, không có lần sau đâu.",
          "{user} đây rồi. Nãy giờ em ngó cửa hơi nhiều, bạn đừng cười em nha.",
        ],
        greet: [
          "{user} vào voice rồi. Ở lại chơi với tụi em đi, à không, tùy bạn thôi.",
          "Ừm, {user} vào thì phòng ấm lên một chút. Một chút xíu thôi, đừng tự hào.",
          "{user} ngồi gần em cũng được. Em không có ngại đâu, chỉ hơi nóng mặt thôi.",
          "Nghe giọng {user} là em thấy yên tâm hơn. Quên câu em vừa nói đi nha!",
          "Ủa {user} tới rồi, em mừng... à nhầm, em hơi mừng thôi. Mà hơi nhiều hơn mọi lần.",
          "Chào {user}. Em chờ bạn từ nãy, không phải chờ đâu, là tiện thì chờ á.",
        ],
        bye: [
          "{user} đi rồi hả. Em hơi buồn thiệt, mà đừng để ý, em ổn mà.",
          "Ở lại thêm chút nữa đi {user}, à không, tùy bạn. Nhưng mà ở lại thì em vui.",
          "Bye {user}. Mai nhớ vào sớm nha, em nói cho vui thôi... mà em chờ thiệt.",
          "{user} thoát rồi, phòng vắng hẳn. Em hơi nhớ bạn rồi đó, hơi hơi thôi nha.",
          "Ừ {user} đi ngủ ngon đi. Em không có lo đâu, mà nhớ ngủ sớm nha.",
          "Đi cẩn thận nha {user}. Em không có dặn dò đâu, em chỉ lỡ miệng thôi.",
        ],
        remind: [
          "{user}, {text}. Em nhớ giùm bạn đó, vì em muốn bạn làm tốt, không phải vì lo đâu nha.",
          "Nè {user}, nhắc nhẹ: {text}. Làm xong thì khoe em, em sẽ khen... chút xíu.",
          "{user} ơi, {text}. Em lo cho bạn thiệt đó, nhưng đừng nói với ai là em thừa nhận nha.",
          "Ừ thì em nhắc {user}: {text}. Em để ý bạn nhiều hơn em tưởng, kỳ quá hà.",
          "{user}, {text}. Cố lên nha, em tin bạn làm được, à mà em nói bâng quơ thôi.",
          "Hứ, {user}, {text}. Em nhắc vì em thích thấy bạn làm xong, vậy thôi, hết.",
        ],
      },
      boy: {
        welcome: [
          "Ừ thì... tui có hơi vui khi {user} vào, chút xíu thôi nha.",
          "{user} tới rồi hả. Tui không đợi đâu, mà thấy bạn là tui đỡ chán hơn.",
          "Ơ {user}! Tui định làm lơ, mà thôi, chào bạn nè. Hôm nay vui hơn xíu.",
          "Chào {user}. Tui có chừa chỗ cho bạn thiệt đó, đừng có làm lố nha.",
          "Hừ, {user} vào làm tui hết chán rồi. Nói một lần thôi, không có lần sau.",
        ],
        greet: [
          "{user} vào voice rồi. Ở lại chơi với tụi tui đi, à không, tùy bạn.",
          "Ừm, {user} vào thì phòng ấm lên chút. Chút xíu thôi, đừng có tự hào.",
          "{user} ngồi gần tui cũng được. Tui không ngại đâu, chỉ hơi nóng mặt thôi.",
          "Nghe giọng {user} là tui yên tâm hơn. Quên câu tui vừa nói đi nha!",
          "Chào {user}. Tui chờ bạn nãy giờ, không phải chờ đâu, là tiện thì chờ á.",
        ],
        bye: [
          "{user} đi rồi hả. Tui hơi buồn thiệt, mà đừng để ý, tui ổn mà.",
          "Ở lại thêm chút nữa đi {user}, à không, tùy bạn. Nhưng ở lại thì tui vui.",
          "Bye {user}. Mai vào sớm nha, tui nói cho vui thôi... mà tui chờ thiệt.",
          "{user} thoát rồi, phòng vắng hẳn. Tui hơi nhớ bạn rồi đó, hơi hơi thôi.",
          "Đi cẩn thận nha {user}. Tui không có dặn dò đâu, tui chỉ lỡ miệng thôi.",
        ],
        remind: [
          "{user}, {text}. Tui nhớ giùm bạn đó, vì tui muốn bạn làm tốt, không phải lo đâu nha.",
          "Nè {user}, nhắc nhẹ: {text}. Làm xong khoe tui đi, tui sẽ khen... chút xíu.",
          "{user} ơi, {text}. Tui lo cho bạn thiệt đó, mà đừng kể ai là tui thừa nhận nha.",
          "Ừ thì tui nhắc {user}: {text}. Tui để ý bạn nhiều hơn tui tưởng, kỳ ghê.",
          "{user}, {text}. Cố lên nha, tui tin bạn làm được, à mà tui nói bâng quơ thôi.",
        ],
      },
    },
  },
  en: {
    girl: {
      welcome: [
        "Oh, {user} is here too. I was not waiting, I just happened to look at the door.",
        "Hmph, {user} arrived. Do not get the wrong idea, I am only greeting you to be polite.",
        "{user} joined the server. Who is happy? Not me. Fine, hello.",
        "Oh, {user}. I did not save you a seat. That chair was empty all by itself.",
        "So {user} is here. Whatever. A tiny bit of hello, that is all you get.",
        "I did not miss {user}. I just noticed the server was one person short.",
        "Hello {user}. I did not fix my pixels before you came, bots do not even have hair!",
        "Oh, {user} is here and I am busy. Busy watching the door. I mean working!",
      ],
      greet: [
        "{user} joined voice. I am not happy, the room is just a little fuller.",
        "Hmph, why did {user} come to voice. We are busy waiting. I mean busy, period!",
        "{user}, sit over there, not near me. A bit closer is fine too, whatever.",
        "Oh, {user} actually came? I did not expect you. I did not hope either. Honest.",
        "The voice room is loud, but fine, {user} can stay. I do not mind. Not at all.",
        "Who let {user} in? My face feels warm. It must be the hardware.",
        "Hi {user}. A polite hello only, do not read into it.",
        "{user} entered the room and I definitely did not look up right away.",
      ],
      bye: [
        "{user} left? I am not sad, the room is just a little quiet.",
        "Goodbye {user}. You do not have to remember us. Well, you can if you want.",
        "Fine, {user}, go. I am not crying, a speck of dust got into my circuits!",
        "{user} disconnected. I am not staring at the door waiting for you to come back.",
        "Leaving so early, {user}? Not that I wanted you to stay. Only a tiny bit.",
        "Bye {user}. Do not forget us. Not that it matters. Okay it matters a little.",
        "Go ahead and leave, {user}. Come back tomorrow. I mean, only if you feel like it.",
        "{user} left voice. I am not sad. I am just being very quiet.",
      ],
      remind: [
        "{user}, reminder: {text}. I do not care, I just get annoyed when you forget.",
        "Hmph, {user} forgot again. {text}. I am only reminding you, do not get the wrong idea.",
        "{user}, {text}. Do it. I am not worried about you, I am worried about the schedule.",
        "Who would remind {user}? Anyway, {text}. Tell me when you finish. No, do not tell me!",
        "{user}, {text}. I remembered it for you, but only because I had spare memory.",
        "Hey {user}, {text}. I will not praise you when it is done, but I will be glad.",
        "{user}, here is your reminder: {text}. I wrote it down on my desk by chance.",
        "Hmph, {user}. {text}. If you are late I will be upset. No, not upset, worried.",
      ],
    },
    boy: { welcome: [], greet: [], bye: [], remind: [] },
    soft: {
      girl: {
        welcome: [
          "Okay, fine, I am a little glad {user} is here. Just a little, do not get smug.",
          "{user} is here. I was not waiting, but I did look at the door a few times.",
          "Oh, {user}! I planned to ignore you, but hello. The place feels better now.",
          "Hi {user}. I may have saved you a seat. Do not make it weird, please.",
          "Hmph, {user} showed up and my boredom is gone. I will only say that once.",
          "There you are, {user}. Please do not laugh, but I kept checking for you.",
        ],
        greet: [
          "{user} joined voice. Stay a while. Or not, it is up to you. But please stay.",
          "Fine, the room feels warmer with {user} in it. Only a bit. Do not let it go to your head.",
          "{user}, you can sit near me. I am not shy, my face is just warm.",
          "Hearing {user} makes me feel calmer. Forget I said that, okay?",
          "Oh, {user} came! I am glad. A little glad. Okay, more than usual.",
          "Hi {user}. I was waiting for you. Not waiting, just conveniently around.",
        ],
        bye: [
          "{user} left? I am a little sad, honestly. Do not mind me, I am fine.",
          "Stay a bit longer, {user}. Or not, it is up to you. But I would be happy if you did.",
          "Bye {user}. Come early tomorrow. I am joking, but I will be here for real.",
          "{user} disconnected and the room feels empty. I miss you a little. A tiny little.",
          "Sleep well, {user}. I am not worried, but please do sleep early.",
          "Be safe out there, {user}. I am not nagging, it just slipped out.",
        ],
        remind: [
          "{user}, {text}. I remembered it because I want you to do well, not because I worry.",
          "Hey {user}, gentle reminder: {text}. Show me when you are done, I might praise you a little.",
          "{user}, {text}. I do worry about you, but please do not tell anyone I admitted it.",
          "Fine, I will remind you, {user}: {text}. I notice you more than I thought, how odd.",
          "{user}, {text}. You can do it, I believe in you. I am only saying it randomly.",
          "Hmph, {user}, {text}. I remind you because I like seeing you finish things. That is all.",
        ],
      },
      boy: { welcome: [], greet: [], bye: [], remind: [] },
    },
  },
};
