// Lines for /lamsong, the "stadium wave" of emoji across several companions. The bot in the middle posts one chant line.
// peak lines are short chants; named lines use {ten}, the name the member typed (exactly once).

const WAVE = {
  vi: {
    peak: [
      "CỐ LÊN!!!",
      "ĐỈNH QUÁ!!!",
      "WIN ĐI!!!",
      "TIẾN LÊN NÀO!!!",
      "KHÔNG THỂ DỪNG LẠI!!!",
      "CHIẾN THẮNG LÀ CỦA CHÚNG TA!!!",
      "HÔ LÊN NÀO CẢ NHÀ!!!",
      "MỘT, HAI, BA, CỐ LÊN!!!",
      "CẢ SERVER CÙNG CỔ VŨ!!!",
      "QUÁ ĐỈNH LUÔN!!!",
      "KHÔNG GÌ CẢN NỔI!!!",
      "BÙNG NỔ ĐI!!!",
      "SÓNG ĐÃ LÊN ĐỈNH RỒI!!!",
      "TIN LÀ SẼ THẮNG!!!",
      "VÔ ĐỊCH VÔ ĐỊCH!!!",
      "CHÁY HẾT MÌNH NÀO!!!",
    ],
    named: [
      "{ten} ƠI CỐ LÊN!!!",
      "{ten} ĐỈNH QUÁ!!!",
      "CẢ SERVER CỔ VŨ {ten}!!!",
      "{ten} WIN ĐI!!!",
      "{ten} LÀ NHẤT!!!",
      "HÔ LÊN CHO {ten} NÀO!!!",
      "{ten} KHÔNG THỂ DỪNG LẠI!!!",
      "TIẾN LÊN {ten} ƠI!!!",
      "{ten} VÔ ĐỊCH!!!",
      "CHÚNG TÔI TIN {ten}!!!",
      "{ten} ƠI, SÓNG NÀY DÀNH CHO BẠN!!!",
      "BÙNG NỔ ĐI {ten}!!!",
    ],
  },
  en: {
    peak: [
      "WE BELIEVE!!!",
      "GO GO GO!!!",
      "LET'S GOOO!!!",
      "YOU CAN DO IT!!!",
      "UNSTOPPABLE!!!",
      "THE WHOLE SERVER IS WITH YOU!!!",
      "ONE, TWO, THREE, GO!!!",
      "NOBODY CAN STOP US!!!",
      "MAKE SOME NOISE!!!",
      "VICTORY IS OURS!!!",
      "THE WAVE HAS PEAKED!!!",
      "ABSOLUTELY LEGENDARY!!!",
      "BRING THE ENERGY!!!",
      "CHAMPIONS, CHAMPIONS!!!",
      "GIVE IT EVERYTHING!!!",
      "WE ARE ON FIRE!!!",
    ],
    named: [
      "{ten} YOU CAN DO IT!!!",
      "GO {ten} GO!!!",
      "WE BELIEVE IN {ten}!!!",
      "THE WHOLE SERVER CHEERS FOR {ten}!!!",
      "{ten} IS UNSTOPPABLE!!!",
      "MAKE SOME NOISE FOR {ten}!!!",
      "{ten} IS THE CHAMPION!!!",
      "LET'S GOOO {ten}!!!",
      "THIS WAVE IS FOR {ten}!!!",
      "{ten} IS ABSOLUTELY LEGENDARY!!!",
      "BRING THE ENERGY, {ten}!!!",
      "NOBODY CAN STOP {ten}!!!",
    ],
  },
};

export default WAVE;
